// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Pipe {
    // message fields
    pub path: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl Pipe {
    pub fn new() -> Pipe {
        ::std::default::Default::default()
    }

    // string path = 1;

    pub fn clear_path(&mut self) {
        self.path.clear();
    }

    // Param is passed by value, moved
    pub fn set_path(&mut self, v: ::std::string::String) {
        self.path = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_path(&mut self) -> &mut ::std::string::String {
        &mut self.path
    }

    // Take field
    pub fn take_path(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.path, ::std::string::String::new())
    }

    pub fn get_path(&self) -> &str {
        &self.path
    }
}

impl ::protobuf::Message for Pipe {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.path)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.path.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.path);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.path.is_empty() {
            os.write_string(1, &self.path)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Pipe {
        Pipe::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "path",
                    |m: &Pipe| { &m.path },
                    |m: &mut Pipe| { &mut m.path },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Pipe>(
                    "Pipe",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Pipe {
        static mut instance: ::protobuf::lazy::Lazy<Pipe> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Pipe,
        };
        unsafe {
            instance.get(Pipe::new)
        }
    }
}

impl ::protobuf::Clear for Pipe {
    fn clear(&mut self) {
        self.clear_path();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Pipe {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Pipe {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SocketAddress {
    // message fields
    pub protocol: SocketAddress_Protocol,
    pub address: ::std::string::String,
    pub resolver_name: ::std::string::String,
    pub ipv4_compat: bool,
    // message oneof groups
    pub port_specifier: ::std::option::Option<SocketAddress_oneof_port_specifier>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

#[derive(Clone,PartialEq)]
pub enum SocketAddress_oneof_port_specifier {
    port_value(u32),
    named_port(::std::string::String),
}

impl SocketAddress {
    pub fn new() -> SocketAddress {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.core.SocketAddress.Protocol protocol = 1;

    pub fn clear_protocol(&mut self) {
        self.protocol = SocketAddress_Protocol::TCP;
    }

    // Param is passed by value, moved
    pub fn set_protocol(&mut self, v: SocketAddress_Protocol) {
        self.protocol = v;
    }

    pub fn get_protocol(&self) -> SocketAddress_Protocol {
        self.protocol
    }

    // string address = 2;

    pub fn clear_address(&mut self) {
        self.address.clear();
    }

    // Param is passed by value, moved
    pub fn set_address(&mut self, v: ::std::string::String) {
        self.address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address(&mut self) -> &mut ::std::string::String {
        &mut self.address
    }

    // Take field
    pub fn take_address(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.address, ::std::string::String::new())
    }

    pub fn get_address(&self) -> &str {
        &self.address
    }

    // uint32 port_value = 3;

    pub fn clear_port_value(&mut self) {
        self.port_specifier = ::std::option::Option::None;
    }

    pub fn has_port_value(&self) -> bool {
        match self.port_specifier {
            ::std::option::Option::Some(SocketAddress_oneof_port_specifier::port_value(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_port_value(&mut self, v: u32) {
        self.port_specifier = ::std::option::Option::Some(SocketAddress_oneof_port_specifier::port_value(v))
    }

    pub fn get_port_value(&self) -> u32 {
        match self.port_specifier {
            ::std::option::Option::Some(SocketAddress_oneof_port_specifier::port_value(v)) => v,
            _ => 0,
        }
    }

    // string named_port = 4;

    pub fn clear_named_port(&mut self) {
        self.port_specifier = ::std::option::Option::None;
    }

    pub fn has_named_port(&self) -> bool {
        match self.port_specifier {
            ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_named_port(&mut self, v: ::std::string::String) {
        self.port_specifier = ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(v))
    }

    // Mutable pointer to the field.
    pub fn mut_named_port(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(_)) = self.port_specifier {
        } else {
            self.port_specifier = ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(::std::string::String::new()));
        }
        match self.port_specifier {
            ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_named_port(&mut self) -> ::std::string::String {
        if self.has_named_port() {
            match self.port_specifier.take() {
                ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    pub fn get_named_port(&self) -> &str {
        match self.port_specifier {
            ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(ref v)) => v,
            _ => "",
        }
    }

    // string resolver_name = 5;

    pub fn clear_resolver_name(&mut self) {
        self.resolver_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_resolver_name(&mut self, v: ::std::string::String) {
        self.resolver_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_resolver_name(&mut self) -> &mut ::std::string::String {
        &mut self.resolver_name
    }

    // Take field
    pub fn take_resolver_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.resolver_name, ::std::string::String::new())
    }

    pub fn get_resolver_name(&self) -> &str {
        &self.resolver_name
    }

    // bool ipv4_compat = 6;

    pub fn clear_ipv4_compat(&mut self) {
        self.ipv4_compat = false;
    }

    // Param is passed by value, moved
    pub fn set_ipv4_compat(&mut self, v: bool) {
        self.ipv4_compat = v;
    }

    pub fn get_ipv4_compat(&self) -> bool {
        self.ipv4_compat
    }
}

impl ::protobuf::Message for SocketAddress {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.protocol, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.address)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.port_specifier = ::std::option::Option::Some(SocketAddress_oneof_port_specifier::port_value(is.read_uint32()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.port_specifier = ::std::option::Option::Some(SocketAddress_oneof_port_specifier::named_port(is.read_string()?));
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.resolver_name)?;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.ipv4_compat = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.protocol != SocketAddress_Protocol::TCP {
            my_size += ::protobuf::rt::enum_size(1, self.protocol);
        }
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.address);
        }
        if !self.resolver_name.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.resolver_name);
        }
        if self.ipv4_compat != false {
            my_size += 2;
        }
        if let ::std::option::Option::Some(ref v) = self.port_specifier {
            match v {
                &SocketAddress_oneof_port_specifier::port_value(v) => {
                    my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
                },
                &SocketAddress_oneof_port_specifier::named_port(ref v) => {
                    my_size += ::protobuf::rt::string_size(4, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.protocol != SocketAddress_Protocol::TCP {
            os.write_enum(1, self.protocol.value())?;
        }
        if !self.address.is_empty() {
            os.write_string(2, &self.address)?;
        }
        if !self.resolver_name.is_empty() {
            os.write_string(5, &self.resolver_name)?;
        }
        if self.ipv4_compat != false {
            os.write_bool(6, self.ipv4_compat)?;
        }
        if let ::std::option::Option::Some(ref v) = self.port_specifier {
            match v {
                &SocketAddress_oneof_port_specifier::port_value(v) => {
                    os.write_uint32(3, v)?;
                },
                &SocketAddress_oneof_port_specifier::named_port(ref v) => {
                    os.write_string(4, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SocketAddress {
        SocketAddress::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<SocketAddress_Protocol>>(
                    "protocol",
                    |m: &SocketAddress| { &m.protocol },
                    |m: &mut SocketAddress| { &mut m.protocol },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "address",
                    |m: &SocketAddress| { &m.address },
                    |m: &mut SocketAddress| { &mut m.address },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_u32_accessor::<_>(
                    "port_value",
                    SocketAddress::has_port_value,
                    SocketAddress::get_port_value,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                    "named_port",
                    SocketAddress::has_named_port,
                    SocketAddress::get_named_port,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "resolver_name",
                    |m: &SocketAddress| { &m.resolver_name },
                    |m: &mut SocketAddress| { &mut m.resolver_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "ipv4_compat",
                    |m: &SocketAddress| { &m.ipv4_compat },
                    |m: &mut SocketAddress| { &mut m.ipv4_compat },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<SocketAddress>(
                    "SocketAddress",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static SocketAddress {
        static mut instance: ::protobuf::lazy::Lazy<SocketAddress> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const SocketAddress,
        };
        unsafe {
            instance.get(SocketAddress::new)
        }
    }
}

impl ::protobuf::Clear for SocketAddress {
    fn clear(&mut self) {
        self.clear_protocol();
        self.clear_address();
        self.clear_port_value();
        self.clear_named_port();
        self.clear_resolver_name();
        self.clear_ipv4_compat();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SocketAddress {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SocketAddress {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum SocketAddress_Protocol {
    TCP = 0,
    UDP = 1,
}

impl ::protobuf::ProtobufEnum for SocketAddress_Protocol {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SocketAddress_Protocol> {
        match value {
            0 => ::std::option::Option::Some(SocketAddress_Protocol::TCP),
            1 => ::std::option::Option::Some(SocketAddress_Protocol::UDP),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SocketAddress_Protocol] = &[
            SocketAddress_Protocol::TCP,
            SocketAddress_Protocol::UDP,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("SocketAddress_Protocol", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for SocketAddress_Protocol {
}

impl ::std::default::Default for SocketAddress_Protocol {
    fn default() -> Self {
        SocketAddress_Protocol::TCP
    }
}

impl ::protobuf::reflect::ProtobufValue for SocketAddress_Protocol {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TcpKeepalive {
    // message fields
    pub keepalive_probes: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub keepalive_time: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub keepalive_interval: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl TcpKeepalive {
    pub fn new() -> TcpKeepalive {
        ::std::default::Default::default()
    }

    // .google.protobuf.UInt32Value keepalive_probes = 1;

    pub fn clear_keepalive_probes(&mut self) {
        self.keepalive_probes.clear();
    }

    pub fn has_keepalive_probes(&self) -> bool {
        self.keepalive_probes.is_some()
    }

    // Param is passed by value, moved
    pub fn set_keepalive_probes(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.keepalive_probes = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_keepalive_probes(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.keepalive_probes.is_none() {
            self.keepalive_probes.set_default();
        }
        self.keepalive_probes.as_mut().unwrap()
    }

    // Take field
    pub fn take_keepalive_probes(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.keepalive_probes.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_keepalive_probes(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.keepalive_probes.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // .google.protobuf.UInt32Value keepalive_time = 2;

    pub fn clear_keepalive_time(&mut self) {
        self.keepalive_time.clear();
    }

    pub fn has_keepalive_time(&self) -> bool {
        self.keepalive_time.is_some()
    }

    // Param is passed by value, moved
    pub fn set_keepalive_time(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.keepalive_time = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_keepalive_time(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.keepalive_time.is_none() {
            self.keepalive_time.set_default();
        }
        self.keepalive_time.as_mut().unwrap()
    }

    // Take field
    pub fn take_keepalive_time(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.keepalive_time.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_keepalive_time(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.keepalive_time.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // .google.protobuf.UInt32Value keepalive_interval = 3;

    pub fn clear_keepalive_interval(&mut self) {
        self.keepalive_interval.clear();
    }

    pub fn has_keepalive_interval(&self) -> bool {
        self.keepalive_interval.is_some()
    }

    // Param is passed by value, moved
    pub fn set_keepalive_interval(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.keepalive_interval = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_keepalive_interval(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.keepalive_interval.is_none() {
            self.keepalive_interval.set_default();
        }
        self.keepalive_interval.as_mut().unwrap()
    }

    // Take field
    pub fn take_keepalive_interval(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.keepalive_interval.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_keepalive_interval(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.keepalive_interval.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }
}

impl ::protobuf::Message for TcpKeepalive {
    fn is_initialized(&self) -> bool {
        for v in &self.keepalive_probes {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.keepalive_time {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.keepalive_interval {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.keepalive_probes)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.keepalive_time)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.keepalive_interval)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.keepalive_probes.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.keepalive_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.keepalive_interval.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.keepalive_probes.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.keepalive_time.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.keepalive_interval.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TcpKeepalive {
        TcpKeepalive::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "keepalive_probes",
                    |m: &TcpKeepalive| { &m.keepalive_probes },
                    |m: &mut TcpKeepalive| { &mut m.keepalive_probes },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "keepalive_time",
                    |m: &TcpKeepalive| { &m.keepalive_time },
                    |m: &mut TcpKeepalive| { &mut m.keepalive_time },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "keepalive_interval",
                    |m: &TcpKeepalive| { &m.keepalive_interval },
                    |m: &mut TcpKeepalive| { &mut m.keepalive_interval },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<TcpKeepalive>(
                    "TcpKeepalive",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static TcpKeepalive {
        static mut instance: ::protobuf::lazy::Lazy<TcpKeepalive> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const TcpKeepalive,
        };
        unsafe {
            instance.get(TcpKeepalive::new)
        }
    }
}

impl ::protobuf::Clear for TcpKeepalive {
    fn clear(&mut self) {
        self.clear_keepalive_probes();
        self.clear_keepalive_time();
        self.clear_keepalive_interval();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TcpKeepalive {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TcpKeepalive {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BindConfig {
    // message fields
    pub source_address: ::protobuf::SingularPtrField<SocketAddress>,
    pub freebind: ::protobuf::SingularPtrField<::protobuf::well_known_types::BoolValue>,
    pub socket_options: ::protobuf::RepeatedField<super::base::SocketOption>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl BindConfig {
    pub fn new() -> BindConfig {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.core.SocketAddress source_address = 1;

    pub fn clear_source_address(&mut self) {
        self.source_address.clear();
    }

    pub fn has_source_address(&self) -> bool {
        self.source_address.is_some()
    }

    // Param is passed by value, moved
    pub fn set_source_address(&mut self, v: SocketAddress) {
        self.source_address = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_source_address(&mut self) -> &mut SocketAddress {
        if self.source_address.is_none() {
            self.source_address.set_default();
        }
        self.source_address.as_mut().unwrap()
    }

    // Take field
    pub fn take_source_address(&mut self) -> SocketAddress {
        self.source_address.take().unwrap_or_else(|| SocketAddress::new())
    }

    pub fn get_source_address(&self) -> &SocketAddress {
        self.source_address.as_ref().unwrap_or_else(|| SocketAddress::default_instance())
    }

    // .google.protobuf.BoolValue freebind = 2;

    pub fn clear_freebind(&mut self) {
        self.freebind.clear();
    }

    pub fn has_freebind(&self) -> bool {
        self.freebind.is_some()
    }

    // Param is passed by value, moved
    pub fn set_freebind(&mut self, v: ::protobuf::well_known_types::BoolValue) {
        self.freebind = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_freebind(&mut self) -> &mut ::protobuf::well_known_types::BoolValue {
        if self.freebind.is_none() {
            self.freebind.set_default();
        }
        self.freebind.as_mut().unwrap()
    }

    // Take field
    pub fn take_freebind(&mut self) -> ::protobuf::well_known_types::BoolValue {
        self.freebind.take().unwrap_or_else(|| ::protobuf::well_known_types::BoolValue::new())
    }

    pub fn get_freebind(&self) -> &::protobuf::well_known_types::BoolValue {
        self.freebind.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::BoolValue::default_instance())
    }

    // repeated .envoy.api.v2.core.SocketOption socket_options = 3;

    pub fn clear_socket_options(&mut self) {
        self.socket_options.clear();
    }

    // Param is passed by value, moved
    pub fn set_socket_options(&mut self, v: ::protobuf::RepeatedField<super::base::SocketOption>) {
        self.socket_options = v;
    }

    // Mutable pointer to the field.
    pub fn mut_socket_options(&mut self) -> &mut ::protobuf::RepeatedField<super::base::SocketOption> {
        &mut self.socket_options
    }

    // Take field
    pub fn take_socket_options(&mut self) -> ::protobuf::RepeatedField<super::base::SocketOption> {
        ::std::mem::replace(&mut self.socket_options, ::protobuf::RepeatedField::new())
    }

    pub fn get_socket_options(&self) -> &[super::base::SocketOption] {
        &self.socket_options
    }
}

impl ::protobuf::Message for BindConfig {
    fn is_initialized(&self) -> bool {
        for v in &self.source_address {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.freebind {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.socket_options {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.source_address)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.freebind)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.socket_options)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.source_address.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.freebind.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.socket_options {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.source_address.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.freebind.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.socket_options {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BindConfig {
        BindConfig::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<SocketAddress>>(
                    "source_address",
                    |m: &BindConfig| { &m.source_address },
                    |m: &mut BindConfig| { &mut m.source_address },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::BoolValue>>(
                    "freebind",
                    |m: &BindConfig| { &m.freebind },
                    |m: &mut BindConfig| { &mut m.freebind },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::SocketOption>>(
                    "socket_options",
                    |m: &BindConfig| { &m.socket_options },
                    |m: &mut BindConfig| { &mut m.socket_options },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<BindConfig>(
                    "BindConfig",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static BindConfig {
        static mut instance: ::protobuf::lazy::Lazy<BindConfig> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const BindConfig,
        };
        unsafe {
            instance.get(BindConfig::new)
        }
    }
}

impl ::protobuf::Clear for BindConfig {
    fn clear(&mut self) {
        self.clear_source_address();
        self.clear_freebind();
        self.clear_socket_options();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BindConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BindConfig {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Address {
    // message oneof groups
    pub address: ::std::option::Option<Address_oneof_address>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

#[derive(Clone,PartialEq)]
pub enum Address_oneof_address {
    socket_address(SocketAddress),
    pipe(Pipe),
}

impl Address {
    pub fn new() -> Address {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.core.SocketAddress socket_address = 1;

    pub fn clear_socket_address(&mut self) {
        self.address = ::std::option::Option::None;
    }

    pub fn has_socket_address(&self) -> bool {
        match self.address {
            ::std::option::Option::Some(Address_oneof_address::socket_address(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_socket_address(&mut self, v: SocketAddress) {
        self.address = ::std::option::Option::Some(Address_oneof_address::socket_address(v))
    }

    // Mutable pointer to the field.
    pub fn mut_socket_address(&mut self) -> &mut SocketAddress {
        if let ::std::option::Option::Some(Address_oneof_address::socket_address(_)) = self.address {
        } else {
            self.address = ::std::option::Option::Some(Address_oneof_address::socket_address(SocketAddress::new()));
        }
        match self.address {
            ::std::option::Option::Some(Address_oneof_address::socket_address(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_socket_address(&mut self) -> SocketAddress {
        if self.has_socket_address() {
            match self.address.take() {
                ::std::option::Option::Some(Address_oneof_address::socket_address(v)) => v,
                _ => panic!(),
            }
        } else {
            SocketAddress::new()
        }
    }

    pub fn get_socket_address(&self) -> &SocketAddress {
        match self.address {
            ::std::option::Option::Some(Address_oneof_address::socket_address(ref v)) => v,
            _ => SocketAddress::default_instance(),
        }
    }

    // .envoy.api.v2.core.Pipe pipe = 2;

    pub fn clear_pipe(&mut self) {
        self.address = ::std::option::Option::None;
    }

    pub fn has_pipe(&self) -> bool {
        match self.address {
            ::std::option::Option::Some(Address_oneof_address::pipe(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_pipe(&mut self, v: Pipe) {
        self.address = ::std::option::Option::Some(Address_oneof_address::pipe(v))
    }

    // Mutable pointer to the field.
    pub fn mut_pipe(&mut self) -> &mut Pipe {
        if let ::std::option::Option::Some(Address_oneof_address::pipe(_)) = self.address {
        } else {
            self.address = ::std::option::Option::Some(Address_oneof_address::pipe(Pipe::new()));
        }
        match self.address {
            ::std::option::Option::Some(Address_oneof_address::pipe(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_pipe(&mut self) -> Pipe {
        if self.has_pipe() {
            match self.address.take() {
                ::std::option::Option::Some(Address_oneof_address::pipe(v)) => v,
                _ => panic!(),
            }
        } else {
            Pipe::new()
        }
    }

    pub fn get_pipe(&self) -> &Pipe {
        match self.address {
            ::std::option::Option::Some(Address_oneof_address::pipe(ref v)) => v,
            _ => Pipe::default_instance(),
        }
    }
}

impl ::protobuf::Message for Address {
    fn is_initialized(&self) -> bool {
        if let Some(Address_oneof_address::socket_address(ref v)) = self.address {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Address_oneof_address::pipe(ref v)) = self.address {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.address = ::std::option::Option::Some(Address_oneof_address::socket_address(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.address = ::std::option::Option::Some(Address_oneof_address::pipe(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.address {
            match v {
                &Address_oneof_address::socket_address(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Address_oneof_address::pipe(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.address {
            match v {
                &Address_oneof_address::socket_address(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Address_oneof_address::pipe(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Address {
        Address::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SocketAddress>(
                    "socket_address",
                    Address::has_socket_address,
                    Address::get_socket_address,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Pipe>(
                    "pipe",
                    Address::has_pipe,
                    Address::get_pipe,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Address>(
                    "Address",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Address {
        static mut instance: ::protobuf::lazy::Lazy<Address> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Address,
        };
        unsafe {
            instance.get(Address::new)
        }
    }
}

impl ::protobuf::Clear for Address {
    fn clear(&mut self) {
        self.clear_socket_address();
        self.clear_pipe();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Address {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Address {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CidrRange {
    // message fields
    pub address_prefix: ::std::string::String,
    pub prefix_len: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl CidrRange {
    pub fn new() -> CidrRange {
        ::std::default::Default::default()
    }

    // string address_prefix = 1;

    pub fn clear_address_prefix(&mut self) {
        self.address_prefix.clear();
    }

    // Param is passed by value, moved
    pub fn set_address_prefix(&mut self, v: ::std::string::String) {
        self.address_prefix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address_prefix(&mut self) -> &mut ::std::string::String {
        &mut self.address_prefix
    }

    // Take field
    pub fn take_address_prefix(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.address_prefix, ::std::string::String::new())
    }

    pub fn get_address_prefix(&self) -> &str {
        &self.address_prefix
    }

    // .google.protobuf.UInt32Value prefix_len = 2;

    pub fn clear_prefix_len(&mut self) {
        self.prefix_len.clear();
    }

    pub fn has_prefix_len(&self) -> bool {
        self.prefix_len.is_some()
    }

    // Param is passed by value, moved
    pub fn set_prefix_len(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.prefix_len = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_prefix_len(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.prefix_len.is_none() {
            self.prefix_len.set_default();
        }
        self.prefix_len.as_mut().unwrap()
    }

    // Take field
    pub fn take_prefix_len(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.prefix_len.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_prefix_len(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.prefix_len.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }
}

impl ::protobuf::Message for CidrRange {
    fn is_initialized(&self) -> bool {
        for v in &self.prefix_len {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.address_prefix)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.prefix_len)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.address_prefix.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.address_prefix);
        }
        if let Some(ref v) = self.prefix_len.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.address_prefix.is_empty() {
            os.write_string(1, &self.address_prefix)?;
        }
        if let Some(ref v) = self.prefix_len.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CidrRange {
        CidrRange::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "address_prefix",
                    |m: &CidrRange| { &m.address_prefix },
                    |m: &mut CidrRange| { &mut m.address_prefix },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "prefix_len",
                    |m: &CidrRange| { &m.prefix_len },
                    |m: &mut CidrRange| { &mut m.prefix_len },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<CidrRange>(
                    "CidrRange",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static CidrRange {
        static mut instance: ::protobuf::lazy::Lazy<CidrRange> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const CidrRange,
        };
        unsafe {
            instance.get(CidrRange::new)
        }
    }
}

impl ::protobuf::Clear for CidrRange {
    fn clear(&mut self) {
        self.clear_address_prefix();
        self.clear_prefix_len();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CidrRange {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CidrRange {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1fenvoy/api/v2/core/address.proto\x12\x11envoy.api.v2.core\x1a\x1cen\
    voy/api/v2/core/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17\
    validate/validate.proto\x1a\x14gogoproto/gogo.proto\"%\n\x04Pipe\x12\x1d\
    \n\x04path\x18\x01\x20\x01(\tR\x04pathB\t\xba\xe9\xc0\x03\x04r\x02\x20\
    \x01\"\xd9\x02\n\rSocketAddress\x12Q\n\x08protocol\x18\x01\x20\x01(\x0e2\
    ).envoy.api.v2.core.SocketAddress.ProtocolR\x08protocolB\n\xba\xe9\xc0\
    \x03\x05\x82\x01\x02\x10\x01\x12#\n\x07address\x18\x02\x20\x01(\tR\x07ad\
    dressB\t\xba\xe9\xc0\x03\x04r\x02\x20\x01\x12,\n\nport_value\x18\x03\x20\
    \x01(\rH\0R\tportValueB\x0b\xba\xe9\xc0\x03\x06*\x04\x18\xff\xff\x03\x12\
    \x1f\n\nnamed_port\x18\x04\x20\x01(\tH\0R\tnamedPort\x12#\n\rresolver_na\
    me\x18\x05\x20\x01(\tR\x0cresolverName\x12\x1f\n\x0bipv4_compat\x18\x06\
    \x20\x01(\x08R\nipv4Compat\"\"\n\x08Protocol\x12\x07\n\x03TCP\x10\0\x12\
    \x07\n\x03UDP\x10\x01\x1a\x04\x88\xa3\x1e\0B\x17\n\x0eport_specifier\x12\
    \x05\xb8\xe9\xc0\x03\x01\"\xe9\x01\n\x0cTcpKeepalive\x12G\n\x10keepalive\
    _probes\x18\x01\x20\x01(\x0b2\x1c.google.protobuf.UInt32ValueR\x0fkeepal\
    iveProbes\x12C\n\x0ekeepalive_time\x18\x02\x20\x01(\x0b2\x1c.google.prot\
    obuf.UInt32ValueR\rkeepaliveTime\x12K\n\x12keepalive_interval\x18\x03\
    \x20\x01(\x0b2\x1c.google.protobuf.UInt32ValueR\x11keepaliveInterval\"\
    \xe5\x01\n\nBindConfig\x12W\n\x0esource_address\x18\x01\x20\x01(\x0b2\
    \x20.envoy.api.v2.core.SocketAddressR\rsourceAddressB\x0e\xc8\xde\x1f\0\
    \xba\xe9\xc0\x03\x05\x8a\x01\x02\x10\x01\x126\n\x08freebind\x18\x02\x20\
    \x01(\x0b2\x1a.google.protobuf.BoolValueR\x08freebind\x12F\n\x0esocket_o\
    ptions\x18\x03\x20\x03(\x0b2\x1f.envoy.api.v2.core.SocketOptionR\rsocket\
    Options\"\x95\x01\n\x07Address\x12I\n\x0esocket_address\x18\x01\x20\x01(\
    \x0b2\x20.envoy.api.v2.core.SocketAddressH\0R\rsocketAddress\x12-\n\x04p\
    ipe\x18\x02\x20\x01(\x0b2\x17.envoy.api.v2.core.PipeH\0R\x04pipeB\x10\n\
    \x07address\x12\x05\xb8\xe9\xc0\x03\x01\"\x86\x01\n\tCidrRange\x120\n\
    \x0eaddress_prefix\x18\x01\x20\x01(\tR\raddressPrefixB\t\xba\xe9\xc0\x03\
    \x04r\x02\x20\x01\x12G\n\nprefix_len\x18\x02\x20\x01(\x0b2\x1c.google.pr\
    otobuf.UInt32ValueR\tprefixLenB\n\xba\xe9\xc0\x03\x05*\x03\x18\x80\x01B5\
    \n\x1fio.envoyproxy.envoy.api.v2.coreB\x0cAddressProtoP\x01\xa8\xe2\x1e\
    \x01J\xa5*\n\x06\x12\x04\0\0x\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\
    \n\x01\x02\x12\x03\x02\x08\x19\n\x08\n\x01\x08\x12\x03\x04\0-\n\t\n\x02\
    \x08\x08\x12\x03\x04\0-\n\x08\n\x01\x08\x12\x03\x05\0\"\n\t\n\x02\x08\n\
    \x12\x03\x05\0\"\n\x08\n\x01\x08\x12\x03\x06\08\n\t\n\x02\x08\x01\x12\
    \x03\x06\08\n\t\n\x02\x03\0\x12\x03\x08\x07%\n\t\n\x02\x03\x01\x12\x03\n\
    \x07'\n\t\n\x02\x03\x02\x12\x03\x0c\x07\x20\n\t\n\x02\x03\x03\x12\x03\r\
    \x07\x1d\n\x08\n\x01\x08\x12\x03\x0f\0$\n\x0b\n\x04\x08\xa5\xec\x03\x12\
    \x03\x0f\0$\n2\n\x02\x04\0\x12\x04\x13\0\x19\x012&\x20[#protodoc-title:\
    \x20Network\x20addresses]\n\n\n\n\x03\x04\0\x01\x12\x03\x13\x08\x0c\n\
    \xf6\x01\n\x04\x04\0\x02\0\x12\x03\x18\x02:\x1a\xe8\x01\x20Unix\x20Domai\
    n\x20Socket\x20path.\x20On\x20Linux,\x20paths\x20starting\x20with\x20'@'\
    \x20will\x20use\x20the\n\x20abstract\x20namespace.\x20The\x20starting\
    \x20'@'\x20is\x20replaced\x20by\x20a\x20null\x20byte\x20by\x20Envoy.\n\
    \x20Paths\x20starting\x20with\x20'@'\x20will\x20result\x20in\x20an\x20er\
    ror\x20in\x20environments\x20other\x20than\n\x20Linux.\n\n\r\n\x05\x04\0\
    \x02\0\x04\x12\x04\x18\x02\x13\x0e\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\
    \x18\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x18\t\r\n\x0c\n\x05\x04\
    \0\x02\0\x03\x12\x03\x18\x10\x11\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03\x18\
    \x129\n\x11\n\n\x04\0\x02\0\x08\x97\x8d8\x0e\x04\x12\x03\x18\x138\n\n\n\
    \x02\x04\x01\x12\x04\x1b\0B\x01\n\n\n\x03\x04\x01\x01\x12\x03\x1b\x08\
    \x15\n\x0c\n\x04\x04\x01\x04\0\x12\x04\x1c\x02!\x03\n\x0c\n\x05\x04\x01\
    \x04\0\x01\x12\x03\x1c\x07\x0f\n\x0c\n\x05\x04\x01\x04\0\x03\x12\x03\x1d\
    \x043\n\x0f\n\x08\x04\x01\x04\0\x03\xb1\xe4\x03\x12\x03\x1d\x043\n\r\n\
    \x06\x04\x01\x04\0\x02\0\x12\x03\x1e\x04\x0c\n\x0e\n\x07\x04\x01\x04\0\
    \x02\0\x01\x12\x03\x1e\x04\x07\n\x0e\n\x07\x04\x01\x04\0\x02\0\x02\x12\
    \x03\x1e\n\x0b\n)\n\x06\x04\x01\x04\0\x02\x01\x12\x03\x20\x04\x0c\x1a\
    \x1a\x20[#not-implemented-hide:]\n\n\x0e\n\x07\x04\x01\x04\0\x02\x01\x01\
    \x12\x03\x20\x04\x07\n\x0e\n\x07\x04\x01\x04\0\x02\x01\x02\x12\x03\x20\n\
    \x0b\n\x0b\n\x04\x04\x01\x02\0\x12\x03\"\x02D\n\r\n\x05\x04\x01\x02\0\
    \x04\x12\x04\"\x02!\x03\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\"\x02\n\n\
    \x0c\n\x05\x04\x01\x02\0\x01\x12\x03\"\x0b\x13\n\x0c\n\x05\x04\x01\x02\0\
    \x03\x12\x03\"\x16\x17\n\x0c\n\x05\x04\x01\x02\0\x08\x12\x03\"\x18C\n\
    \x11\n\n\x04\x01\x02\0\x08\x97\x8d8\x10\x02\x12\x03\"\x19B\n\xea\x06\n\
    \x04\x04\x01\x02\x01\x12\x03.\x02=\x1a\xdc\x06\x20The\x20address\x20for\
    \x20this\x20socket.\x20:ref:`Listeners\x20<config_listeners>`\x20will\
    \x20bind\n\x20to\x20the\x20address.\x20An\x20empty\x20address\x20is\x20n\
    ot\x20allowed.\x20Specify\x20``0.0.0.0``\x20or\x20``::``\n\x20to\x20bind\
    \x20to\x20any\x20address.\x20[#comment:TODO(zuercher)\x20reinstate\x20wh\
    en\x20implemented:\n\x20It\x20is\x20possible\x20to\x20distinguish\x20a\
    \x20Listener\x20address\x20via\x20the\x20prefix/suffix\x20matching\n\x20\
    in\x20:ref:`FilterChainMatch\x20<envoy_api_msg_listener.FilterChainMatch\
    >`.]\x20When\x20used\n\x20within\x20an\x20upstream\x20:ref:`BindConfig\
    \x20<envoy_api_msg_core.BindConfig>`,\x20the\x20address\n\x20controls\
    \x20the\x20source\x20address\x20of\x20outbound\x20connections.\x20For\
    \x20:ref:`clusters\n\x20<envoy_api_msg_Cluster>`,\x20the\x20cluster\x20t\
    ype\x20determines\x20whether\x20the\n\x20address\x20must\x20be\x20an\x20\
    IP\x20(*STATIC*\x20or\x20*EDS*\x20clusters)\x20or\x20a\x20hostname\x20re\
    solved\x20by\x20DNS\n\x20(*STRICT_DNS*\x20or\x20*LOGICAL_DNS*\x20cluster\
    s).\x20Address\x20resolution\x20can\x20be\x20customized\n\x20via\x20:ref\
    :`resolver_name\x20<envoy_api_field_core.SocketAddress.resolver_name>`.\
    \n\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04.\x02\"D\n\x0c\n\x05\x04\x01\x02\
    \x01\x05\x12\x03.\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03.\t\x10\
    \n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03.\x13\x14\n\x0c\n\x05\x04\x01\
    \x02\x01\x08\x12\x03.\x15<\n\x11\n\n\x04\x01\x02\x01\x08\x97\x8d8\x0e\
    \x04\x12\x03.\x16;\n\x0c\n\x04\x04\x01\x08\0\x12\x04/\x026\x03\n\x0c\n\
    \x05\x04\x01\x08\0\x01\x12\x03/\x08\x16\n\x0c\n\x05\x04\x01\x08\0\x02\
    \x12\x030\x04&\n\x0f\n\x08\x04\x01\x08\0\x02\x97\x8d8\x12\x030\x04&\n\
    \x0b\n\x04\x04\x01\x02\x02\x12\x031\x04@\n\x0c\n\x05\x04\x01\x02\x02\x05\
    \x12\x031\x04\n\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x031\x0b\x15\n\x0c\n\
    \x05\x04\x01\x02\x02\x03\x12\x031\x18\x19\n\x0c\n\x05\x04\x01\x02\x02\
    \x08\x12\x031\x1a?\n\x11\n\n\x04\x01\x02\x02\x08\x97\x8d8\x05\x03\x12\
    \x031\x1b>\n\xbe\x01\n\x04\x04\x01\x02\x03\x12\x035\x04\x1a\x1a\xb0\x01\
    \x20This\x20is\x20only\x20valid\x20if\x20:ref:`resolver_name\n\x20<envoy\
    _api_field_core.SocketAddress.resolver_name>`\x20is\x20specified\x20belo\
    w\x20and\x20the\n\x20named\x20resolver\x20is\x20capable\x20of\x20named\
    \x20port\x20resolution.\n\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x035\x04\n\
    \n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x035\x0b\x15\n\x0c\n\x05\x04\x01\
    \x02\x03\x03\x12\x035\x18\x19\n\x9c\x02\n\x04\x04\x01\x02\x04\x12\x03;\
    \x02\x1b\x1a\x8e\x02\x20The\x20name\x20of\x20the\x20resolver.\x20This\
    \x20must\x20have\x20been\x20registered\x20with\x20Envoy.\x20If\x20this\
    \x20is\n\x20empty,\x20a\x20context\x20dependent\x20default\x20applies.\
    \x20If\x20address\x20is\x20a\x20hostname\x20this\n\x20should\x20be\x20se\
    t\x20for\x20resolution\x20other\x20than\x20DNS.\x20If\x20the\x20address\
    \x20is\x20a\x20concrete\n\x20IP\x20address,\x20no\x20resolution\x20will\
    \x20occur.\n\n\r\n\x05\x04\x01\x02\x04\x04\x12\x04;\x026\x03\n\x0c\n\x05\
    \x04\x01\x02\x04\x05\x12\x03;\x02\x08\n\x0c\n\x05\x04\x01\x02\x04\x01\
    \x12\x03;\t\x16\n\x0c\n\x05\x04\x01\x02\x04\x03\x12\x03;\x19\x1a\n\x96\
    \x02\n\x04\x04\x01\x02\x05\x12\x03A\x02\x17\x1a\x88\x02\x20When\x20bindi\
    ng\x20to\x20an\x20IPv6\x20address\x20above,\x20this\x20enables\x20`IPv4\
    \x20compatibility\n\x20<https://tools.ietf.org/html/rfc3493#page-11>`_.\
    \x20Binding\x20to\x20``::``\x20will\n\x20allow\x20both\x20IPv4\x20and\
    \x20IPv6\x20connections,\x20with\x20peer\x20IPv4\x20addresses\x20mapped\
    \x20into\n\x20IPv6\x20space\x20as\x20``::FFFF:<IPv4-address>``.\n\n\r\n\
    \x05\x04\x01\x02\x05\x04\x12\x04A\x02;\x1b\n\x0c\n\x05\x04\x01\x02\x05\
    \x05\x12\x03A\x02\x06\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\x03A\x07\x12\n\
    \x0c\n\x05\x04\x01\x02\x05\x03\x12\x03A\x15\x16\n\n\n\x02\x04\x02\x12\
    \x04D\0P\x01\n\n\n\x03\x04\x02\x01\x12\x03D\x08\x14\n\xcc\x01\n\x04\x04\
    \x02\x02\0\x12\x03H\x023\x1a\xbe\x01\x20Maximum\x20number\x20of\x20keepa\
    live\x20probes\x20to\x20send\x20without\x20response\x20before\x20decidin\
    g\n\x20the\x20connection\x20is\x20dead.\x20Default\x20is\x20to\x20use\
    \x20the\x20OS\x20level\x20configuration\x20(unless\n\x20overridden,\x20L\
    inux\x20defaults\x20to\x209.)\n\n\r\n\x05\x04\x02\x02\0\x04\x12\x04H\x02\
    D\x16\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03H\x02\x1d\n\x0c\n\x05\x04\x02\
    \x02\0\x01\x12\x03H\x1e.\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03H12\n\xd7\
    \x01\n\x04\x04\x02\x02\x01\x12\x03L\x021\x1a\xc9\x01\x20The\x20number\
    \x20of\x20seconds\x20a\x20connection\x20needs\x20to\x20be\x20idle\x20bef\
    ore\x20keep-alive\x20probes\n\x20start\x20being\x20sent.\x20Default\x20i\
    s\x20to\x20use\x20the\x20OS\x20level\x20configuration\x20(unless\n\x20ov\
    erridden,\x20Linux\x20defaults\x20to\x207200s\x20(ie\x202\x20hours.)\n\n\
    \r\n\x05\x04\x02\x02\x01\x04\x12\x04L\x02H3\n\x0c\n\x05\x04\x02\x02\x01\
    \x06\x12\x03L\x02\x1d\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03L\x1e,\n\
    \x0c\n\x05\x04\x02\x02\x01\x03\x12\x03L/0\n\x9a\x01\n\x04\x04\x02\x02\
    \x02\x12\x03O\x025\x1a\x8c\x01\x20The\x20number\x20of\x20seconds\x20betw\
    een\x20keep-alive\x20probes.\x20Default\x20is\x20to\x20use\x20the\x20OS\
    \n\x20level\x20configuration\x20(unless\x20overridden,\x20Linux\x20defau\
    lts\x20to\x2075s.)\n\n\r\n\x05\x04\x02\x02\x02\x04\x12\x04O\x02L1\n\x0c\
    \n\x05\x04\x02\x02\x02\x06\x12\x03O\x02\x1d\n\x0c\n\x05\x04\x02\x02\x02\
    \x01\x12\x03O\x1e0\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03O34\n\n\n\x02\
    \x04\x03\x12\x04R\0c\x01\n\n\n\x03\x04\x03\x01\x12\x03R\x08\x12\n>\n\x04\
    \x04\x03\x02\0\x12\x04T\x02UO\x1a0\x20The\x20address\x20to\x20bind\x20to\
    \x20when\x20creating\x20a\x20socket.\n\n\r\n\x05\x04\x03\x02\0\x04\x12\
    \x04T\x02R\x14\n\x0c\n\x05\x04\x03\x02\0\x06\x12\x03T\x02\x0f\n\x0c\n\
    \x05\x04\x03\x02\0\x01\x12\x03T\x10\x1e\n\x0c\n\x05\x04\x03\x02\0\x03\
    \x12\x03T!\"\n\x0c\n\x05\x04\x03\x02\0\x08\x12\x03U\x06N\n\x11\n\n\x04\
    \x03\x02\0\x08\x97\x8d8\x11\x02\x12\x03U\x07/\n\x0f\n\x08\x04\x03\x02\0\
    \x08\xe9\xfb\x03\x12\x03U1M\n\xd9\x03\n\x04\x04\x03\x02\x01\x12\x03^\x02\
    )\x1a\xcb\x03\x20Whether\x20to\x20set\x20the\x20*IP_FREEBIND*\x20option\
    \x20when\x20creating\x20the\x20socket.\x20When\x20this\n\x20flag\x20is\
    \x20set\x20to\x20true,\x20allows\x20the\x20:ref:`source_address\n\x20<en\
    voy_api_field_UpstreamBindConfig.source_address>`\x20to\x20be\x20an\x20I\
    P\x20address\n\x20that\x20is\x20not\x20configured\x20on\x20the\x20system\
    \x20running\x20Envoy.\x20When\x20this\x20flag\x20is\x20set\n\x20to\x20fa\
    lse,\x20the\x20option\x20*IP_FREEBIND*\x20is\x20disabled\x20on\x20the\
    \x20socket.\x20When\x20this\n\x20flag\x20is\x20not\x20set\x20(default),\
    \x20the\x20socket\x20is\x20not\x20modified,\x20i.e.\x20the\x20option\x20\
    is\n\x20neither\x20enabled\x20nor\x20disabled.\n\n\r\n\x05\x04\x03\x02\
    \x01\x04\x12\x04^\x02UO\n\x0c\n\x05\x04\x03\x02\x01\x06\x12\x03^\x02\x1b\
    \n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03^\x1c$\n\x0c\n\x05\x04\x03\x02\
    \x01\x03\x12\x03^'(\no\n\x04\x04\x03\x02\x02\x12\x03b\x02+\x1ab\x20Addit\
    ional\x20socket\x20options\x20that\x20may\x20not\x20be\x20present\x20in\
    \x20Envoy\x20source\x20code\x20or\n\x20precompiled\x20binaries.\n\n\x0c\
    \n\x05\x04\x03\x02\x02\x04\x12\x03b\x02\n\n\x0c\n\x05\x04\x03\x02\x02\
    \x06\x12\x03b\x0b\x17\n\x0c\n\x05\x04\x03\x02\x02\x01\x12\x03b\x18&\n\
    \x0c\n\x05\x04\x03\x02\x02\x03\x12\x03b)*\n\xb5\x01\n\x02\x04\x04\x12\
    \x04h\0o\x01\x1a\xa8\x01\x20Addresses\x20specify\x20either\x20a\x20logic\
    al\x20or\x20physical\x20address\x20and\x20port,\x20which\x20are\n\x20use\
    d\x20to\x20tell\x20Envoy\x20where\x20to\x20bind/listen,\x20connect\x20to\
    \x20upstream\x20and\x20find\n\x20management\x20servers.\n\n\n\n\x03\x04\
    \x04\x01\x12\x03h\x08\x0f\n\x0c\n\x04\x04\x04\x08\0\x12\x04i\x02n\x03\n\
    \x0c\n\x05\x04\x04\x08\0\x01\x12\x03i\x08\x0f\n\x0c\n\x05\x04\x04\x08\0\
    \x02\x12\x03j\x04&\n\x0f\n\x08\x04\x04\x08\0\x02\x97\x8d8\x12\x03j\x04&\
    \n\x0b\n\x04\x04\x04\x02\0\x12\x03l\x04%\n\x0c\n\x05\x04\x04\x02\0\x06\
    \x12\x03l\x04\x11\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03l\x12\x20\n\x0c\n\
    \x05\x04\x04\x02\0\x03\x12\x03l#$\n\x0b\n\x04\x04\x04\x02\x01\x12\x03m\
    \x04\x12\n\x0c\n\x05\x04\x04\x02\x01\x06\x12\x03m\x04\x08\n\x0c\n\x05\
    \x04\x04\x02\x01\x01\x12\x03m\t\r\n\x0c\n\x05\x04\x04\x02\x01\x03\x12\
    \x03m\x10\x11\n\x9d\x01\n\x02\x04\x05\x12\x04s\0x\x01\x1a\x90\x01\x20Cid\
    rRange\x20specifies\x20an\x20IP\x20Address\x20and\x20a\x20prefix\x20leng\
    th\x20to\x20construct\n\x20the\x20subnet\x20mask\x20for\x20a\x20`CIDR\
    \x20<https://tools.ietf.org/html/rfc4632>`_\x20range.\n\n\n\n\x03\x04\
    \x05\x01\x12\x03s\x08\x11\nJ\n\x04\x04\x05\x02\0\x12\x03u\x02D\x1a=\x20I\
    Pv4\x20or\x20IPv6\x20address,\x20e.g.\x20``192.0.0.0``\x20or\x20``2001:d\
    b8::``.\n\n\r\n\x05\x04\x05\x02\0\x04\x12\x04u\x02s\x13\n\x0c\n\x05\x04\
    \x05\x02\0\x05\x12\x03u\x02\x08\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x03u\t\
    \x17\n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03u\x1a\x1b\n\x0c\n\x05\x04\x05\
    \x02\0\x08\x12\x03u\x1cC\n\x11\n\n\x04\x05\x02\0\x08\x97\x8d8\x0e\x04\
    \x12\x03u\x1dB\n,\n\x04\x04\x05\x02\x01\x12\x03w\x02Q\x1a\x1f\x20Length\
    \x20of\x20prefix,\x20e.g.\x200,\x2032.\n\n\r\n\x05\x04\x05\x02\x01\x04\
    \x12\x04w\x02uD\n\x0c\n\x05\x04\x05\x02\x01\x06\x12\x03w\x02\x1d\n\x0c\n\
    \x05\x04\x05\x02\x01\x01\x12\x03w\x1e(\n\x0c\n\x05\x04\x05\x02\x01\x03\
    \x12\x03w+,\n\x0c\n\x05\x04\x05\x02\x01\x08\x12\x03w-P\n\x11\n\n\x04\x05\
    \x02\x01\x08\x97\x8d8\x05\x03\x12\x03w.Ob\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
