// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct AdsDummy {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl AdsDummy {
    pub fn new() -> AdsDummy {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for AdsDummy {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AdsDummy {
        AdsDummy::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let fields = ::std::vec::Vec::new();
                ::protobuf::reflect::MessageDescriptor::new::<AdsDummy>(
                    "AdsDummy",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AdsDummy {
        static mut instance: ::protobuf::lazy::Lazy<AdsDummy> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const AdsDummy,
        };
        unsafe {
            instance.get(AdsDummy::new)
        }
    }
}

impl ::protobuf::Clear for AdsDummy {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AdsDummy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AdsDummy {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$envoy/service/discovery/v2/ads.proto\x12\x1aenvoy.service.discovery.v\
    2\x1a\x1cenvoy/api/v2/discovery.proto\"\n\n\x08AdsDummy2\xff\x01\n\x1aAg\
    gregatedDiscoveryService\x12b\n\x19StreamAggregatedResources\x12\x1e.env\
    oy.api.v2.DiscoveryRequest\x1a\x1f.envoy.api.v2.DiscoveryResponse\"\0(\
    \x010\x01\x12}\n\x1eIncrementalAggregatedResources\x12).envoy.api.v2.Inc\
    rementalDiscoveryRequest\x1a*.envoy.api.v2.IncrementalDiscoveryResponse\
    \"\0(\x010\x01B=\n(io.envoyproxy.envoy.service.discovery.v2B\x08AdsProto\
    P\x01Z\x02v2\x88\x01\x01J\x8f\n\n\x06\x12\x04\0\0%\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\x08\"\n\x08\n\x01\x08\x12\
    \x03\x04\0)\n\t\n\x02\x08\x08\x12\x03\x04\0)\n\x08\n\x01\x08\x12\x03\x05\
    \0\"\n\t\n\x02\x08\n\x12\x03\x05\0\"\n\x08\n\x01\x08\x12\x03\x06\0A\n\t\
    \n\x02\x08\x01\x12\x03\x06\0A\n\x08\n\x01\x08\x12\x03\x07\0\x19\n\t\n\
    \x02\x08\x0b\x12\x03\x07\0\x19\n\x08\n\x01\x08\x12\x03\x08\0$\n\t\n\x02\
    \x08\x11\x12\x03\x08\0$\n\t\n\x02\x03\0\x12\x03\n\x07%\n\xa1\x01\n\x02\
    \x04\0\x12\x04\x0e\0\x0f\x01\x1a\x94\x01\x20[#not-implemented-hide:]\x20\
    Not\x20configuration.\x20Workaround\x20c++\x20protobuf\x20issue\x20with\
    \x20importing\n\x20services:\x20https://github.com/google/protobuf/issue\
    s/4221\n\n\n\n\x03\x04\0\x01\x12\x03\x0e\x08\x10\n\xfc\x05\n\x02\x06\0\
    \x12\x04\x1c\0%\x01\x1a\xc2\x03\x20See\x20https://github.com/lyft/envoy-\
    api#apis\x20for\x20a\x20description\x20of\x20the\x20role\x20of\n\x20ADS\
    \x20and\x20how\x20it\x20is\x20intended\x20to\x20be\x20used\x20by\x20a\
    \x20management\x20server.\x20ADS\x20requests\n\x20have\x20the\x20same\
    \x20structure\x20as\x20their\x20singleton\x20xDS\x20counterparts,\x20but\
    \x20can\n\x20multiplex\x20many\x20resource\x20types\x20on\x20a\x20single\
    \x20stream.\x20The\x20type_url\x20in\x20the\n\x20DiscoveryRequest/Discov\
    eryResponse\x20provides\x20sufficient\x20information\x20to\x20recover\n\
    \x20the\x20multiplexed\x20singleton\x20APIs\x20at\x20the\x20Envoy\x20ins\
    tance\x20and\x20management\x20server.\n2\xaa\x02\x20[#not-implemented-hi\
    de:]\x20Discovery\x20services\x20for\x20endpoints,\x20clusters,\x20route\
    s,\n\x20and\x20listeners\x20are\x20retained\x20in\x20the\x20package\x20`\
    envoy.api.v2`\x20for\x20backwards\n\x20compatibility\x20with\x20existing\
    \x20management\x20servers.\x20New\x20development\x20in\x20discovery\n\
    \x20services\x20should\x20proceed\x20in\x20the\x20package\x20`envoy.serv\
    ice.discovery.v2`.\n\n\n\n\x03\x06\0\x01\x12\x03\x1c\x08\"\n(\n\x04\x06\
    \0\x02\0\x12\x04\x1e\x02\x20\x03\x1a\x1a\x20This\x20is\x20a\x20gRPC-only\
    \x20API.\n\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x1e\x06\x1f\n\x0c\n\x05\
    \x06\0\x02\0\x05\x12\x03\x1e\x20&\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\
    \x1e'D\n\x0c\n\x05\x06\0\x02\0\x06\x12\x03\x1f\x0f\x15\n\x0c\n\x05\x06\0\
    \x02\0\x03\x12\x03\x1f\x164\n\x0c\n\x04\x06\0\x02\x01\x12\x04\"\x02$\x03\
    \n\x0c\n\x05\x06\0\x02\x01\x01\x12\x03\"\x06$\n\x0c\n\x05\x06\0\x02\x01\
    \x05\x12\x03\"%+\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x03\",T\n\x0c\n\x05\
    \x06\0\x02\x01\x06\x12\x03#\x0f\x15\n\x0c\n\x05\x06\0\x02\x01\x03\x12\
    \x03#\x16?b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
