// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct ClusterLoadAssignment {
    // message fields
    pub cluster_name: ::std::string::String,
    pub endpoints: ::protobuf::RepeatedField<super::endpoint::LocalityLbEndpoints>,
    pub named_endpoints: ::std::collections::HashMap<::std::string::String, super::endpoint::Endpoint>,
    pub policy: ::protobuf::SingularPtrField<ClusterLoadAssignment_Policy>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl ClusterLoadAssignment {
    pub fn new() -> ClusterLoadAssignment {
        ::std::default::Default::default()
    }

    // string cluster_name = 1;

    pub fn clear_cluster_name(&mut self) {
        self.cluster_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_cluster_name(&mut self, v: ::std::string::String) {
        self.cluster_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_cluster_name(&mut self) -> &mut ::std::string::String {
        &mut self.cluster_name
    }

    // Take field
    pub fn take_cluster_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.cluster_name, ::std::string::String::new())
    }

    pub fn get_cluster_name(&self) -> &str {
        &self.cluster_name
    }

    // repeated .envoy.api.v2.endpoint.LocalityLbEndpoints endpoints = 2;

    pub fn clear_endpoints(&mut self) {
        self.endpoints.clear();
    }

    // Param is passed by value, moved
    pub fn set_endpoints(&mut self, v: ::protobuf::RepeatedField<super::endpoint::LocalityLbEndpoints>) {
        self.endpoints = v;
    }

    // Mutable pointer to the field.
    pub fn mut_endpoints(&mut self) -> &mut ::protobuf::RepeatedField<super::endpoint::LocalityLbEndpoints> {
        &mut self.endpoints
    }

    // Take field
    pub fn take_endpoints(&mut self) -> ::protobuf::RepeatedField<super::endpoint::LocalityLbEndpoints> {
        ::std::mem::replace(&mut self.endpoints, ::protobuf::RepeatedField::new())
    }

    pub fn get_endpoints(&self) -> &[super::endpoint::LocalityLbEndpoints] {
        &self.endpoints
    }

    // repeated .envoy.api.v2.ClusterLoadAssignment.NamedEndpointsEntry named_endpoints = 5;

    pub fn clear_named_endpoints(&mut self) {
        self.named_endpoints.clear();
    }

    // Param is passed by value, moved
    pub fn set_named_endpoints(&mut self, v: ::std::collections::HashMap<::std::string::String, super::endpoint::Endpoint>) {
        self.named_endpoints = v;
    }

    // Mutable pointer to the field.
    pub fn mut_named_endpoints(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, super::endpoint::Endpoint> {
        &mut self.named_endpoints
    }

    // Take field
    pub fn take_named_endpoints(&mut self) -> ::std::collections::HashMap<::std::string::String, super::endpoint::Endpoint> {
        ::std::mem::replace(&mut self.named_endpoints, ::std::collections::HashMap::new())
    }

    pub fn get_named_endpoints(&self) -> &::std::collections::HashMap<::std::string::String, super::endpoint::Endpoint> {
        &self.named_endpoints
    }

    // .envoy.api.v2.ClusterLoadAssignment.Policy policy = 4;

    pub fn clear_policy(&mut self) {
        self.policy.clear();
    }

    pub fn has_policy(&self) -> bool {
        self.policy.is_some()
    }

    // Param is passed by value, moved
    pub fn set_policy(&mut self, v: ClusterLoadAssignment_Policy) {
        self.policy = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_policy(&mut self) -> &mut ClusterLoadAssignment_Policy {
        if self.policy.is_none() {
            self.policy.set_default();
        }
        self.policy.as_mut().unwrap()
    }

    // Take field
    pub fn take_policy(&mut self) -> ClusterLoadAssignment_Policy {
        self.policy.take().unwrap_or_else(|| ClusterLoadAssignment_Policy::new())
    }

    pub fn get_policy(&self) -> &ClusterLoadAssignment_Policy {
        self.policy.as_ref().unwrap_or_else(|| ClusterLoadAssignment_Policy::default_instance())
    }
}

impl ::protobuf::Message for ClusterLoadAssignment {
    fn is_initialized(&self) -> bool {
        for v in &self.endpoints {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.policy {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.cluster_name)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.endpoints)?;
                },
                5 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<super::endpoint::Endpoint>>(wire_type, is, &mut self.named_endpoints)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.policy)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.cluster_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.cluster_name);
        }
        for value in &self.endpoints {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<super::endpoint::Endpoint>>(5, &self.named_endpoints);
        if let Some(ref v) = self.policy.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.cluster_name.is_empty() {
            os.write_string(1, &self.cluster_name)?;
        }
        for v in &self.endpoints {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<super::endpoint::Endpoint>>(5, &self.named_endpoints, os)?;
        if let Some(ref v) = self.policy.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClusterLoadAssignment {
        ClusterLoadAssignment::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "cluster_name",
                    |m: &ClusterLoadAssignment| { &m.cluster_name },
                    |m: &mut ClusterLoadAssignment| { &mut m.cluster_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::endpoint::LocalityLbEndpoints>>(
                    "endpoints",
                    |m: &ClusterLoadAssignment| { &m.endpoints },
                    |m: &mut ClusterLoadAssignment| { &mut m.endpoints },
                ));
                fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<super::endpoint::Endpoint>>(
                    "named_endpoints",
                    |m: &ClusterLoadAssignment| { &m.named_endpoints },
                    |m: &mut ClusterLoadAssignment| { &mut m.named_endpoints },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ClusterLoadAssignment_Policy>>(
                    "policy",
                    |m: &ClusterLoadAssignment| { &m.policy },
                    |m: &mut ClusterLoadAssignment| { &mut m.policy },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClusterLoadAssignment>(
                    "ClusterLoadAssignment",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClusterLoadAssignment {
        static mut instance: ::protobuf::lazy::Lazy<ClusterLoadAssignment> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClusterLoadAssignment,
        };
        unsafe {
            instance.get(ClusterLoadAssignment::new)
        }
    }
}

impl ::protobuf::Clear for ClusterLoadAssignment {
    fn clear(&mut self) {
        self.clear_cluster_name();
        self.clear_endpoints();
        self.clear_named_endpoints();
        self.clear_policy();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClusterLoadAssignment {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClusterLoadAssignment {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ClusterLoadAssignment_Policy {
    // message fields
    pub drop_overloads: ::protobuf::RepeatedField<ClusterLoadAssignment_Policy_DropOverload>,
    pub overprovisioning_factor: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl ClusterLoadAssignment_Policy {
    pub fn new() -> ClusterLoadAssignment_Policy {
        ::std::default::Default::default()
    }

    // repeated .envoy.api.v2.ClusterLoadAssignment.Policy.DropOverload drop_overloads = 2;

    pub fn clear_drop_overloads(&mut self) {
        self.drop_overloads.clear();
    }

    // Param is passed by value, moved
    pub fn set_drop_overloads(&mut self, v: ::protobuf::RepeatedField<ClusterLoadAssignment_Policy_DropOverload>) {
        self.drop_overloads = v;
    }

    // Mutable pointer to the field.
    pub fn mut_drop_overloads(&mut self) -> &mut ::protobuf::RepeatedField<ClusterLoadAssignment_Policy_DropOverload> {
        &mut self.drop_overloads
    }

    // Take field
    pub fn take_drop_overloads(&mut self) -> ::protobuf::RepeatedField<ClusterLoadAssignment_Policy_DropOverload> {
        ::std::mem::replace(&mut self.drop_overloads, ::protobuf::RepeatedField::new())
    }

    pub fn get_drop_overloads(&self) -> &[ClusterLoadAssignment_Policy_DropOverload] {
        &self.drop_overloads
    }

    // .google.protobuf.UInt32Value overprovisioning_factor = 3;

    pub fn clear_overprovisioning_factor(&mut self) {
        self.overprovisioning_factor.clear();
    }

    pub fn has_overprovisioning_factor(&self) -> bool {
        self.overprovisioning_factor.is_some()
    }

    // Param is passed by value, moved
    pub fn set_overprovisioning_factor(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.overprovisioning_factor = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_overprovisioning_factor(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.overprovisioning_factor.is_none() {
            self.overprovisioning_factor.set_default();
        }
        self.overprovisioning_factor.as_mut().unwrap()
    }

    // Take field
    pub fn take_overprovisioning_factor(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.overprovisioning_factor.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_overprovisioning_factor(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.overprovisioning_factor.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }
}

impl ::protobuf::Message for ClusterLoadAssignment_Policy {
    fn is_initialized(&self) -> bool {
        for v in &self.drop_overloads {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.overprovisioning_factor {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.drop_overloads)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.overprovisioning_factor)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.drop_overloads {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if let Some(ref v) = self.overprovisioning_factor.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        for v in &self.drop_overloads {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if let Some(ref v) = self.overprovisioning_factor.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClusterLoadAssignment_Policy {
        ClusterLoadAssignment_Policy::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ClusterLoadAssignment_Policy_DropOverload>>(
                    "drop_overloads",
                    |m: &ClusterLoadAssignment_Policy| { &m.drop_overloads },
                    |m: &mut ClusterLoadAssignment_Policy| { &mut m.drop_overloads },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "overprovisioning_factor",
                    |m: &ClusterLoadAssignment_Policy| { &m.overprovisioning_factor },
                    |m: &mut ClusterLoadAssignment_Policy| { &mut m.overprovisioning_factor },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClusterLoadAssignment_Policy>(
                    "ClusterLoadAssignment_Policy",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClusterLoadAssignment_Policy {
        static mut instance: ::protobuf::lazy::Lazy<ClusterLoadAssignment_Policy> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClusterLoadAssignment_Policy,
        };
        unsafe {
            instance.get(ClusterLoadAssignment_Policy::new)
        }
    }
}

impl ::protobuf::Clear for ClusterLoadAssignment_Policy {
    fn clear(&mut self) {
        self.clear_drop_overloads();
        self.clear_overprovisioning_factor();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClusterLoadAssignment_Policy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClusterLoadAssignment_Policy {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ClusterLoadAssignment_Policy_DropOverload {
    // message fields
    pub category: ::std::string::String,
    pub drop_percentage: ::protobuf::SingularPtrField<super::percent::FractionalPercent>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl ClusterLoadAssignment_Policy_DropOverload {
    pub fn new() -> ClusterLoadAssignment_Policy_DropOverload {
        ::std::default::Default::default()
    }

    // string category = 1;

    pub fn clear_category(&mut self) {
        self.category.clear();
    }

    // Param is passed by value, moved
    pub fn set_category(&mut self, v: ::std::string::String) {
        self.category = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_category(&mut self) -> &mut ::std::string::String {
        &mut self.category
    }

    // Take field
    pub fn take_category(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.category, ::std::string::String::new())
    }

    pub fn get_category(&self) -> &str {
        &self.category
    }

    // .envoy.type.FractionalPercent drop_percentage = 2;

    pub fn clear_drop_percentage(&mut self) {
        self.drop_percentage.clear();
    }

    pub fn has_drop_percentage(&self) -> bool {
        self.drop_percentage.is_some()
    }

    // Param is passed by value, moved
    pub fn set_drop_percentage(&mut self, v: super::percent::FractionalPercent) {
        self.drop_percentage = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_drop_percentage(&mut self) -> &mut super::percent::FractionalPercent {
        if self.drop_percentage.is_none() {
            self.drop_percentage.set_default();
        }
        self.drop_percentage.as_mut().unwrap()
    }

    // Take field
    pub fn take_drop_percentage(&mut self) -> super::percent::FractionalPercent {
        self.drop_percentage.take().unwrap_or_else(|| super::percent::FractionalPercent::new())
    }

    pub fn get_drop_percentage(&self) -> &super::percent::FractionalPercent {
        self.drop_percentage.as_ref().unwrap_or_else(|| super::percent::FractionalPercent::default_instance())
    }
}

impl ::protobuf::Message for ClusterLoadAssignment_Policy_DropOverload {
    fn is_initialized(&self) -> bool {
        for v in &self.drop_percentage {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.category)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.drop_percentage)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.category.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.category);
        }
        if let Some(ref v) = self.drop_percentage.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.category.is_empty() {
            os.write_string(1, &self.category)?;
        }
        if let Some(ref v) = self.drop_percentage.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClusterLoadAssignment_Policy_DropOverload {
        ClusterLoadAssignment_Policy_DropOverload::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "category",
                    |m: &ClusterLoadAssignment_Policy_DropOverload| { &m.category },
                    |m: &mut ClusterLoadAssignment_Policy_DropOverload| { &mut m.category },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::percent::FractionalPercent>>(
                    "drop_percentage",
                    |m: &ClusterLoadAssignment_Policy_DropOverload| { &m.drop_percentage },
                    |m: &mut ClusterLoadAssignment_Policy_DropOverload| { &mut m.drop_percentage },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClusterLoadAssignment_Policy_DropOverload>(
                    "ClusterLoadAssignment_Policy_DropOverload",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClusterLoadAssignment_Policy_DropOverload {
        static mut instance: ::protobuf::lazy::Lazy<ClusterLoadAssignment_Policy_DropOverload> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClusterLoadAssignment_Policy_DropOverload,
        };
        unsafe {
            instance.get(ClusterLoadAssignment_Policy_DropOverload::new)
        }
    }
}

impl ::protobuf::Clear for ClusterLoadAssignment_Policy_DropOverload {
    fn clear(&mut self) {
        self.clear_category();
        self.clear_drop_percentage();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClusterLoadAssignment_Policy_DropOverload {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClusterLoadAssignment_Policy_DropOverload {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x16envoy/api/v2/eds.proto\x12\x0cenvoy.api.v2\x1a\x1cenvoy/api/v2/dis\
    covery.proto\x1a$envoy/api/v2/endpoint/endpoint.proto\x1a\x18envoy/type/\
    percent.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/valida\
    te.proto\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/wrappers.pro\
    to\"\xf1\x05\n\x15ClusterLoadAssignment\x12,\n\x0ccluster_name\x18\x01\
    \x20\x01(\tR\x0bclusterNameB\t\xba\xe9\xc0\x03\x04r\x02\x20\x01\x12N\n\t\
    endpoints\x18\x02\x20\x03(\x0b2*.envoy.api.v2.endpoint.LocalityLbEndpoin\
    tsR\tendpointsB\x04\xc8\xde\x1f\0\x12`\n\x0fnamed_endpoints\x18\x05\x20\
    \x03(\x0b27.envoy.api.v2.ClusterLoadAssignment.NamedEndpointsEntryR\x0en\
    amedEndpoints\x12B\n\x06policy\x18\x04\x20\x01(\x0b2*.envoy.api.v2.Clust\
    erLoadAssignment.PolicyR\x06policy\x1ab\n\x13NamedEndpointsEntry\x12\x10\
    \n\x03key\x18\x01\x20\x01(\tR\x03key\x125\n\x05value\x18\x02\x20\x01(\
    \x0b2\x1f.envoy.api.v2.endpoint.EndpointR\x05value:\x028\x01\x1a\xcf\x02\
    \n\x06Policy\x12^\n\x0edrop_overloads\x18\x02\x20\x03(\x0b27.envoy.api.v\
    2.ClusterLoadAssignment.Policy.DropOverloadR\rdropOverloads\x12`\n\x17ov\
    erprovisioning_factor\x18\x03\x20\x01(\x0b2\x1c.google.protobuf.UInt32Va\
    lueR\x16overprovisioningFactorB\t\xba\xe9\xc0\x03\x04*\x02\x20\0\x1a}\n\
    \x0cDropOverload\x12%\n\x08category\x18\x01\x20\x01(\tR\x08categoryB\t\
    \xba\xe9\xc0\x03\x04r\x02\x20\x01\x12F\n\x0fdrop_percentage\x18\x02\x20\
    \x01(\x0b2\x1d.envoy.type.FractionalPercentR\x0edropPercentageJ\x04\x08\
    \x01\x10\x022\xeb\x01\n\x18EndpointDiscoveryService\x12X\n\x0fStreamEndp\
    oints\x12\x1e.envoy.api.v2.DiscoveryRequest\x1a\x1f.envoy.api.v2.Discove\
    ryResponse\"\0(\x010\x01\x12u\n\x0eFetchEndpoints\x12\x1e.envoy.api.v2.D\
    iscoveryRequest\x1a\x1f.envoy.api.v2.DiscoveryResponse\"\"\x82\xd3\xe4\
    \x93\x02\x1c\"\x17/v2/discovery:endpoints:\x01*B/\n\x1aio.envoyproxy.env\
    oy.api.v2B\x08EdsProtoP\x01\x88\x01\x01\xa8\xe2\x1e\x01J\xad\x1f\n\x06\
    \x12\x04\0\0o\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\
    \x03\x02\x08\x14\n\x08\n\x01\x08\x12\x03\x04\0)\n\t\n\x02\x08\x08\x12\
    \x03\x04\0)\n\x08\n\x01\x08\x12\x03\x05\0\"\n\t\n\x02\x08\n\x12\x03\x05\
    \0\"\n\x08\n\x01\x08\x12\x03\x06\03\n\t\n\x02\x08\x01\x12\x03\x06\03\n\
    \x08\n\x01\x08\x12\x03\x08\0$\n\t\n\x02\x08\x11\x12\x03\x08\0$\n\t\n\x02\
    \x03\0\x12\x03\n\x07%\n\t\n\x02\x03\x01\x12\x03\x0b\x07-\n\t\n\x02\x03\
    \x02\x12\x03\x0c\x07!\n\t\n\x02\x03\x03\x12\x03\x0e\x07%\n\t\n\x02\x03\
    \x04\x12\x03\x10\x07\x20\n\t\n\x02\x03\x05\x12\x03\x11\x07\x1d\n\t\n\x02\
    \x03\x06\x12\x03\x12\x07'\n\x08\n\x01\x08\x12\x03\x14\0$\n\x0b\n\x04\x08\
    \xa5\xec\x03\x12\x03\x14\0$\n\x81\x01\n\x02\x06\0\x12\x04\x19\0%\x012u\
    \x20[#protodoc-title:\x20EDS]\n\x20Endpoint\x20discovery\x20:ref:`archit\
    ecture\x20overview\x20<arch_overview_service_discovery_types_eds>`\n\n\n\
    \n\x03\x06\0\x01\x12\x03\x19\x08\x20\nw\n\x04\x06\0\x02\0\x12\x04\x1c\
    \x02\x1d\x03\x1ai\x20The\x20resource_names\x20field\x20in\x20DiscoveryRe\
    quest\x20specifies\x20a\x20list\x20of\x20clusters\n\x20to\x20subscribe\
    \x20to\x20updates\x20for.\n\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x1c\x06\
    \x15\n\x0c\n\x05\x06\0\x02\0\x05\x12\x03\x1c\x16\x1c\n\x0c\n\x05\x06\0\
    \x02\0\x02\x12\x03\x1c\x1d-\n\x0c\n\x05\x06\0\x02\0\x06\x12\x03\x1c8>\n\
    \x0c\n\x05\x06\0\x02\0\x03\x12\x03\x1c?P\n\x0c\n\x04\x06\0\x02\x01\x12\
    \x04\x1f\x02$\x03\n\x0c\n\x05\x06\0\x02\x01\x01\x12\x03\x1f\x06\x14\n\
    \x0c\n\x05\x06\0\x02\x01\x02\x12\x03\x1f\x15%\n\x0c\n\x05\x06\0\x02\x01\
    \x03\x12\x03\x1f0A\n\r\n\x05\x06\0\x02\x01\x04\x12\x04\x20\x04#\x06\n\
    \x11\n\t\x06\0\x02\x01\x04\xb0\xca\xbc\"\x12\x04\x20\x04#\x06\n\xe9\x03\
    \n\x02\x04\0\x12\x04/\0o\x01\x1a\xdc\x03\x20Each\x20route\x20from\x20RDS\
    \x20will\x20map\x20to\x20a\x20single\x20cluster\x20or\x20traffic\x20spli\
    t\x20across\n\x20clusters\x20using\x20weights\x20expressed\x20in\x20the\
    \x20RDS\x20WeightedCluster.\n\n\x20With\x20EDS,\x20each\x20cluster\x20is\
    \x20treated\x20independently\x20from\x20a\x20LB\x20perspective,\x20with\
    \n\x20LB\x20taking\x20place\x20between\x20the\x20Localities\x20within\
    \x20a\x20cluster\x20and\x20at\x20a\x20finer\n\x20granularity\x20between\
    \x20the\x20hosts\x20within\x20a\x20locality.\x20For\x20a\x20given\x20clu\
    ster,\x20the\n\x20effective\x20weight\x20of\x20a\x20host\x20is\x20its\
    \x20load_balancing_weight\x20multiplied\x20by\x20the\n\x20load_balancing\
    _weight\x20of\x20its\x20Locality.\n\n\n\n\x03\x04\0\x01\x12\x03/\x08\x1d\
    \n\xe8\x01\n\x04\x04\0\x02\0\x12\x034\x02B\x1a\xda\x01\x20Name\x20of\x20\
    the\x20cluster.\x20This\x20will\x20be\x20the\x20:ref:`service_name\n\x20\
    <envoy_api_field_Cluster.EdsClusterConfig.service_name>`\x20value\x20if\
    \x20specified\n\x20in\x20the\x20cluster\x20:ref:`EdsClusterConfig\n\x20<\
    envoy_api_msg_Cluster.EdsClusterConfig>`.\n\n\r\n\x05\x04\0\x02\0\x04\
    \x12\x044\x02/\x1f\n\x0c\n\x05\x04\0\x02\0\x05\x12\x034\x02\x08\n\x0c\n\
    \x05\x04\0\x02\0\x01\x12\x034\t\x15\n\x0c\n\x05\x04\0\x02\0\x03\x12\x034\
    \x18\x19\n\x0c\n\x05\x04\0\x02\0\x08\x12\x034\x1aA\n\x11\n\n\x04\0\x02\0\
    \x08\x97\x8d8\x0e\x04\x12\x034\x1b@\n4\n\x04\x04\0\x02\x01\x12\x037\x02U\
    \x1a'\x20List\x20of\x20endpoints\x20to\x20load\x20balance\x20to.\n\n\x0c\
    \n\x05\x04\0\x02\x01\x04\x12\x037\x02\n\n\x0c\n\x05\x04\0\x02\x01\x06\
    \x12\x037\x0b'\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x037(1\n\x0c\n\x05\x04\
    \0\x02\x01\x03\x12\x03745\n\x0c\n\x05\x04\0\x02\x01\x08\x12\x0376T\n\x0f\
    \n\x08\x04\0\x02\x01\x08\xe9\xfb\x03\x12\x0377S\nT\n\x04\x04\0\x02\x02\
    \x12\x03:\x025\x1aG\x20Map\x20of\x20named\x20endpoints\x20that\x20can\
    \x20be\x20referenced\x20in\x20LocalityLbEndpoints.\n\n\r\n\x05\x04\0\x02\
    \x02\x04\x12\x04:\x027U\n\x0c\n\x05\x04\0\x02\x02\x06\x12\x03:\x02\x20\n\
    \x0c\n\x05\x04\0\x02\x02\x01\x12\x03:!0\n\x0c\n\x05\x04\0\x02\x02\x03\
    \x12\x03:34\n/\n\x04\x04\0\x03\x01\x12\x04=\x02k\x03\x1a!\x20Load\x20bal\
    ancing\x20policy\x20settings.\n\n\x0c\n\x05\x04\0\x03\x01\x01\x12\x03=\n\
    \x10\n\x0c\n\x05\x04\0\x03\x01\t\x12\x03>\r\x0f\n\r\n\x06\x04\0\x03\x01\
    \t\0\x12\x03>\r\x0e\n\x0e\n\x07\x04\0\x03\x01\t\0\x01\x12\x03>\r\x0e\n\
    \x0e\n\x07\x04\0\x03\x01\t\0\x02\x12\x03>\r\x0e\n\x0e\n\x06\x04\0\x03\
    \x01\x03\0\x12\x04@\x04F\x05\n\x0e\n\x07\x04\0\x03\x01\x03\0\x01\x12\x03\
    @\x0c\x18\nA\n\x08\x04\0\x03\x01\x03\0\x02\0\x12\x03B\x06B\x1a0\x20Ident\
    ifier\x20for\x20the\x20policy\x20specifying\x20the\x20drop.\n\n\x11\n\t\
    \x04\0\x03\x01\x03\0\x02\0\x04\x12\x04B\x06@\x1a\n\x10\n\t\x04\0\x03\x01\
    \x03\0\x02\0\x05\x12\x03B\x06\x0c\n\x10\n\t\x04\0\x03\x01\x03\0\x02\0\
    \x01\x12\x03B\r\x15\n\x10\n\t\x04\0\x03\x01\x03\0\x02\0\x03\x12\x03B\x18\
    \x19\n\x10\n\t\x04\0\x03\x01\x03\0\x02\0\x08\x12\x03B\x1aA\n\x15\n\x0e\
    \x04\0\x03\x01\x03\0\x02\0\x08\x97\x8d8\x0e\x04\x12\x03B\x1b@\nQ\n\x08\
    \x04\0\x03\x01\x03\0\x02\x01\x12\x03E\x067\x1a@\x20Percentage\x20of\x20t\
    raffic\x20that\x20should\x20be\x20dropped\x20for\x20the\x20category.\n\n\
    \x11\n\t\x04\0\x03\x01\x03\0\x02\x01\x04\x12\x04E\x06BB\n\x10\n\t\x04\0\
    \x03\x01\x03\0\x02\x01\x06\x12\x03E\x06\"\n\x10\n\t\x04\0\x03\x01\x03\0\
    \x02\x01\x01\x12\x03E#2\n\x10\n\t\x04\0\x03\x01\x03\0\x02\x01\x03\x12\
    \x03E56\n\xaf\x06\n\x06\x04\0\x03\x01\x02\0\x12\x03Z\x04-\x1a\x9f\x06\
    \x20Action\x20to\x20trim\x20the\x20overall\x20incoming\x20traffic\x20to\
    \x20protect\x20the\x20upstream\n\x20hosts.\x20This\x20action\x20allows\
    \x20protection\x20in\x20case\x20the\x20hosts\x20are\x20unable\x20to\n\
    \x20recover\x20from\x20an\x20outage,\x20or\x20unable\x20to\x20autoscale\
    \x20or\x20unable\x20to\x20handle\n\x20incoming\x20traffic\x20volume\x20f\
    or\x20any\x20reason.\n\n\x20At\x20the\x20client\x20each\x20category\x20i\
    s\x20applied\x20one\x20after\x20the\x20other\x20to\x20generate\n\x20the\
    \x20'actual'\x20drop\x20percentage\x20on\x20all\x20outgoing\x20traffic.\
    \x20For\x20example:\n\n\x20..\x20code-block::\x20json\n\n\x20\x20{\x20\"\
    drop_overloads\":\x20[\n\x20\x20\x20\x20\x20\x20{\x20\"category\":\x20\"\
    throttle\",\x20\"drop_percentage\":\x2060\x20}\n\x20\x20\x20\x20\x20\x20\
    {\x20\"category\":\x20\"lb\",\x20\"drop_percentage\":\x2050\x20}\n\x20\
    \x20]}\n\n\x20The\x20actual\x20drop\x20percentages\x20applied\x20to\x20t\
    he\x20traffic\x20at\x20the\x20clients\x20will\x20be\n\x20\x20\x20\x20\"t\
    hrottle\"_drop\x20=\x2060%\n\x20\x20\x20\x20\"lb\"_drop\x20=\x2020%\x20\
    \x20//\x2050%\x20of\x20the\x20remaining\x20'actual'\x20load,\x20which\
    \x20is\x2040%.\n\x20\x20\x20\x20actual_outgoing_load\x20=\x2020%\x20//\
    \x20remaining\x20after\x20applying\x20all\x20categories.\n\n\x0e\n\x07\
    \x04\0\x03\x01\x02\0\x04\x12\x03Z\x04\x0c\n\x0e\n\x07\x04\0\x03\x01\x02\
    \0\x06\x12\x03Z\r\x19\n\x0e\n\x07\x04\0\x03\x01\x02\0\x01\x12\x03Z\x1a(\
    \n\x0e\n\x07\x04\0\x03\x01\x02\0\x03\x12\x03Z+,\n\xa6\x05\n\x06\x04\0\
    \x03\x01\x02\x01\x12\x03j\x04]\x1a\x96\x05\x20Priority\x20levels\x20and\
    \x20localities\x20are\x20considered\x20overprovisioned\x20with\x20this\n\
    \x20factor\x20(in\x20percentage).\x20This\x20means\x20that\x20we\x20don'\
    t\x20consider\x20a\x20priority\n\x20level\x20or\x20locality\x20unhealthy\
    \x20until\x20the\x20percentage\x20of\x20healthy\x20hosts\n\x20multiplied\
    \x20by\x20the\x20overprovisioning\x20factor\x20drops\x20below\x20100.\n\
    \x20With\x20the\x20default\x20value\x20140(1.4),\x20Envoy\x20doesn't\x20\
    consider\x20a\x20priority\x20level\n\x20or\x20a\x20locality\x20unhealthy\
    \x20until\x20their\x20percentage\x20of\x20healthy\x20hosts\x20drops\n\
    \x20below\x2072%.\x20For\x20example:\n\n\x20..\x20code-block::\x20json\n\
    \n\x20\x20{\x20\"overprovisioning_factor\":\x20100\x20}\n\n\x20Read\x20m\
    ore\x20at\x20:ref:`priority\x20levels\x20<arch_overview_load_balancing_p\
    riority_levels>`\x20and\n\x20:ref:`localities\x20<arch_overview_load_bal\
    ancing_locality_weighted_lb>`.\n\n\x0f\n\x07\x04\0\x03\x01\x02\x01\x04\
    \x12\x04j\x04Z-\n\x0e\n\x07\x04\0\x03\x01\x02\x01\x06\x12\x03j\x04\x1f\n\
    \x0e\n\x07\x04\0\x03\x01\x02\x01\x01\x12\x03j\x207\n\x0e\n\x07\x04\0\x03\
    \x01\x02\x01\x03\x12\x03j:;\n\x0e\n\x07\x04\0\x03\x01\x02\x01\x08\x12\
    \x03j<\\\n\x13\n\x0c\x04\0\x03\x01\x02\x01\x08\x97\x8d8\x05\x04\x12\x03j\
    =[\n.\n\x04\x04\0\x02\x03\x12\x03n\x02\x14\x1a!\x20Load\x20balancing\x20\
    policy\x20settings.\n\n\r\n\x05\x04\0\x02\x03\x04\x12\x04n\x02k\x03\n\
    \x0c\n\x05\x04\0\x02\x03\x06\x12\x03n\x02\x08\n\x0c\n\x05\x04\0\x02\x03\
    \x01\x12\x03n\t\x0f\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03n\x12\x13b\x06p\
    roto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
