// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

pub mod exts {
    use protobuf::Message as Message_imported_for_functions;

    pub const goproto_enum_prefix: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62001, phantom: ::std::marker::PhantomData };

    pub const goproto_enum_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62021, phantom: ::std::marker::PhantomData };

    pub const enum_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62022, phantom: ::std::marker::PhantomData };

    pub const enum_customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 62023, phantom: ::std::marker::PhantomData };

    pub const enumdecl: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62024, phantom: ::std::marker::PhantomData };

    pub const enumvalue_customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 66001, phantom: ::std::marker::PhantomData };

    pub const goproto_getters_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63001, phantom: ::std::marker::PhantomData };

    pub const goproto_enum_prefix_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63002, phantom: ::std::marker::PhantomData };

    pub const goproto_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63003, phantom: ::std::marker::PhantomData };

    pub const verbose_equal_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63004, phantom: ::std::marker::PhantomData };

    pub const face_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63005, phantom: ::std::marker::PhantomData };

    pub const gostring_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63006, phantom: ::std::marker::PhantomData };

    pub const populate_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63007, phantom: ::std::marker::PhantomData };

    pub const stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63008, phantom: ::std::marker::PhantomData };

    pub const onlyone_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63009, phantom: ::std::marker::PhantomData };

    pub const equal_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63013, phantom: ::std::marker::PhantomData };

    pub const description_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63014, phantom: ::std::marker::PhantomData };

    pub const testgen_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63015, phantom: ::std::marker::PhantomData };

    pub const benchgen_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63016, phantom: ::std::marker::PhantomData };

    pub const marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63017, phantom: ::std::marker::PhantomData };

    pub const unmarshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63018, phantom: ::std::marker::PhantomData };

    pub const stable_marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63019, phantom: ::std::marker::PhantomData };

    pub const sizer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63020, phantom: ::std::marker::PhantomData };

    pub const goproto_enum_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63021, phantom: ::std::marker::PhantomData };

    pub const enum_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63022, phantom: ::std::marker::PhantomData };

    pub const unsafe_marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63023, phantom: ::std::marker::PhantomData };

    pub const unsafe_unmarshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63024, phantom: ::std::marker::PhantomData };

    pub const goproto_extensions_map_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63025, phantom: ::std::marker::PhantomData };

    pub const goproto_unrecognized_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63026, phantom: ::std::marker::PhantomData };

    pub const gogoproto_import: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63027, phantom: ::std::marker::PhantomData };

    pub const protosizer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63028, phantom: ::std::marker::PhantomData };

    pub const compare_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63029, phantom: ::std::marker::PhantomData };

    pub const typedecl_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63030, phantom: ::std::marker::PhantomData };

    pub const enumdecl_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63031, phantom: ::std::marker::PhantomData };

    pub const goproto_getters: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64001, phantom: ::std::marker::PhantomData };

    pub const goproto_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64003, phantom: ::std::marker::PhantomData };

    pub const verbose_equal: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64004, phantom: ::std::marker::PhantomData };

    pub const face: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64005, phantom: ::std::marker::PhantomData };

    pub const gostring: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64006, phantom: ::std::marker::PhantomData };

    pub const populate: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64007, phantom: ::std::marker::PhantomData };

    pub const stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 67008, phantom: ::std::marker::PhantomData };

    pub const onlyone: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64009, phantom: ::std::marker::PhantomData };

    pub const equal: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64013, phantom: ::std::marker::PhantomData };

    pub const description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64014, phantom: ::std::marker::PhantomData };

    pub const testgen: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64015, phantom: ::std::marker::PhantomData };

    pub const benchgen: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64016, phantom: ::std::marker::PhantomData };

    pub const marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64017, phantom: ::std::marker::PhantomData };

    pub const unmarshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64018, phantom: ::std::marker::PhantomData };

    pub const stable_marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64019, phantom: ::std::marker::PhantomData };

    pub const sizer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64020, phantom: ::std::marker::PhantomData };

    pub const unsafe_marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64023, phantom: ::std::marker::PhantomData };

    pub const unsafe_unmarshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64024, phantom: ::std::marker::PhantomData };

    pub const goproto_extensions_map: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64025, phantom: ::std::marker::PhantomData };

    pub const goproto_unrecognized: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64026, phantom: ::std::marker::PhantomData };

    pub const protosizer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64028, phantom: ::std::marker::PhantomData };

    pub const compare: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64029, phantom: ::std::marker::PhantomData };

    pub const typedecl: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64030, phantom: ::std::marker::PhantomData };

    pub const nullable: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65001, phantom: ::std::marker::PhantomData };

    pub const embed: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65002, phantom: ::std::marker::PhantomData };

    pub const customtype: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65003, phantom: ::std::marker::PhantomData };

    pub const customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65004, phantom: ::std::marker::PhantomData };

    pub const jsontag: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65005, phantom: ::std::marker::PhantomData };

    pub const moretags: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65006, phantom: ::std::marker::PhantomData };

    pub const casttype: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65007, phantom: ::std::marker::PhantomData };

    pub const castkey: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65008, phantom: ::std::marker::PhantomData };

    pub const castvalue: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65009, phantom: ::std::marker::PhantomData };

    pub const stdtime: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65010, phantom: ::std::marker::PhantomData };

    pub const stdduration: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65011, phantom: ::std::marker::PhantomData };
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14gogoproto/gogo.proto\x12\tgogoproto\x1a\x20google/protobuf/descrip\
    tor.proto:N\n\x13goproto_enum_prefix\x18\xb1\xe4\x03\x20\x01(\x08\x12\
    \x1c.google.protobuf.EnumOptionsR\x11goprotoEnumPrefix:R\n\x15goproto_en\
    um_stringer\x18\xc5\xe4\x03\x20\x01(\x08\x12\x1c.google.protobuf.EnumOpt\
    ionsR\x13goprotoEnumStringer:C\n\renum_stringer\x18\xc6\xe4\x03\x20\x01(\
    \x08\x12\x1c.google.protobuf.EnumOptionsR\x0cenumStringer:G\n\x0fenum_cu\
    stomname\x18\xc7\xe4\x03\x20\x01(\t\x12\x1c.google.protobuf.EnumOptionsR\
    \x0eenumCustomname::\n\x08enumdecl\x18\xc8\xe4\x03\x20\x01(\x08\x12\x1c.\
    google.protobuf.EnumOptionsR\x08enumdecl:V\n\x14enumvalue_customname\x18\
    \xd1\x83\x04\x20\x01(\t\x12!.google.protobuf.EnumValueOptionsR\x13enumva\
    lueCustomname:N\n\x13goproto_getters_all\x18\x99\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x11goprotoGettersAll:U\n\x17goprot\
    o_enum_prefix_all\x18\x9a\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.F\
    ileOptionsR\x14goprotoEnumPrefixAll:P\n\x14goproto_stringer_all\x18\x9b\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x12goprotoStr\
    ingerAll:J\n\x11verbose_equal_all\x18\x9c\xec\x03\x20\x01(\x08\x12\x1c.g\
    oogle.protobuf.FileOptionsR\x0fverboseEqualAll:9\n\x08face_all\x18\x9d\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x07faceAll:A\
    \n\x0cgostring_all\x18\x9e\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.\
    FileOptionsR\x0bgostringAll:A\n\x0cpopulate_all\x18\x9f\xec\x03\x20\x01(\
    \x08\x12\x1c.google.protobuf.FileOptionsR\x0bpopulateAll:A\n\x0cstringer\
    _all\x18\xa0\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\
    \x0bstringerAll:?\n\x0bonlyone_all\x18\xa1\xec\x03\x20\x01(\x08\x12\x1c.\
    google.protobuf.FileOptionsR\nonlyoneAll:;\n\tequal_all\x18\xa5\xec\x03\
    \x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x08equalAll:G\n\x0fde\
    scription_all\x18\xa6\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileO\
    ptionsR\x0edescriptionAll:?\n\x0btestgen_all\x18\xa7\xec\x03\x20\x01(\
    \x08\x12\x1c.google.protobuf.FileOptionsR\ntestgenAll:A\n\x0cbenchgen_al\
    l\x18\xa8\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0bb\
    enchgenAll:C\n\rmarshaler_all\x18\xa9\xec\x03\x20\x01(\x08\x12\x1c.googl\
    e.protobuf.FileOptionsR\x0cmarshalerAll:G\n\x0funmarshaler_all\x18\xaa\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0eunmarshale\
    rAll:P\n\x14stable_marshaler_all\x18\xab\xec\x03\x20\x01(\x08\x12\x1c.go\
    ogle.protobuf.FileOptionsR\x12stableMarshalerAll:;\n\tsizer_all\x18\xac\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x08sizerAll:Y\
    \n\x19goproto_enum_stringer_all\x18\xad\xec\x03\x20\x01(\x08\x12\x1c.goo\
    gle.protobuf.FileOptionsR\x16goprotoEnumStringerAll:J\n\x11enum_stringer\
    _all\x18\xae\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\
    \x0fenumStringerAll:P\n\x14unsafe_marshaler_all\x18\xaf\xec\x03\x20\x01(\
    \x08\x12\x1c.google.protobuf.FileOptionsR\x12unsafeMarshalerAll:T\n\x16u\
    nsafe_unmarshaler_all\x18\xb0\xec\x03\x20\x01(\x08\x12\x1c.google.protob\
    uf.FileOptionsR\x14unsafeUnmarshalerAll:[\n\x1agoproto_extensions_map_al\
    l\x18\xb1\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x17g\
    oprotoExtensionsMapAll:X\n\x18goproto_unrecognized_all\x18\xb2\xec\x03\
    \x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x16goprotoUnrecognize\
    dAll:I\n\x10gogoproto_import\x18\xb3\xec\x03\x20\x01(\x08\x12\x1c.google\
    .protobuf.FileOptionsR\x0fgogoprotoImport:E\n\x0eprotosizer_all\x18\xb4\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\rprotosizerAl\
    l:?\n\x0bcompare_all\x18\xb5\xec\x03\x20\x01(\x08\x12\x1c.google.protobu\
    f.FileOptionsR\ncompareAll:A\n\x0ctypedecl_all\x18\xb6\xec\x03\x20\x01(\
    \x08\x12\x1c.google.protobuf.FileOptionsR\x0btypedeclAll:A\n\x0cenumdecl\
    _all\x18\xb7\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\
    \x0benumdeclAll:J\n\x0fgoproto_getters\x18\x81\xf4\x03\x20\x01(\x08\x12\
    \x1f.google.protobuf.MessageOptionsR\x0egoprotoGetters:L\n\x10goproto_st\
    ringer\x18\x83\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptio\
    nsR\x0fgoprotoStringer:F\n\rverbose_equal\x18\x84\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x0cverboseEqual:5\n\x04face\x18\
    \x85\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x04fac\
    e:=\n\x08gostring\x18\x86\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.M\
    essageOptionsR\x08gostring:=\n\x08populate\x18\x87\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x08populate:=\n\x08stringer\x18\
    \xc0\x8b\x04\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x08str\
    inger:;\n\x07onlyone\x18\x89\xf4\x03\x20\x01(\x08\x12\x1f.google.protobu\
    f.MessageOptionsR\x07onlyone:7\n\x05equal\x18\x8d\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x05equal:C\n\x0bdescription\x18\
    \x8e\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0bdes\
    cription:;\n\x07testgen\x18\x8f\xf4\x03\x20\x01(\x08\x12\x1f.google.prot\
    obuf.MessageOptionsR\x07testgen:=\n\x08benchgen\x18\x90\xf4\x03\x20\x01(\
    \x08\x12\x1f.google.protobuf.MessageOptionsR\x08benchgen:?\n\tmarshaler\
    \x18\x91\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\tm\
    arshaler:C\n\x0bunmarshaler\x18\x92\xf4\x03\x20\x01(\x08\x12\x1f.google.\
    protobuf.MessageOptionsR\x0bunmarshaler:L\n\x10stable_marshaler\x18\x93\
    \xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0fstableM\
    arshaler:7\n\x05sizer\x18\x94\xf4\x03\x20\x01(\x08\x12\x1f.google.protob\
    uf.MessageOptionsR\x05sizer:L\n\x10unsafe_marshaler\x18\x97\xf4\x03\x20\
    \x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0funsafeMarshaler:P\n\
    \x12unsafe_unmarshaler\x18\x98\xf4\x03\x20\x01(\x08\x12\x1f.google.proto\
    buf.MessageOptionsR\x11unsafeUnmarshaler:W\n\x16goproto_extensions_map\
    \x18\x99\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\
    \x14goprotoExtensionsMap:T\n\x14goproto_unrecognized\x18\x9a\xf4\x03\x20\
    \x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x13goprotoUnrecognized\
    :A\n\nprotosizer\x18\x9c\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.Me\
    ssageOptionsR\nprotosizer:;\n\x07compare\x18\x9d\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x07compare:=\n\x08typedecl\x18\
    \x9e\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x08typ\
    edecl:;\n\x08nullable\x18\xe9\xfb\x03\x20\x01(\x08\x12\x1d.google.protob\
    uf.FieldOptionsR\x08nullable:5\n\x05embed\x18\xea\xfb\x03\x20\x01(\x08\
    \x12\x1d.google.protobuf.FieldOptionsR\x05embed:?\n\ncustomtype\x18\xeb\
    \xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\ncustomtype:?\
    \n\ncustomname\x18\xec\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldO\
    ptionsR\ncustomname:9\n\x07jsontag\x18\xed\xfb\x03\x20\x01(\t\x12\x1d.go\
    ogle.protobuf.FieldOptionsR\x07jsontag:;\n\x08moretags\x18\xee\xfb\x03\
    \x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x08moretags:;\n\x08cas\
    ttype\x18\xef\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\
    \x08casttype:9\n\x07castkey\x18\xf0\xfb\x03\x20\x01(\t\x12\x1d.google.pr\
    otobuf.FieldOptionsR\x07castkey:=\n\tcastvalue\x18\xf1\xfb\x03\x20\x01(\
    \t\x12\x1d.google.protobuf.FieldOptionsR\tcastvalue:9\n\x07stdtime\x18\
    \xf2\xfb\x03\x20\x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\x07stdti\
    me:A\n\x0bstdduration\x18\xf3\xfb\x03\x20\x01(\x08\x12\x1d.google.protob\
    uf.FieldOptionsR\x0bstddurationB!\n\x13com.google.protobufB\nGoGoProtosJ\
    \xe01\n\x07\x12\x05\x1c\0\x81\x01\x01\n\xfc\n\n\x01\x0c\x12\x03\x1c\0\
    \x122\xf1\n\x20Protocol\x20Buffers\x20for\x20Go\x20with\x20Gadgets\n\n\
    \x20Copyright\x20(c)\x202013,\x20The\x20GoGo\x20Authors.\x20All\x20right\
    s\x20reserved.\n\x20http://github.com/gogo/protobuf\n\n\x20Redistributio\
    n\x20and\x20use\x20in\x20source\x20and\x20binary\x20forms,\x20with\x20or\
    \x20without\n\x20modification,\x20are\x20permitted\x20provided\x20that\
    \x20the\x20following\x20conditions\x20are\n\x20met:\n\n\x20\x20\x20\x20\
    \x20*\x20Redistributions\x20of\x20source\x20code\x20must\x20retain\x20th\
    e\x20above\x20copyright\n\x20notice,\x20this\x20list\x20of\x20conditions\
    \x20and\x20the\x20following\x20disclaimer.\n\x20\x20\x20\x20\x20*\x20Red\
    istributions\x20in\x20binary\x20form\x20must\x20reproduce\x20the\x20abov\
    e\n\x20copyright\x20notice,\x20this\x20list\x20of\x20conditions\x20and\
    \x20the\x20following\x20disclaimer\n\x20in\x20the\x20documentation\x20an\
    d/or\x20other\x20materials\x20provided\x20with\x20the\n\x20distribution.\
    \n\n\x20THIS\x20SOFTWARE\x20IS\x20PROVIDED\x20BY\x20THE\x20COPYRIGHT\x20\
    HOLDERS\x20AND\x20CONTRIBUTORS\n\x20\"AS\x20IS\"\x20AND\x20ANY\x20EXPRES\
    S\x20OR\x20IMPLIED\x20WARRANTIES,\x20INCLUDING,\x20BUT\x20NOT\n\x20LIMIT\
    ED\x20TO,\x20THE\x20IMPLIED\x20WARRANTIES\x20OF\x20MERCHANTABILITY\x20AN\
    D\x20FITNESS\x20FOR\n\x20A\x20PARTICULAR\x20PURPOSE\x20ARE\x20DISCLAIMED\
    .\x20IN\x20NO\x20EVENT\x20SHALL\x20THE\x20COPYRIGHT\n\x20OWNER\x20OR\x20\
    CONTRIBUTORS\x20BE\x20LIABLE\x20FOR\x20ANY\x20DIRECT,\x20INDIRECT,\x20IN\
    CIDENTAL,\n\x20SPECIAL,\x20EXEMPLARY,\x20OR\x20CONSEQUENTIAL\x20DAMAGES\
    \x20(INCLUDING,\x20BUT\x20NOT\n\x20LIMITED\x20TO,\x20PROCUREMENT\x20OF\
    \x20SUBSTITUTE\x20GOODS\x20OR\x20SERVICES;\x20LOSS\x20OF\x20USE,\n\x20DA\
    TA,\x20OR\x20PROFITS;\x20OR\x20BUSINESS\x20INTERRUPTION)\x20HOWEVER\x20C\
    AUSED\x20AND\x20ON\x20ANY\n\x20THEORY\x20OF\x20LIABILITY,\x20WHETHER\x20\
    IN\x20CONTRACT,\x20STRICT\x20LIABILITY,\x20OR\x20TORT\n\x20(INCLUDING\
    \x20NEGLIGENCE\x20OR\x20OTHERWISE)\x20ARISING\x20IN\x20ANY\x20WAY\x20OUT\
    \x20OF\x20THE\x20USE\n\x20OF\x20THIS\x20SOFTWARE,\x20EVEN\x20IF\x20ADVIS\
    ED\x20OF\x20THE\x20POSSIBILITY\x20OF\x20SUCH\x20DAMAGE.\n\n\x08\n\x01\
    \x02\x12\x03\x1d\x08\x11\n\t\n\x02\x03\0\x12\x03\x1f\x07)\n\x08\n\x01\
    \x08\x12\x03!\0,\n\t\n\x02\x08\x01\x12\x03!\0,\n\x08\n\x01\x08\x12\x03\"\
    \0+\n\t\n\x02\x08\x08\x12\x03\"\0+\n\t\n\x01\x07\x12\x04$\0*\x01\n\t\n\
    \x02\x07\0\x12\x03%\x082\n\n\n\x03\x07\0\x02\x12\x03$\x07\"\n\n\n\x03\
    \x07\0\x04\x12\x03%\x08\x10\n\n\n\x03\x07\0\x05\x12\x03%\x11\x15\n\n\n\
    \x03\x07\0\x01\x12\x03%\x16)\n\n\n\x03\x07\0\x03\x12\x03%,1\n\t\n\x02\
    \x07\x01\x12\x03&\x084\n\n\n\x03\x07\x01\x02\x12\x03$\x07\"\n\n\n\x03\
    \x07\x01\x04\x12\x03&\x08\x10\n\n\n\x03\x07\x01\x05\x12\x03&\x11\x15\n\n\
    \n\x03\x07\x01\x01\x12\x03&\x16+\n\n\n\x03\x07\x01\x03\x12\x03&.3\n\t\n\
    \x02\x07\x02\x12\x03'\x08,\n\n\n\x03\x07\x02\x02\x12\x03$\x07\"\n\n\n\
    \x03\x07\x02\x04\x12\x03'\x08\x10\n\n\n\x03\x07\x02\x05\x12\x03'\x11\x15\
    \n\n\n\x03\x07\x02\x01\x12\x03'\x16#\n\n\n\x03\x07\x02\x03\x12\x03'&+\n\
    \t\n\x02\x07\x03\x12\x03(\x080\n\n\n\x03\x07\x03\x02\x12\x03$\x07\"\n\n\
    \n\x03\x07\x03\x04\x12\x03(\x08\x10\n\n\n\x03\x07\x03\x05\x12\x03(\x11\
    \x17\n\n\n\x03\x07\x03\x01\x12\x03(\x18'\n\n\n\x03\x07\x03\x03\x12\x03(*\
    /\n\t\n\x02\x07\x04\x12\x03)\x08'\n\n\n\x03\x07\x04\x02\x12\x03$\x07\"\n\
    \n\n\x03\x07\x04\x04\x12\x03)\x08\x10\n\n\n\x03\x07\x04\x05\x12\x03)\x11\
    \x15\n\n\n\x03\x07\x04\x01\x12\x03)\x16\x1e\n\n\n\x03\x07\x04\x03\x12\
    \x03)!&\n\t\n\x01\x07\x12\x04,\0.\x01\n\t\n\x02\x07\x05\x12\x03-\x085\n\
    \n\n\x03\x07\x05\x02\x12\x03,\x07'\n\n\n\x03\x07\x05\x04\x12\x03-\x08\
    \x10\n\n\n\x03\x07\x05\x05\x12\x03-\x11\x17\n\n\n\x03\x07\x05\x01\x12\
    \x03-\x18,\n\n\n\x03\x07\x05\x03\x12\x03-/4\n\t\n\x01\x07\x12\x040\0R\
    \x01\n\t\n\x02\x07\x06\x12\x031\x082\n\n\n\x03\x07\x06\x02\x12\x030\x07\
    \"\n\n\n\x03\x07\x06\x04\x12\x031\x08\x10\n\n\n\x03\x07\x06\x05\x12\x031\
    \x11\x15\n\n\n\x03\x07\x06\x01\x12\x031\x16)\n\n\n\x03\x07\x06\x03\x12\
    \x031,1\n\t\n\x02\x07\x07\x12\x032\x086\n\n\n\x03\x07\x07\x02\x12\x030\
    \x07\"\n\n\n\x03\x07\x07\x04\x12\x032\x08\x10\n\n\n\x03\x07\x07\x05\x12\
    \x032\x11\x15\n\n\n\x03\x07\x07\x01\x12\x032\x16-\n\n\n\x03\x07\x07\x03\
    \x12\x03205\n\t\n\x02\x07\x08\x12\x033\x083\n\n\n\x03\x07\x08\x02\x12\
    \x030\x07\"\n\n\n\x03\x07\x08\x04\x12\x033\x08\x10\n\n\n\x03\x07\x08\x05\
    \x12\x033\x11\x15\n\n\n\x03\x07\x08\x01\x12\x033\x16*\n\n\n\x03\x07\x08\
    \x03\x12\x033-2\n\t\n\x02\x07\t\x12\x034\x080\n\n\n\x03\x07\t\x02\x12\
    \x030\x07\"\n\n\n\x03\x07\t\x04\x12\x034\x08\x10\n\n\n\x03\x07\t\x05\x12\
    \x034\x11\x15\n\n\n\x03\x07\t\x01\x12\x034\x16'\n\n\n\x03\x07\t\x03\x12\
    \x034*/\n\t\n\x02\x07\n\x12\x035\x08'\n\n\n\x03\x07\n\x02\x12\x030\x07\"\
    \n\n\n\x03\x07\n\x04\x12\x035\x08\x10\n\n\n\x03\x07\n\x05\x12\x035\x11\
    \x15\n\n\n\x03\x07\n\x01\x12\x035\x16\x1e\n\n\n\x03\x07\n\x03\x12\x035!&\
    \n\t\n\x02\x07\x0b\x12\x036\x08+\n\n\n\x03\x07\x0b\x02\x12\x030\x07\"\n\
    \n\n\x03\x07\x0b\x04\x12\x036\x08\x10\n\n\n\x03\x07\x0b\x05\x12\x036\x11\
    \x15\n\n\n\x03\x07\x0b\x01\x12\x036\x16\"\n\n\n\x03\x07\x0b\x03\x12\x036\
    %*\n\t\n\x02\x07\x0c\x12\x037\x08+\n\n\n\x03\x07\x0c\x02\x12\x030\x07\"\
    \n\n\n\x03\x07\x0c\x04\x12\x037\x08\x10\n\n\n\x03\x07\x0c\x05\x12\x037\
    \x11\x15\n\n\n\x03\x07\x0c\x01\x12\x037\x16\"\n\n\n\x03\x07\x0c\x03\x12\
    \x037%*\n\t\n\x02\x07\r\x12\x038\x08+\n\n\n\x03\x07\r\x02\x12\x030\x07\"\
    \n\n\n\x03\x07\r\x04\x12\x038\x08\x10\n\n\n\x03\x07\r\x05\x12\x038\x11\
    \x15\n\n\n\x03\x07\r\x01\x12\x038\x16\"\n\n\n\x03\x07\r\x03\x12\x038%*\n\
    \t\n\x02\x07\x0e\x12\x039\x08*\n\n\n\x03\x07\x0e\x02\x12\x030\x07\"\n\n\
    \n\x03\x07\x0e\x04\x12\x039\x08\x10\n\n\n\x03\x07\x0e\x05\x12\x039\x11\
    \x15\n\n\n\x03\x07\x0e\x01\x12\x039\x16!\n\n\n\x03\x07\x0e\x03\x12\x039$\
    )\n\t\n\x02\x07\x0f\x12\x03;\x08(\n\n\n\x03\x07\x0f\x02\x12\x030\x07\"\n\
    \n\n\x03\x07\x0f\x04\x12\x03;\x08\x10\n\n\n\x03\x07\x0f\x05\x12\x03;\x11\
    \x15\n\n\n\x03\x07\x0f\x01\x12\x03;\x16\x1f\n\n\n\x03\x07\x0f\x03\x12\
    \x03;\"'\n\t\n\x02\x07\x10\x12\x03<\x08.\n\n\n\x03\x07\x10\x02\x12\x030\
    \x07\"\n\n\n\x03\x07\x10\x04\x12\x03<\x08\x10\n\n\n\x03\x07\x10\x05\x12\
    \x03<\x11\x15\n\n\n\x03\x07\x10\x01\x12\x03<\x16%\n\n\n\x03\x07\x10\x03\
    \x12\x03<(-\n\t\n\x02\x07\x11\x12\x03=\x08*\n\n\n\x03\x07\x11\x02\x12\
    \x030\x07\"\n\n\n\x03\x07\x11\x04\x12\x03=\x08\x10\n\n\n\x03\x07\x11\x05\
    \x12\x03=\x11\x15\n\n\n\x03\x07\x11\x01\x12\x03=\x16!\n\n\n\x03\x07\x11\
    \x03\x12\x03=$)\n\t\n\x02\x07\x12\x12\x03>\x08+\n\n\n\x03\x07\x12\x02\
    \x12\x030\x07\"\n\n\n\x03\x07\x12\x04\x12\x03>\x08\x10\n\n\n\x03\x07\x12\
    \x05\x12\x03>\x11\x15\n\n\n\x03\x07\x12\x01\x12\x03>\x16\"\n\n\n\x03\x07\
    \x12\x03\x12\x03>%*\n\t\n\x02\x07\x13\x12\x03?\x08,\n\n\n\x03\x07\x13\
    \x02\x12\x030\x07\"\n\n\n\x03\x07\x13\x04\x12\x03?\x08\x10\n\n\n\x03\x07\
    \x13\x05\x12\x03?\x11\x15\n\n\n\x03\x07\x13\x01\x12\x03?\x16#\n\n\n\x03\
    \x07\x13\x03\x12\x03?&+\n\t\n\x02\x07\x14\x12\x03@\x08.\n\n\n\x03\x07\
    \x14\x02\x12\x030\x07\"\n\n\n\x03\x07\x14\x04\x12\x03@\x08\x10\n\n\n\x03\
    \x07\x14\x05\x12\x03@\x11\x15\n\n\n\x03\x07\x14\x01\x12\x03@\x16%\n\n\n\
    \x03\x07\x14\x03\x12\x03@(-\n\t\n\x02\x07\x15\x12\x03A\x083\n\n\n\x03\
    \x07\x15\x02\x12\x030\x07\"\n\n\n\x03\x07\x15\x04\x12\x03A\x08\x10\n\n\n\
    \x03\x07\x15\x05\x12\x03A\x11\x15\n\n\n\x03\x07\x15\x01\x12\x03A\x16*\n\
    \n\n\x03\x07\x15\x03\x12\x03A-2\n\t\n\x02\x07\x16\x12\x03C\x08(\n\n\n\
    \x03\x07\x16\x02\x12\x030\x07\"\n\n\n\x03\x07\x16\x04\x12\x03C\x08\x10\n\
    \n\n\x03\x07\x16\x05\x12\x03C\x11\x15\n\n\n\x03\x07\x16\x01\x12\x03C\x16\
    \x1f\n\n\n\x03\x07\x16\x03\x12\x03C\"'\n\t\n\x02\x07\x17\x12\x03E\x088\n\
    \n\n\x03\x07\x17\x02\x12\x030\x07\"\n\n\n\x03\x07\x17\x04\x12\x03E\x08\
    \x10\n\n\n\x03\x07\x17\x05\x12\x03E\x11\x15\n\n\n\x03\x07\x17\x01\x12\
    \x03E\x16/\n\n\n\x03\x07\x17\x03\x12\x03E27\n\t\n\x02\x07\x18\x12\x03F\
    \x080\n\n\n\x03\x07\x18\x02\x12\x030\x07\"\n\n\n\x03\x07\x18\x04\x12\x03\
    F\x08\x10\n\n\n\x03\x07\x18\x05\x12\x03F\x11\x15\n\n\n\x03\x07\x18\x01\
    \x12\x03F\x16'\n\n\n\x03\x07\x18\x03\x12\x03F*/\n\t\n\x02\x07\x19\x12\
    \x03H\x083\n\n\n\x03\x07\x19\x02\x12\x030\x07\"\n\n\n\x03\x07\x19\x04\
    \x12\x03H\x08\x10\n\n\n\x03\x07\x19\x05\x12\x03H\x11\x15\n\n\n\x03\x07\
    \x19\x01\x12\x03H\x16*\n\n\n\x03\x07\x19\x03\x12\x03H-2\n\t\n\x02\x07\
    \x1a\x12\x03I\x085\n\n\n\x03\x07\x1a\x02\x12\x030\x07\"\n\n\n\x03\x07\
    \x1a\x04\x12\x03I\x08\x10\n\n\n\x03\x07\x1a\x05\x12\x03I\x11\x15\n\n\n\
    \x03\x07\x1a\x01\x12\x03I\x16,\n\n\n\x03\x07\x1a\x03\x12\x03I/4\n\t\n\
    \x02\x07\x1b\x12\x03K\x089\n\n\n\x03\x07\x1b\x02\x12\x030\x07\"\n\n\n\
    \x03\x07\x1b\x04\x12\x03K\x08\x10\n\n\n\x03\x07\x1b\x05\x12\x03K\x11\x15\
    \n\n\n\x03\x07\x1b\x01\x12\x03K\x160\n\n\n\x03\x07\x1b\x03\x12\x03K38\n\
    \t\n\x02\x07\x1c\x12\x03L\x087\n\n\n\x03\x07\x1c\x02\x12\x030\x07\"\n\n\
    \n\x03\x07\x1c\x04\x12\x03L\x08\x10\n\n\n\x03\x07\x1c\x05\x12\x03L\x11\
    \x15\n\n\n\x03\x07\x1c\x01\x12\x03L\x16.\n\n\n\x03\x07\x1c\x03\x12\x03L1\
    6\n\t\n\x02\x07\x1d\x12\x03M\x08/\n\n\n\x03\x07\x1d\x02\x12\x030\x07\"\n\
    \n\n\x03\x07\x1d\x04\x12\x03M\x08\x10\n\n\n\x03\x07\x1d\x05\x12\x03M\x11\
    \x15\n\n\n\x03\x07\x1d\x01\x12\x03M\x16&\n\n\n\x03\x07\x1d\x03\x12\x03M)\
    .\n\t\n\x02\x07\x1e\x12\x03N\x08-\n\n\n\x03\x07\x1e\x02\x12\x030\x07\"\n\
    \n\n\x03\x07\x1e\x04\x12\x03N\x08\x10\n\n\n\x03\x07\x1e\x05\x12\x03N\x11\
    \x15\n\n\n\x03\x07\x1e\x01\x12\x03N\x16$\n\n\n\x03\x07\x1e\x03\x12\x03N'\
    ,\n\t\n\x02\x07\x1f\x12\x03O\x08*\n\n\n\x03\x07\x1f\x02\x12\x030\x07\"\n\
    \n\n\x03\x07\x1f\x04\x12\x03O\x08\x10\n\n\n\x03\x07\x1f\x05\x12\x03O\x11\
    \x15\n\n\n\x03\x07\x1f\x01\x12\x03O\x16!\n\n\n\x03\x07\x1f\x03\x12\x03O$\
    )\n\t\n\x02\x07\x20\x12\x03P\x04'\n\n\n\x03\x07\x20\x02\x12\x030\x07\"\n\
    \n\n\x03\x07\x20\x04\x12\x03P\x04\x0c\n\n\n\x03\x07\x20\x05\x12\x03P\r\
    \x11\n\n\n\x03\x07\x20\x01\x12\x03P\x12\x1e\n\n\n\x03\x07\x20\x03\x12\
    \x03P!&\n\t\n\x02\x07!\x12\x03Q\x04'\n\n\n\x03\x07!\x02\x12\x030\x07\"\n\
    \n\n\x03\x07!\x04\x12\x03Q\x04\x0c\n\n\n\x03\x07!\x05\x12\x03Q\r\x11\n\n\
    \n\x03\x07!\x01\x12\x03Q\x12\x1e\n\n\n\x03\x07!\x03\x12\x03Q!&\n\t\n\x01\
    \x07\x12\x04T\0r\x01\n\t\n\x02\x07\"\x12\x03U\x08.\n\n\n\x03\x07\"\x02\
    \x12\x03T\x07%\n\n\n\x03\x07\"\x04\x12\x03U\x08\x10\n\n\n\x03\x07\"\x05\
    \x12\x03U\x11\x15\n\n\n\x03\x07\"\x01\x12\x03U\x16%\n\n\n\x03\x07\"\x03\
    \x12\x03U(-\n\t\n\x02\x07#\x12\x03V\x08/\n\n\n\x03\x07#\x02\x12\x03T\x07\
    %\n\n\n\x03\x07#\x04\x12\x03V\x08\x10\n\n\n\x03\x07#\x05\x12\x03V\x11\
    \x15\n\n\n\x03\x07#\x01\x12\x03V\x16&\n\n\n\x03\x07#\x03\x12\x03V).\n\t\
    \n\x02\x07$\x12\x03W\x08,\n\n\n\x03\x07$\x02\x12\x03T\x07%\n\n\n\x03\x07\
    $\x04\x12\x03W\x08\x10\n\n\n\x03\x07$\x05\x12\x03W\x11\x15\n\n\n\x03\x07\
    $\x01\x12\x03W\x16#\n\n\n\x03\x07$\x03\x12\x03W&+\n\t\n\x02\x07%\x12\x03\
    X\x08#\n\n\n\x03\x07%\x02\x12\x03T\x07%\n\n\n\x03\x07%\x04\x12\x03X\x08\
    \x10\n\n\n\x03\x07%\x05\x12\x03X\x11\x15\n\n\n\x03\x07%\x01\x12\x03X\x16\
    \x1a\n\n\n\x03\x07%\x03\x12\x03X\x1d\"\n\t\n\x02\x07&\x12\x03Y\x08'\n\n\
    \n\x03\x07&\x02\x12\x03T\x07%\n\n\n\x03\x07&\x04\x12\x03Y\x08\x10\n\n\n\
    \x03\x07&\x05\x12\x03Y\x11\x15\n\n\n\x03\x07&\x01\x12\x03Y\x16\x1e\n\n\n\
    \x03\x07&\x03\x12\x03Y!&\n\t\n\x02\x07'\x12\x03Z\x08'\n\n\n\x03\x07'\x02\
    \x12\x03T\x07%\n\n\n\x03\x07'\x04\x12\x03Z\x08\x10\n\n\n\x03\x07'\x05\
    \x12\x03Z\x11\x15\n\n\n\x03\x07'\x01\x12\x03Z\x16\x1e\n\n\n\x03\x07'\x03\
    \x12\x03Z!&\n\t\n\x02\x07(\x12\x03[\x08'\n\n\n\x03\x07(\x02\x12\x03T\x07\
    %\n\n\n\x03\x07(\x04\x12\x03[\x08\x10\n\n\n\x03\x07(\x05\x12\x03[\x11\
    \x15\n\n\n\x03\x07(\x01\x12\x03[\x16\x1e\n\n\n\x03\x07(\x03\x12\x03[!&\n\
    \t\n\x02\x07)\x12\x03\\\x08&\n\n\n\x03\x07)\x02\x12\x03T\x07%\n\n\n\x03\
    \x07)\x04\x12\x03\\\x08\x10\n\n\n\x03\x07)\x05\x12\x03\\\x11\x15\n\n\n\
    \x03\x07)\x01\x12\x03\\\x16\x1d\n\n\n\x03\x07)\x03\x12\x03\\\x20%\n\t\n\
    \x02\x07*\x12\x03^\x08$\n\n\n\x03\x07*\x02\x12\x03T\x07%\n\n\n\x03\x07*\
    \x04\x12\x03^\x08\x10\n\n\n\x03\x07*\x05\x12\x03^\x11\x15\n\n\n\x03\x07*\
    \x01\x12\x03^\x16\x1b\n\n\n\x03\x07*\x03\x12\x03^\x1e#\n\t\n\x02\x07+\
    \x12\x03_\x08*\n\n\n\x03\x07+\x02\x12\x03T\x07%\n\n\n\x03\x07+\x04\x12\
    \x03_\x08\x10\n\n\n\x03\x07+\x05\x12\x03_\x11\x15\n\n\n\x03\x07+\x01\x12\
    \x03_\x16!\n\n\n\x03\x07+\x03\x12\x03_$)\n\t\n\x02\x07,\x12\x03`\x08&\n\
    \n\n\x03\x07,\x02\x12\x03T\x07%\n\n\n\x03\x07,\x04\x12\x03`\x08\x10\n\n\
    \n\x03\x07,\x05\x12\x03`\x11\x15\n\n\n\x03\x07,\x01\x12\x03`\x16\x1d\n\n\
    \n\x03\x07,\x03\x12\x03`\x20%\n\t\n\x02\x07-\x12\x03a\x08'\n\n\n\x03\x07\
    -\x02\x12\x03T\x07%\n\n\n\x03\x07-\x04\x12\x03a\x08\x10\n\n\n\x03\x07-\
    \x05\x12\x03a\x11\x15\n\n\n\x03\x07-\x01\x12\x03a\x16\x1e\n\n\n\x03\x07-\
    \x03\x12\x03a!&\n\t\n\x02\x07.\x12\x03b\x08(\n\n\n\x03\x07.\x02\x12\x03T\
    \x07%\n\n\n\x03\x07.\x04\x12\x03b\x08\x10\n\n\n\x03\x07.\x05\x12\x03b\
    \x11\x15\n\n\n\x03\x07.\x01\x12\x03b\x16\x1f\n\n\n\x03\x07.\x03\x12\x03b\
    \"'\n\t\n\x02\x07/\x12\x03c\x08*\n\n\n\x03\x07/\x02\x12\x03T\x07%\n\n\n\
    \x03\x07/\x04\x12\x03c\x08\x10\n\n\n\x03\x07/\x05\x12\x03c\x11\x15\n\n\n\
    \x03\x07/\x01\x12\x03c\x16!\n\n\n\x03\x07/\x03\x12\x03c$)\n\t\n\x02\x070\
    \x12\x03d\x08/\n\n\n\x03\x070\x02\x12\x03T\x07%\n\n\n\x03\x070\x04\x12\
    \x03d\x08\x10\n\n\n\x03\x070\x05\x12\x03d\x11\x15\n\n\n\x03\x070\x01\x12\
    \x03d\x16&\n\n\n\x03\x070\x03\x12\x03d).\n\t\n\x02\x071\x12\x03f\x08$\n\
    \n\n\x03\x071\x02\x12\x03T\x07%\n\n\n\x03\x071\x04\x12\x03f\x08\x10\n\n\
    \n\x03\x071\x05\x12\x03f\x11\x15\n\n\n\x03\x071\x01\x12\x03f\x16\x1b\n\n\
    \n\x03\x071\x03\x12\x03f\x1e#\n\t\n\x02\x072\x12\x03h\x08/\n\n\n\x03\x07\
    2\x02\x12\x03T\x07%\n\n\n\x03\x072\x04\x12\x03h\x08\x10\n\n\n\x03\x072\
    \x05\x12\x03h\x11\x15\n\n\n\x03\x072\x01\x12\x03h\x16&\n\n\n\x03\x072\
    \x03\x12\x03h).\n\t\n\x02\x073\x12\x03i\x081\n\n\n\x03\x073\x02\x12\x03T\
    \x07%\n\n\n\x03\x073\x04\x12\x03i\x08\x10\n\n\n\x03\x073\x05\x12\x03i\
    \x11\x15\n\n\n\x03\x073\x01\x12\x03i\x16(\n\n\n\x03\x073\x03\x12\x03i+0\
    \n\t\n\x02\x074\x12\x03k\x085\n\n\n\x03\x074\x02\x12\x03T\x07%\n\n\n\x03\
    \x074\x04\x12\x03k\x08\x10\n\n\n\x03\x074\x05\x12\x03k\x11\x15\n\n\n\x03\
    \x074\x01\x12\x03k\x16,\n\n\n\x03\x074\x03\x12\x03k/4\n\t\n\x02\x075\x12\
    \x03l\x083\n\n\n\x03\x075\x02\x12\x03T\x07%\n\n\n\x03\x075\x04\x12\x03l\
    \x08\x10\n\n\n\x03\x075\x05\x12\x03l\x11\x15\n\n\n\x03\x075\x01\x12\x03l\
    \x16*\n\n\n\x03\x075\x03\x12\x03l-2\n\t\n\x02\x076\x12\x03n\x08)\n\n\n\
    \x03\x076\x02\x12\x03T\x07%\n\n\n\x03\x076\x04\x12\x03n\x08\x10\n\n\n\
    \x03\x076\x05\x12\x03n\x11\x15\n\n\n\x03\x076\x01\x12\x03n\x16\x20\n\n\n\
    \x03\x076\x03\x12\x03n#(\n\t\n\x02\x077\x12\x03o\x08&\n\n\n\x03\x077\x02\
    \x12\x03T\x07%\n\n\n\x03\x077\x04\x12\x03o\x08\x10\n\n\n\x03\x077\x05\
    \x12\x03o\x11\x15\n\n\n\x03\x077\x01\x12\x03o\x16\x1d\n\n\n\x03\x077\x03\
    \x12\x03o\x20%\n\t\n\x02\x078\x12\x03q\x08'\n\n\n\x03\x078\x02\x12\x03T\
    \x07%\n\n\n\x03\x078\x04\x12\x03q\x08\x10\n\n\n\x03\x078\x05\x12\x03q\
    \x11\x15\n\n\n\x03\x078\x01\x12\x03q\x16\x1e\n\n\n\x03\x078\x03\x12\x03q\
    !&\n\n\n\x01\x07\x12\x05t\0\x81\x01\x01\n\t\n\x02\x079\x12\x03u\x08'\n\n\
    \n\x03\x079\x02\x12\x03t\x07#\n\n\n\x03\x079\x04\x12\x03u\x08\x10\n\n\n\
    \x03\x079\x05\x12\x03u\x11\x15\n\n\n\x03\x079\x01\x12\x03u\x16\x1e\n\n\n\
    \x03\x079\x03\x12\x03u!&\n\t\n\x02\x07:\x12\x03v\x08$\n\n\n\x03\x07:\x02\
    \x12\x03t\x07#\n\n\n\x03\x07:\x04\x12\x03v\x08\x10\n\n\n\x03\x07:\x05\
    \x12\x03v\x11\x15\n\n\n\x03\x07:\x01\x12\x03v\x16\x1b\n\n\n\x03\x07:\x03\
    \x12\x03v\x1e#\n\t\n\x02\x07;\x12\x03w\x08+\n\n\n\x03\x07;\x02\x12\x03t\
    \x07#\n\n\n\x03\x07;\x04\x12\x03w\x08\x10\n\n\n\x03\x07;\x05\x12\x03w\
    \x11\x17\n\n\n\x03\x07;\x01\x12\x03w\x18\"\n\n\n\x03\x07;\x03\x12\x03w%*\
    \n\t\n\x02\x07<\x12\x03x\x08+\n\n\n\x03\x07<\x02\x12\x03t\x07#\n\n\n\x03\
    \x07<\x04\x12\x03x\x08\x10\n\n\n\x03\x07<\x05\x12\x03x\x11\x17\n\n\n\x03\
    \x07<\x01\x12\x03x\x18\"\n\n\n\x03\x07<\x03\x12\x03x%*\n\t\n\x02\x07=\
    \x12\x03y\x08(\n\n\n\x03\x07=\x02\x12\x03t\x07#\n\n\n\x03\x07=\x04\x12\
    \x03y\x08\x10\n\n\n\x03\x07=\x05\x12\x03y\x11\x17\n\n\n\x03\x07=\x01\x12\
    \x03y\x18\x1f\n\n\n\x03\x07=\x03\x12\x03y\"'\n\t\n\x02\x07>\x12\x03z\x08\
    )\n\n\n\x03\x07>\x02\x12\x03t\x07#\n\n\n\x03\x07>\x04\x12\x03z\x08\x10\n\
    \n\n\x03\x07>\x05\x12\x03z\x11\x17\n\n\n\x03\x07>\x01\x12\x03z\x18\x20\n\
    \n\n\x03\x07>\x03\x12\x03z#(\n\t\n\x02\x07?\x12\x03{\x08)\n\n\n\x03\x07?\
    \x02\x12\x03t\x07#\n\n\n\x03\x07?\x04\x12\x03{\x08\x10\n\n\n\x03\x07?\
    \x05\x12\x03{\x11\x17\n\n\n\x03\x07?\x01\x12\x03{\x18\x20\n\n\n\x03\x07?\
    \x03\x12\x03{#(\n\t\n\x02\x07@\x12\x03|\x08(\n\n\n\x03\x07@\x02\x12\x03t\
    \x07#\n\n\n\x03\x07@\x04\x12\x03|\x08\x10\n\n\n\x03\x07@\x05\x12\x03|\
    \x11\x17\n\n\n\x03\x07@\x01\x12\x03|\x18\x1f\n\n\n\x03\x07@\x03\x12\x03|\
    \"'\n\t\n\x02\x07A\x12\x03}\x08*\n\n\n\x03\x07A\x02\x12\x03t\x07#\n\n\n\
    \x03\x07A\x04\x12\x03}\x08\x10\n\n\n\x03\x07A\x05\x12\x03}\x11\x17\n\n\n\
    \x03\x07A\x01\x12\x03}\x18!\n\n\n\x03\x07A\x03\x12\x03}$)\n\t\n\x02\x07B\
    \x12\x03\x7f\x08&\n\n\n\x03\x07B\x02\x12\x03t\x07#\n\n\n\x03\x07B\x04\
    \x12\x03\x7f\x08\x10\n\n\n\x03\x07B\x05\x12\x03\x7f\x11\x15\n\n\n\x03\
    \x07B\x01\x12\x03\x7f\x16\x1d\n\n\n\x03\x07B\x03\x12\x03\x7f\x20%\n\n\n\
    \x02\x07C\x12\x04\x80\x01\x08*\n\n\n\x03\x07C\x02\x12\x03t\x07#\n\x0b\n\
    \x03\x07C\x04\x12\x04\x80\x01\x08\x10\n\x0b\n\x03\x07C\x05\x12\x04\x80\
    \x01\x11\x15\n\x0b\n\x03\x07C\x01\x12\x04\x80\x01\x16!\n\x0b\n\x03\x07C\
    \x03\x12\x04\x80\x01$)\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
