// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct HttpUri {
    // message fields
    pub uri: ::std::string::String,
    pub timeout: ::protobuf::SingularPtrField<::protobuf::well_known_types::Duration>,
    // message oneof groups
    pub http_upstream_type: ::std::option::Option<HttpUri_oneof_http_upstream_type>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

#[derive(Clone,PartialEq)]
pub enum HttpUri_oneof_http_upstream_type {
    cluster(::std::string::String),
}

impl HttpUri {
    pub fn new() -> HttpUri {
        ::std::default::Default::default()
    }

    // string uri = 1;

    pub fn clear_uri(&mut self) {
        self.uri.clear();
    }

    // Param is passed by value, moved
    pub fn set_uri(&mut self, v: ::std::string::String) {
        self.uri = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_uri(&mut self) -> &mut ::std::string::String {
        &mut self.uri
    }

    // Take field
    pub fn take_uri(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.uri, ::std::string::String::new())
    }

    pub fn get_uri(&self) -> &str {
        &self.uri
    }

    // string cluster = 2;

    pub fn clear_cluster(&mut self) {
        self.http_upstream_type = ::std::option::Option::None;
    }

    pub fn has_cluster(&self) -> bool {
        match self.http_upstream_type {
            ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_cluster(&mut self, v: ::std::string::String) {
        self.http_upstream_type = ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(v))
    }

    // Mutable pointer to the field.
    pub fn mut_cluster(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(_)) = self.http_upstream_type {
        } else {
            self.http_upstream_type = ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(::std::string::String::new()));
        }
        match self.http_upstream_type {
            ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_cluster(&mut self) -> ::std::string::String {
        if self.has_cluster() {
            match self.http_upstream_type.take() {
                ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    pub fn get_cluster(&self) -> &str {
        match self.http_upstream_type {
            ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(ref v)) => v,
            _ => "",
        }
    }

    // .google.protobuf.Duration timeout = 3;

    pub fn clear_timeout(&mut self) {
        self.timeout.clear();
    }

    pub fn has_timeout(&self) -> bool {
        self.timeout.is_some()
    }

    // Param is passed by value, moved
    pub fn set_timeout(&mut self, v: ::protobuf::well_known_types::Duration) {
        self.timeout = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_timeout(&mut self) -> &mut ::protobuf::well_known_types::Duration {
        if self.timeout.is_none() {
            self.timeout.set_default();
        }
        self.timeout.as_mut().unwrap()
    }

    // Take field
    pub fn take_timeout(&mut self) -> ::protobuf::well_known_types::Duration {
        self.timeout.take().unwrap_or_else(|| ::protobuf::well_known_types::Duration::new())
    }

    pub fn get_timeout(&self) -> &::protobuf::well_known_types::Duration {
        self.timeout.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Duration::default_instance())
    }
}

impl ::protobuf::Message for HttpUri {
    fn is_initialized(&self) -> bool {
        for v in &self.timeout {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.uri)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.http_upstream_type = ::std::option::Option::Some(HttpUri_oneof_http_upstream_type::cluster(is.read_string()?));
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.timeout)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.uri.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.uri);
        }
        if let Some(ref v) = self.timeout.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let ::std::option::Option::Some(ref v) = self.http_upstream_type {
            match v {
                &HttpUri_oneof_http_upstream_type::cluster(ref v) => {
                    my_size += ::protobuf::rt::string_size(2, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.uri.is_empty() {
            os.write_string(1, &self.uri)?;
        }
        if let Some(ref v) = self.timeout.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let ::std::option::Option::Some(ref v) = self.http_upstream_type {
            match v {
                &HttpUri_oneof_http_upstream_type::cluster(ref v) => {
                    os.write_string(2, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HttpUri {
        HttpUri::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "uri",
                    |m: &HttpUri| { &m.uri },
                    |m: &mut HttpUri| { &mut m.uri },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_string_accessor::<_>(
                    "cluster",
                    HttpUri::has_cluster,
                    HttpUri::get_cluster,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Duration>>(
                    "timeout",
                    |m: &HttpUri| { &m.timeout },
                    |m: &mut HttpUri| { &mut m.timeout },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<HttpUri>(
                    "HttpUri",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static HttpUri {
        static mut instance: ::protobuf::lazy::Lazy<HttpUri> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const HttpUri,
        };
        unsafe {
            instance.get(HttpUri::new)
        }
    }
}

impl ::protobuf::Clear for HttpUri {
    fn clear(&mut self) {
        self.clear_uri();
        self.clear_cluster();
        self.clear_timeout();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HttpUri {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HttpUri {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20envoy/api/v2/core/http_uri.proto\x12\x11envoy.api.v2.core\x1a\x1eg\
    oogle/protobuf/duration.proto\x1a\x14gogoproto/gogo.proto\x1a\x17validat\
    e/validate.proto\"\xb9\x01\n\x07HttpUri\x12\x1b\n\x03uri\x18\x01\x20\x01\
    (\tR\x03uriB\t\xba\xe9\xc0\x03\x04r\x02\x20\x01\x12%\n\x07cluster\x18\
    \x02\x20\x01(\tH\0R\x07clusterB\t\xba\xe9\xc0\x03\x04r\x02\x20\x01\x12M\
    \n\x07timeout\x18\x03\x20\x01(\x0b2\x19.google.protobuf.DurationR\x07tim\
    eoutB\x18\xba\xe9\xc0\x03\x05\xaa\x01\x022\0\xba\xe9\xc0\x03\x05\xaa\x01\
    \x02\x08\x01\x98\xdf\x1f\x01B\x1b\n\x12http_upstream_type\x12\x05\xb8\
    \xe9\xc0\x03\x01B1\n\x1fio.envoyproxy.envoy.api.v2.coreB\x0cHttpUriProto\
    P\x01J\x84\n\n\x06\x12\x04\0\03\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\
    \x08\n\x01\x02\x12\x03\x02\x08\x19\n\x08\n\x01\x08\x12\x03\x04\0-\n\t\n\
    \x02\x08\x08\x12\x03\x04\0-\n\x08\n\x01\x08\x12\x03\x05\0\"\n\t\n\x02\
    \x08\n\x12\x03\x05\0\"\n\x08\n\x01\x08\x12\x03\x06\08\n\t\n\x02\x08\x01\
    \x12\x03\x06\08\n\t\n\x02\x03\0\x12\x03\x08\x07'\n\t\n\x02\x03\x01\x12\
    \x03\t\x07\x1d\n\t\n\x02\x03\x02\x12\x03\x0b\x07\x20\nS\n\x02\x04\0\x12\
    \x04\x10\03\x01\x1a\x1f\x20Envoy\x20external\x20URI\x20descriptor\n2&\
    \x20[#protodoc-title:\x20HTTP\x20Service\x20URI\x20]\n\n\n\n\x03\x04\0\
    \x01\x12\x03\x10\x08\x0f\n\xb3\x01\n\x04\x04\0\x02\0\x12\x03\x19\x029\
    \x1a\xa5\x01\x20The\x20HTTP\x20server\x20URI.\x20It\x20should\x20be\x20a\
    \x20full\x20FQDN\x20with\x20protocol,\x20host\x20and\x20path.\n\n\x20Exa\
    mple:\n\n\x20..\x20code-block::\x20yaml\n\n\x20\x20\x20\x20uri:\x20https\
    ://www.googleapis.com/oauth2/v1/certs\n\n\n\r\n\x05\x04\0\x02\0\x04\x12\
    \x04\x19\x02\x10\x11\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x19\x02\x08\n\
    \x0c\n\x05\x04\0\x02\0\x01\x12\x03\x19\t\x0c\n\x0c\n\x05\x04\0\x02\0\x03\
    \x12\x03\x19\x0f\x10\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03\x19\x118\n\x11\
    \n\n\x04\0\x02\0\x08\x97\x8d8\x0e\x04\x12\x03\x19\x127\n\xf5\x01\n\x04\
    \x04\0\x08\0\x12\x04\x1f\x02+\x03\x1a\xe6\x01\x20Specify\x20how\x20`uri`\
    \x20is\x20to\x20be\x20fetched.\x20Today,\x20this\x20requires\x20an\x20ex\
    plicit\n\x20cluster,\x20but\x20in\x20the\x20future\x20we\x20may\x20suppo\
    rt\x20dynamic\x20cluster\x20creation\x20or\n\x20inline\x20DNS\x20resolut\
    ion.\x20See\x20`issue\n\x20<https://github.com/envoyproxy/envoy/issues/1\
    606>`_.\n\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\x1f\x08\x1a\n\x0c\n\x05\
    \x04\0\x08\0\x02\x12\x03\x20\x04&\n\x0f\n\x08\x04\0\x08\0\x02\x97\x8d8\
    \x12\x03\x20\x04&\n\xb9\x01\n\x04\x04\0\x02\x01\x12\x03*\x04?\x1a\xab\
    \x01\x20A\x20cluster\x20is\x20created\x20in\x20the\x20Envoy\x20\"cluster\
    _manager\"\x20config\n\x20section.\x20This\x20field\x20specifies\x20the\
    \x20cluster\x20name.\n\n\x20Example:\n\n\x20..\x20code-block::\x20yaml\n\
    \n\x20\x20\x20\x20cluster:\x20jwks_cluster\n\n\n\x0c\n\x05\x04\0\x02\x01\
    \x05\x12\x03*\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03*\x0b\x12\n\x0c\
    \n\x05\x04\0\x02\x01\x03\x12\x03*\x15\x16\n\x0c\n\x05\x04\0\x02\x01\x08\
    \x12\x03*\x17>\n\x11\n\n\x04\0\x02\x01\x08\x97\x8d8\x0e\x04\x12\x03*\x18\
    =\nj\n\x04\x04\0\x02\x02\x12\x04.\x022\x04\x1a\\\x20Sets\x20the\x20maxim\
    um\x20duration\x20in\x20milliseconds\x20that\x20a\x20response\x20can\x20\
    take\x20to\x20arrive\x20upon\x20request.\n\n\r\n\x05\x04\0\x02\x02\x04\
    \x12\x04.\x02+\x03\n\x0c\n\x05\x04\0\x02\x02\x06\x12\x03.\x02\x1a\n\x0c\
    \n\x05\x04\0\x02\x02\x01\x12\x03.\x1b\"\n\x0c\n\x05\x04\0\x02\x02\x03\
    \x12\x03.%&\n\r\n\x05\x04\0\x02\x02\x08\x12\x04.'2\x03\n\x11\n\n\x04\0\
    \x02\x02\x08\x97\x8d8\x15\x06\x12\x03/\x04&\n\x11\n\n\x04\0\x02\x02\x08\
    \x97\x8d8\x15\x01\x12\x030\x04-\n\x0f\n\x08\x04\0\x02\x02\x08\xf3\xfb\
    \x03\x12\x031\x04\"b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
