// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Filter {
    // message fields
    pub name: ::std::string::String,
    // message oneof groups
    pub config_type: ::std::option::Option<Filter_oneof_config_type>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

#[derive(Clone,PartialEq)]
pub enum Filter_oneof_config_type {
    config(::protobuf::well_known_types::Struct),
    typed_config(::protobuf::well_known_types::Any),
}

impl Filter {
    pub fn new() -> Filter {
        ::std::default::Default::default()
    }

    // string name = 1;

    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    pub fn get_name(&self) -> &str {
        &self.name
    }

    // .google.protobuf.Struct config = 2;

    pub fn clear_config(&mut self) {
        self.config_type = ::std::option::Option::None;
    }

    pub fn has_config(&self) -> bool {
        match self.config_type {
            ::std::option::Option::Some(Filter_oneof_config_type::config(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_config(&mut self, v: ::protobuf::well_known_types::Struct) {
        self.config_type = ::std::option::Option::Some(Filter_oneof_config_type::config(v))
    }

    // Mutable pointer to the field.
    pub fn mut_config(&mut self) -> &mut ::protobuf::well_known_types::Struct {
        if let ::std::option::Option::Some(Filter_oneof_config_type::config(_)) = self.config_type {
        } else {
            self.config_type = ::std::option::Option::Some(Filter_oneof_config_type::config(::protobuf::well_known_types::Struct::new()));
        }
        match self.config_type {
            ::std::option::Option::Some(Filter_oneof_config_type::config(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_config(&mut self) -> ::protobuf::well_known_types::Struct {
        if self.has_config() {
            match self.config_type.take() {
                ::std::option::Option::Some(Filter_oneof_config_type::config(v)) => v,
                _ => panic!(),
            }
        } else {
            ::protobuf::well_known_types::Struct::new()
        }
    }

    pub fn get_config(&self) -> &::protobuf::well_known_types::Struct {
        match self.config_type {
            ::std::option::Option::Some(Filter_oneof_config_type::config(ref v)) => v,
            _ => ::protobuf::well_known_types::Struct::default_instance(),
        }
    }

    // .google.protobuf.Any typed_config = 4;

    pub fn clear_typed_config(&mut self) {
        self.config_type = ::std::option::Option::None;
    }

    pub fn has_typed_config(&self) -> bool {
        match self.config_type {
            ::std::option::Option::Some(Filter_oneof_config_type::typed_config(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_typed_config(&mut self, v: ::protobuf::well_known_types::Any) {
        self.config_type = ::std::option::Option::Some(Filter_oneof_config_type::typed_config(v))
    }

    // Mutable pointer to the field.
    pub fn mut_typed_config(&mut self) -> &mut ::protobuf::well_known_types::Any {
        if let ::std::option::Option::Some(Filter_oneof_config_type::typed_config(_)) = self.config_type {
        } else {
            self.config_type = ::std::option::Option::Some(Filter_oneof_config_type::typed_config(::protobuf::well_known_types::Any::new()));
        }
        match self.config_type {
            ::std::option::Option::Some(Filter_oneof_config_type::typed_config(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_typed_config(&mut self) -> ::protobuf::well_known_types::Any {
        if self.has_typed_config() {
            match self.config_type.take() {
                ::std::option::Option::Some(Filter_oneof_config_type::typed_config(v)) => v,
                _ => panic!(),
            }
        } else {
            ::protobuf::well_known_types::Any::new()
        }
    }

    pub fn get_typed_config(&self) -> &::protobuf::well_known_types::Any {
        match self.config_type {
            ::std::option::Option::Some(Filter_oneof_config_type::typed_config(ref v)) => v,
            _ => ::protobuf::well_known_types::Any::default_instance(),
        }
    }
}

impl ::protobuf::Message for Filter {
    fn is_initialized(&self) -> bool {
        if let Some(Filter_oneof_config_type::config(ref v)) = self.config_type {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Filter_oneof_config_type::typed_config(ref v)) = self.config_type {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.config_type = ::std::option::Option::Some(Filter_oneof_config_type::config(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.config_type = ::std::option::Option::Some(Filter_oneof_config_type::typed_config(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if let ::std::option::Option::Some(ref v) = self.config_type {
            match v {
                &Filter_oneof_config_type::config(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Filter_oneof_config_type::typed_config(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if let ::std::option::Option::Some(ref v) = self.config_type {
            match v {
                &Filter_oneof_config_type::config(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Filter_oneof_config_type::typed_config(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Filter {
        Filter::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "name",
                    |m: &Filter| { &m.name },
                    |m: &mut Filter| { &mut m.name },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ::protobuf::well_known_types::Struct>(
                    "config",
                    Filter::has_config,
                    Filter::get_config,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ::protobuf::well_known_types::Any>(
                    "typed_config",
                    Filter::has_typed_config,
                    Filter::get_typed_config,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Filter>(
                    "Filter",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Filter {
        static mut instance: ::protobuf::lazy::Lazy<Filter> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Filter,
        };
        unsafe {
            instance.get(Filter::new)
        }
    }
}

impl ::protobuf::Clear for Filter {
    fn clear(&mut self) {
        self.clear_name();
        self.clear_config();
        self.clear_typed_config();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Filter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Filter {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct FilterChainMatch {
    // message fields
    pub destination_port: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub prefix_ranges: ::protobuf::RepeatedField<super::address::CidrRange>,
    pub address_suffix: ::std::string::String,
    pub suffix_len: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub source_type: FilterChainMatch_ConnectionSourceType,
    pub source_prefix_ranges: ::protobuf::RepeatedField<super::address::CidrRange>,
    pub source_ports: ::protobuf::RepeatedField<::protobuf::well_known_types::UInt32Value>,
    pub server_names: ::protobuf::RepeatedField<::std::string::String>,
    pub transport_protocol: ::std::string::String,
    pub application_protocols: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl FilterChainMatch {
    pub fn new() -> FilterChainMatch {
        ::std::default::Default::default()
    }

    // .google.protobuf.UInt32Value destination_port = 8;

    pub fn clear_destination_port(&mut self) {
        self.destination_port.clear();
    }

    pub fn has_destination_port(&self) -> bool {
        self.destination_port.is_some()
    }

    // Param is passed by value, moved
    pub fn set_destination_port(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.destination_port = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_destination_port(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.destination_port.is_none() {
            self.destination_port.set_default();
        }
        self.destination_port.as_mut().unwrap()
    }

    // Take field
    pub fn take_destination_port(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.destination_port.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_destination_port(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.destination_port.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // repeated .envoy.api.v2.core.CidrRange prefix_ranges = 3;

    pub fn clear_prefix_ranges(&mut self) {
        self.prefix_ranges.clear();
    }

    // Param is passed by value, moved
    pub fn set_prefix_ranges(&mut self, v: ::protobuf::RepeatedField<super::address::CidrRange>) {
        self.prefix_ranges = v;
    }

    // Mutable pointer to the field.
    pub fn mut_prefix_ranges(&mut self) -> &mut ::protobuf::RepeatedField<super::address::CidrRange> {
        &mut self.prefix_ranges
    }

    // Take field
    pub fn take_prefix_ranges(&mut self) -> ::protobuf::RepeatedField<super::address::CidrRange> {
        ::std::mem::replace(&mut self.prefix_ranges, ::protobuf::RepeatedField::new())
    }

    pub fn get_prefix_ranges(&self) -> &[super::address::CidrRange] {
        &self.prefix_ranges
    }

    // string address_suffix = 4;

    pub fn clear_address_suffix(&mut self) {
        self.address_suffix.clear();
    }

    // Param is passed by value, moved
    pub fn set_address_suffix(&mut self, v: ::std::string::String) {
        self.address_suffix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address_suffix(&mut self) -> &mut ::std::string::String {
        &mut self.address_suffix
    }

    // Take field
    pub fn take_address_suffix(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.address_suffix, ::std::string::String::new())
    }

    pub fn get_address_suffix(&self) -> &str {
        &self.address_suffix
    }

    // .google.protobuf.UInt32Value suffix_len = 5;

    pub fn clear_suffix_len(&mut self) {
        self.suffix_len.clear();
    }

    pub fn has_suffix_len(&self) -> bool {
        self.suffix_len.is_some()
    }

    // Param is passed by value, moved
    pub fn set_suffix_len(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.suffix_len = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_suffix_len(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.suffix_len.is_none() {
            self.suffix_len.set_default();
        }
        self.suffix_len.as_mut().unwrap()
    }

    // Take field
    pub fn take_suffix_len(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.suffix_len.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_suffix_len(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.suffix_len.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // .envoy.api.v2.listener.FilterChainMatch.ConnectionSourceType source_type = 12;

    pub fn clear_source_type(&mut self) {
        self.source_type = FilterChainMatch_ConnectionSourceType::ANY;
    }

    // Param is passed by value, moved
    pub fn set_source_type(&mut self, v: FilterChainMatch_ConnectionSourceType) {
        self.source_type = v;
    }

    pub fn get_source_type(&self) -> FilterChainMatch_ConnectionSourceType {
        self.source_type
    }

    // repeated .envoy.api.v2.core.CidrRange source_prefix_ranges = 6;

    pub fn clear_source_prefix_ranges(&mut self) {
        self.source_prefix_ranges.clear();
    }

    // Param is passed by value, moved
    pub fn set_source_prefix_ranges(&mut self, v: ::protobuf::RepeatedField<super::address::CidrRange>) {
        self.source_prefix_ranges = v;
    }

    // Mutable pointer to the field.
    pub fn mut_source_prefix_ranges(&mut self) -> &mut ::protobuf::RepeatedField<super::address::CidrRange> {
        &mut self.source_prefix_ranges
    }

    // Take field
    pub fn take_source_prefix_ranges(&mut self) -> ::protobuf::RepeatedField<super::address::CidrRange> {
        ::std::mem::replace(&mut self.source_prefix_ranges, ::protobuf::RepeatedField::new())
    }

    pub fn get_source_prefix_ranges(&self) -> &[super::address::CidrRange] {
        &self.source_prefix_ranges
    }

    // repeated .google.protobuf.UInt32Value source_ports = 7;

    pub fn clear_source_ports(&mut self) {
        self.source_ports.clear();
    }

    // Param is passed by value, moved
    pub fn set_source_ports(&mut self, v: ::protobuf::RepeatedField<::protobuf::well_known_types::UInt32Value>) {
        self.source_ports = v;
    }

    // Mutable pointer to the field.
    pub fn mut_source_ports(&mut self) -> &mut ::protobuf::RepeatedField<::protobuf::well_known_types::UInt32Value> {
        &mut self.source_ports
    }

    // Take field
    pub fn take_source_ports(&mut self) -> ::protobuf::RepeatedField<::protobuf::well_known_types::UInt32Value> {
        ::std::mem::replace(&mut self.source_ports, ::protobuf::RepeatedField::new())
    }

    pub fn get_source_ports(&self) -> &[::protobuf::well_known_types::UInt32Value] {
        &self.source_ports
    }

    // repeated string server_names = 11;

    pub fn clear_server_names(&mut self) {
        self.server_names.clear();
    }

    // Param is passed by value, moved
    pub fn set_server_names(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.server_names = v;
    }

    // Mutable pointer to the field.
    pub fn mut_server_names(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.server_names
    }

    // Take field
    pub fn take_server_names(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.server_names, ::protobuf::RepeatedField::new())
    }

    pub fn get_server_names(&self) -> &[::std::string::String] {
        &self.server_names
    }

    // string transport_protocol = 9;

    pub fn clear_transport_protocol(&mut self) {
        self.transport_protocol.clear();
    }

    // Param is passed by value, moved
    pub fn set_transport_protocol(&mut self, v: ::std::string::String) {
        self.transport_protocol = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_transport_protocol(&mut self) -> &mut ::std::string::String {
        &mut self.transport_protocol
    }

    // Take field
    pub fn take_transport_protocol(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.transport_protocol, ::std::string::String::new())
    }

    pub fn get_transport_protocol(&self) -> &str {
        &self.transport_protocol
    }

    // repeated string application_protocols = 10;

    pub fn clear_application_protocols(&mut self) {
        self.application_protocols.clear();
    }

    // Param is passed by value, moved
    pub fn set_application_protocols(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.application_protocols = v;
    }

    // Mutable pointer to the field.
    pub fn mut_application_protocols(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.application_protocols
    }

    // Take field
    pub fn take_application_protocols(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.application_protocols, ::protobuf::RepeatedField::new())
    }

    pub fn get_application_protocols(&self) -> &[::std::string::String] {
        &self.application_protocols
    }
}

impl ::protobuf::Message for FilterChainMatch {
    fn is_initialized(&self) -> bool {
        for v in &self.destination_port {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.prefix_ranges {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.suffix_len {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.source_prefix_ranges {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.source_ports {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                8 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.destination_port)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.prefix_ranges)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.address_suffix)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.suffix_len)?;
                },
                12 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.source_type, 12, &mut self.unknown_fields)?
                },
                6 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.source_prefix_ranges)?;
                },
                7 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.source_ports)?;
                },
                11 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.server_names)?;
                },
                9 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.transport_protocol)?;
                },
                10 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.application_protocols)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.destination_port.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.prefix_ranges {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if !self.address_suffix.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.address_suffix);
        }
        if let Some(ref v) = self.suffix_len.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.source_type != FilterChainMatch_ConnectionSourceType::ANY {
            my_size += ::protobuf::rt::enum_size(12, self.source_type);
        }
        for value in &self.source_prefix_ranges {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.source_ports {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.server_names {
            my_size += ::protobuf::rt::string_size(11, &value);
        };
        if !self.transport_protocol.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.transport_protocol);
        }
        for value in &self.application_protocols {
            my_size += ::protobuf::rt::string_size(10, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.destination_port.as_ref() {
            os.write_tag(8, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.prefix_ranges {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if !self.address_suffix.is_empty() {
            os.write_string(4, &self.address_suffix)?;
        }
        if let Some(ref v) = self.suffix_len.as_ref() {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.source_type != FilterChainMatch_ConnectionSourceType::ANY {
            os.write_enum(12, self.source_type.value())?;
        }
        for v in &self.source_prefix_ranges {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.source_ports {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.server_names {
            os.write_string(11, &v)?;
        };
        if !self.transport_protocol.is_empty() {
            os.write_string(9, &self.transport_protocol)?;
        }
        for v in &self.application_protocols {
            os.write_string(10, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FilterChainMatch {
        FilterChainMatch::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "destination_port",
                    |m: &FilterChainMatch| { &m.destination_port },
                    |m: &mut FilterChainMatch| { &mut m.destination_port },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::address::CidrRange>>(
                    "prefix_ranges",
                    |m: &FilterChainMatch| { &m.prefix_ranges },
                    |m: &mut FilterChainMatch| { &mut m.prefix_ranges },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "address_suffix",
                    |m: &FilterChainMatch| { &m.address_suffix },
                    |m: &mut FilterChainMatch| { &mut m.address_suffix },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "suffix_len",
                    |m: &FilterChainMatch| { &m.suffix_len },
                    |m: &mut FilterChainMatch| { &mut m.suffix_len },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<FilterChainMatch_ConnectionSourceType>>(
                    "source_type",
                    |m: &FilterChainMatch| { &m.source_type },
                    |m: &mut FilterChainMatch| { &mut m.source_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::address::CidrRange>>(
                    "source_prefix_ranges",
                    |m: &FilterChainMatch| { &m.source_prefix_ranges },
                    |m: &mut FilterChainMatch| { &mut m.source_prefix_ranges },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "source_ports",
                    |m: &FilterChainMatch| { &m.source_ports },
                    |m: &mut FilterChainMatch| { &mut m.source_ports },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "server_names",
                    |m: &FilterChainMatch| { &m.server_names },
                    |m: &mut FilterChainMatch| { &mut m.server_names },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "transport_protocol",
                    |m: &FilterChainMatch| { &m.transport_protocol },
                    |m: &mut FilterChainMatch| { &mut m.transport_protocol },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "application_protocols",
                    |m: &FilterChainMatch| { &m.application_protocols },
                    |m: &mut FilterChainMatch| { &mut m.application_protocols },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<FilterChainMatch>(
                    "FilterChainMatch",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static FilterChainMatch {
        static mut instance: ::protobuf::lazy::Lazy<FilterChainMatch> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const FilterChainMatch,
        };
        unsafe {
            instance.get(FilterChainMatch::new)
        }
    }
}

impl ::protobuf::Clear for FilterChainMatch {
    fn clear(&mut self) {
        self.clear_destination_port();
        self.clear_prefix_ranges();
        self.clear_address_suffix();
        self.clear_suffix_len();
        self.clear_source_type();
        self.clear_source_prefix_ranges();
        self.clear_source_ports();
        self.clear_server_names();
        self.clear_transport_protocol();
        self.clear_application_protocols();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FilterChainMatch {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FilterChainMatch {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum FilterChainMatch_ConnectionSourceType {
    ANY = 0,
    LOCAL = 1,
    EXTERNAL = 2,
}

impl ::protobuf::ProtobufEnum for FilterChainMatch_ConnectionSourceType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FilterChainMatch_ConnectionSourceType> {
        match value {
            0 => ::std::option::Option::Some(FilterChainMatch_ConnectionSourceType::ANY),
            1 => ::std::option::Option::Some(FilterChainMatch_ConnectionSourceType::LOCAL),
            2 => ::std::option::Option::Some(FilterChainMatch_ConnectionSourceType::EXTERNAL),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [FilterChainMatch_ConnectionSourceType] = &[
            FilterChainMatch_ConnectionSourceType::ANY,
            FilterChainMatch_ConnectionSourceType::LOCAL,
            FilterChainMatch_ConnectionSourceType::EXTERNAL,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("FilterChainMatch_ConnectionSourceType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for FilterChainMatch_ConnectionSourceType {
}

impl ::std::default::Default for FilterChainMatch_ConnectionSourceType {
    fn default() -> Self {
        FilterChainMatch_ConnectionSourceType::ANY
    }
}

impl ::protobuf::reflect::ProtobufValue for FilterChainMatch_ConnectionSourceType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct FilterChain {
    // message fields
    pub filter_chain_match: ::protobuf::SingularPtrField<FilterChainMatch>,
    pub tls_context: ::protobuf::SingularPtrField<super::cert::DownstreamTlsContext>,
    pub filters: ::protobuf::RepeatedField<Filter>,
    pub use_proxy_proto: ::protobuf::SingularPtrField<::protobuf::well_known_types::BoolValue>,
    pub metadata: ::protobuf::SingularPtrField<super::base::Metadata>,
    pub transport_socket: ::protobuf::SingularPtrField<super::base::TransportSocket>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl FilterChain {
    pub fn new() -> FilterChain {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.listener.FilterChainMatch filter_chain_match = 1;

    pub fn clear_filter_chain_match(&mut self) {
        self.filter_chain_match.clear();
    }

    pub fn has_filter_chain_match(&self) -> bool {
        self.filter_chain_match.is_some()
    }

    // Param is passed by value, moved
    pub fn set_filter_chain_match(&mut self, v: FilterChainMatch) {
        self.filter_chain_match = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filter_chain_match(&mut self) -> &mut FilterChainMatch {
        if self.filter_chain_match.is_none() {
            self.filter_chain_match.set_default();
        }
        self.filter_chain_match.as_mut().unwrap()
    }

    // Take field
    pub fn take_filter_chain_match(&mut self) -> FilterChainMatch {
        self.filter_chain_match.take().unwrap_or_else(|| FilterChainMatch::new())
    }

    pub fn get_filter_chain_match(&self) -> &FilterChainMatch {
        self.filter_chain_match.as_ref().unwrap_or_else(|| FilterChainMatch::default_instance())
    }

    // .envoy.api.v2.auth.DownstreamTlsContext tls_context = 2;

    pub fn clear_tls_context(&mut self) {
        self.tls_context.clear();
    }

    pub fn has_tls_context(&self) -> bool {
        self.tls_context.is_some()
    }

    // Param is passed by value, moved
    pub fn set_tls_context(&mut self, v: super::cert::DownstreamTlsContext) {
        self.tls_context = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tls_context(&mut self) -> &mut super::cert::DownstreamTlsContext {
        if self.tls_context.is_none() {
            self.tls_context.set_default();
        }
        self.tls_context.as_mut().unwrap()
    }

    // Take field
    pub fn take_tls_context(&mut self) -> super::cert::DownstreamTlsContext {
        self.tls_context.take().unwrap_or_else(|| super::cert::DownstreamTlsContext::new())
    }

    pub fn get_tls_context(&self) -> &super::cert::DownstreamTlsContext {
        self.tls_context.as_ref().unwrap_or_else(|| super::cert::DownstreamTlsContext::default_instance())
    }

    // repeated .envoy.api.v2.listener.Filter filters = 3;

    pub fn clear_filters(&mut self) {
        self.filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_filters(&mut self, v: ::protobuf::RepeatedField<Filter>) {
        self.filters = v;
    }

    // Mutable pointer to the field.
    pub fn mut_filters(&mut self) -> &mut ::protobuf::RepeatedField<Filter> {
        &mut self.filters
    }

    // Take field
    pub fn take_filters(&mut self) -> ::protobuf::RepeatedField<Filter> {
        ::std::mem::replace(&mut self.filters, ::protobuf::RepeatedField::new())
    }

    pub fn get_filters(&self) -> &[Filter] {
        &self.filters
    }

    // .google.protobuf.BoolValue use_proxy_proto = 4;

    pub fn clear_use_proxy_proto(&mut self) {
        self.use_proxy_proto.clear();
    }

    pub fn has_use_proxy_proto(&self) -> bool {
        self.use_proxy_proto.is_some()
    }

    // Param is passed by value, moved
    pub fn set_use_proxy_proto(&mut self, v: ::protobuf::well_known_types::BoolValue) {
        self.use_proxy_proto = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_use_proxy_proto(&mut self) -> &mut ::protobuf::well_known_types::BoolValue {
        if self.use_proxy_proto.is_none() {
            self.use_proxy_proto.set_default();
        }
        self.use_proxy_proto.as_mut().unwrap()
    }

    // Take field
    pub fn take_use_proxy_proto(&mut self) -> ::protobuf::well_known_types::BoolValue {
        self.use_proxy_proto.take().unwrap_or_else(|| ::protobuf::well_known_types::BoolValue::new())
    }

    pub fn get_use_proxy_proto(&self) -> &::protobuf::well_known_types::BoolValue {
        self.use_proxy_proto.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::BoolValue::default_instance())
    }

    // .envoy.api.v2.core.Metadata metadata = 5;

    pub fn clear_metadata(&mut self) {
        self.metadata.clear();
    }

    pub fn has_metadata(&self) -> bool {
        self.metadata.is_some()
    }

    // Param is passed by value, moved
    pub fn set_metadata(&mut self, v: super::base::Metadata) {
        self.metadata = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_metadata(&mut self) -> &mut super::base::Metadata {
        if self.metadata.is_none() {
            self.metadata.set_default();
        }
        self.metadata.as_mut().unwrap()
    }

    // Take field
    pub fn take_metadata(&mut self) -> super::base::Metadata {
        self.metadata.take().unwrap_or_else(|| super::base::Metadata::new())
    }

    pub fn get_metadata(&self) -> &super::base::Metadata {
        self.metadata.as_ref().unwrap_or_else(|| super::base::Metadata::default_instance())
    }

    // .envoy.api.v2.core.TransportSocket transport_socket = 6;

    pub fn clear_transport_socket(&mut self) {
        self.transport_socket.clear();
    }

    pub fn has_transport_socket(&self) -> bool {
        self.transport_socket.is_some()
    }

    // Param is passed by value, moved
    pub fn set_transport_socket(&mut self, v: super::base::TransportSocket) {
        self.transport_socket = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_transport_socket(&mut self) -> &mut super::base::TransportSocket {
        if self.transport_socket.is_none() {
            self.transport_socket.set_default();
        }
        self.transport_socket.as_mut().unwrap()
    }

    // Take field
    pub fn take_transport_socket(&mut self) -> super::base::TransportSocket {
        self.transport_socket.take().unwrap_or_else(|| super::base::TransportSocket::new())
    }

    pub fn get_transport_socket(&self) -> &super::base::TransportSocket {
        self.transport_socket.as_ref().unwrap_or_else(|| super::base::TransportSocket::default_instance())
    }
}

impl ::protobuf::Message for FilterChain {
    fn is_initialized(&self) -> bool {
        for v in &self.filter_chain_match {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.tls_context {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.filters {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.use_proxy_proto {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.metadata {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.transport_socket {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.filter_chain_match)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.tls_context)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.filters)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.use_proxy_proto)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.metadata)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.transport_socket)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.filter_chain_match.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.tls_context.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.filters {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if let Some(ref v) = self.use_proxy_proto.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.transport_socket.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.filter_chain_match.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.tls_context.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.filters {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if let Some(ref v) = self.use_proxy_proto.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.metadata.as_ref() {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.transport_socket.as_ref() {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FilterChain {
        FilterChain::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<FilterChainMatch>>(
                    "filter_chain_match",
                    |m: &FilterChain| { &m.filter_chain_match },
                    |m: &mut FilterChain| { &mut m.filter_chain_match },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::cert::DownstreamTlsContext>>(
                    "tls_context",
                    |m: &FilterChain| { &m.tls_context },
                    |m: &mut FilterChain| { &mut m.tls_context },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Filter>>(
                    "filters",
                    |m: &FilterChain| { &m.filters },
                    |m: &mut FilterChain| { &mut m.filters },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::BoolValue>>(
                    "use_proxy_proto",
                    |m: &FilterChain| { &m.use_proxy_proto },
                    |m: &mut FilterChain| { &mut m.use_proxy_proto },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::Metadata>>(
                    "metadata",
                    |m: &FilterChain| { &m.metadata },
                    |m: &mut FilterChain| { &mut m.metadata },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::TransportSocket>>(
                    "transport_socket",
                    |m: &FilterChain| { &m.transport_socket },
                    |m: &mut FilterChain| { &mut m.transport_socket },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<FilterChain>(
                    "FilterChain",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static FilterChain {
        static mut instance: ::protobuf::lazy::Lazy<FilterChain> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const FilterChain,
        };
        unsafe {
            instance.get(FilterChain::new)
        }
    }
}

impl ::protobuf::Clear for FilterChain {
    fn clear(&mut self) {
        self.clear_filter_chain_match();
        self.clear_tls_context();
        self.clear_filters();
        self.clear_use_proxy_proto();
        self.clear_metadata();
        self.clear_transport_socket();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FilterChain {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FilterChain {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ListenerFilter {
    // message fields
    pub name: ::std::string::String,
    // message oneof groups
    pub config_type: ::std::option::Option<ListenerFilter_oneof_config_type>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

#[derive(Clone,PartialEq)]
pub enum ListenerFilter_oneof_config_type {
    config(::protobuf::well_known_types::Struct),
    typed_config(::protobuf::well_known_types::Any),
}

impl ListenerFilter {
    pub fn new() -> ListenerFilter {
        ::std::default::Default::default()
    }

    // string name = 1;

    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    pub fn get_name(&self) -> &str {
        &self.name
    }

    // .google.protobuf.Struct config = 2;

    pub fn clear_config(&mut self) {
        self.config_type = ::std::option::Option::None;
    }

    pub fn has_config(&self) -> bool {
        match self.config_type {
            ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_config(&mut self, v: ::protobuf::well_known_types::Struct) {
        self.config_type = ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(v))
    }

    // Mutable pointer to the field.
    pub fn mut_config(&mut self) -> &mut ::protobuf::well_known_types::Struct {
        if let ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(_)) = self.config_type {
        } else {
            self.config_type = ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(::protobuf::well_known_types::Struct::new()));
        }
        match self.config_type {
            ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_config(&mut self) -> ::protobuf::well_known_types::Struct {
        if self.has_config() {
            match self.config_type.take() {
                ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(v)) => v,
                _ => panic!(),
            }
        } else {
            ::protobuf::well_known_types::Struct::new()
        }
    }

    pub fn get_config(&self) -> &::protobuf::well_known_types::Struct {
        match self.config_type {
            ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(ref v)) => v,
            _ => ::protobuf::well_known_types::Struct::default_instance(),
        }
    }

    // .google.protobuf.Any typed_config = 3;

    pub fn clear_typed_config(&mut self) {
        self.config_type = ::std::option::Option::None;
    }

    pub fn has_typed_config(&self) -> bool {
        match self.config_type {
            ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_typed_config(&mut self, v: ::protobuf::well_known_types::Any) {
        self.config_type = ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(v))
    }

    // Mutable pointer to the field.
    pub fn mut_typed_config(&mut self) -> &mut ::protobuf::well_known_types::Any {
        if let ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(_)) = self.config_type {
        } else {
            self.config_type = ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(::protobuf::well_known_types::Any::new()));
        }
        match self.config_type {
            ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_typed_config(&mut self) -> ::protobuf::well_known_types::Any {
        if self.has_typed_config() {
            match self.config_type.take() {
                ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(v)) => v,
                _ => panic!(),
            }
        } else {
            ::protobuf::well_known_types::Any::new()
        }
    }

    pub fn get_typed_config(&self) -> &::protobuf::well_known_types::Any {
        match self.config_type {
            ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(ref v)) => v,
            _ => ::protobuf::well_known_types::Any::default_instance(),
        }
    }
}

impl ::protobuf::Message for ListenerFilter {
    fn is_initialized(&self) -> bool {
        if let Some(ListenerFilter_oneof_config_type::config(ref v)) = self.config_type {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ListenerFilter_oneof_config_type::typed_config(ref v)) = self.config_type {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.config_type = ::std::option::Option::Some(ListenerFilter_oneof_config_type::config(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.config_type = ::std::option::Option::Some(ListenerFilter_oneof_config_type::typed_config(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if let ::std::option::Option::Some(ref v) = self.config_type {
            match v {
                &ListenerFilter_oneof_config_type::config(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ListenerFilter_oneof_config_type::typed_config(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if let ::std::option::Option::Some(ref v) = self.config_type {
            match v {
                &ListenerFilter_oneof_config_type::config(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ListenerFilter_oneof_config_type::typed_config(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ListenerFilter {
        ListenerFilter::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "name",
                    |m: &ListenerFilter| { &m.name },
                    |m: &mut ListenerFilter| { &mut m.name },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ::protobuf::well_known_types::Struct>(
                    "config",
                    ListenerFilter::has_config,
                    ListenerFilter::get_config,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ::protobuf::well_known_types::Any>(
                    "typed_config",
                    ListenerFilter::has_typed_config,
                    ListenerFilter::get_typed_config,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ListenerFilter>(
                    "ListenerFilter",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ListenerFilter {
        static mut instance: ::protobuf::lazy::Lazy<ListenerFilter> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ListenerFilter,
        };
        unsafe {
            instance.get(ListenerFilter::new)
        }
    }
}

impl ::protobuf::Clear for ListenerFilter {
    fn clear(&mut self) {
        self.clear_name();
        self.clear_config();
        self.clear_typed_config();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ListenerFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListenerFilter {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$envoy/api/v2/listener/listener.proto\x12\x15envoy.api.v2.listener\x1a\
    \x1fenvoy/api/v2/core/address.proto\x1a\x1cenvoy/api/v2/auth/cert.proto\
    \x1a\x1cenvoy/api/v2/core/base.proto\x1a\x19google/protobuf/any.proto\
    \x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.pro\
    to\x1a\x17validate/validate.proto\x1a\x14gogoproto/gogo.proto\"\xae\x01\
    \n\x06Filter\x12\x1d\n\x04name\x18\x01\x20\x01(\tR\x04nameB\t\xba\xe9\
    \xc0\x03\x04r\x02\x20\x01\x125\n\x06config\x18\x02\x20\x01(\x0b2\x17.goo\
    gle.protobuf.StructH\0R\x06configB\x02\x18\x01\x129\n\x0ctyped_config\
    \x18\x04\x20\x01(\x0b2\x14.google.protobuf.AnyH\0R\x0btypedConfigB\r\n\
    \x0bconfig_typeJ\x04\x08\x03\x10\x04\"\xe1\x05\n\x10FilterChainMatch\x12\
    V\n\x10destination_port\x18\x08\x20\x01(\x0b2\x1c.google.protobuf.UInt32\
    ValueR\x0fdestinationPortB\r\xba\xe9\xc0\x03\x08*\x06\x18\xff\xff\x03(\
    \x01\x12A\n\rprefix_ranges\x18\x03\x20\x03(\x0b2\x1c.envoy.api.v2.core.C\
    idrRangeR\x0cprefixRanges\x12%\n\x0eaddress_suffix\x18\x04\x20\x01(\tR\r\
    addressSuffix\x12;\n\nsuffix_len\x18\x05\x20\x01(\x0b2\x1c.google.protob\
    uf.UInt32ValueR\tsuffixLen\x12i\n\x0bsource_type\x18\x0c\x20\x01(\x0e2<.\
    envoy.api.v2.listener.FilterChainMatch.ConnectionSourceTypeR\nsourceType\
    B\n\xba\xe9\xc0\x03\x05\x82\x01\x02\x10\x01\x12N\n\x14source_prefix_rang\
    es\x18\x06\x20\x03(\x0b2\x1c.envoy.api.v2.core.CidrRangeR\x12sourcePrefi\
    xRanges\x12?\n\x0csource_ports\x18\x07\x20\x03(\x0b2\x1c.google.protobuf\
    .UInt32ValueR\x0bsourcePorts\x12!\n\x0cserver_names\x18\x0b\x20\x03(\tR\
    \x0bserverNames\x12-\n\x12transport_protocol\x18\t\x20\x01(\tR\x11transp\
    ortProtocol\x123\n\x15application_protocols\x18\n\x20\x03(\tR\x14applica\
    tionProtocols\"8\n\x14ConnectionSourceType\x12\x07\n\x03ANY\x10\0\x12\t\
    \n\x05LOCAL\x10\x01\x12\x0c\n\x08EXTERNAL\x10\x02J\x04\x08\x01\x10\x02R\
    \x0bsni_domains\"\xb9\x03\n\x0bFilterChain\x12U\n\x12filter_chain_match\
    \x18\x01\x20\x01(\x0b2'.envoy.api.v2.listener.FilterChainMatchR\x10filte\
    rChainMatch\x12H\n\x0btls_context\x18\x02\x20\x01(\x0b2'.envoy.api.v2.au\
    th.DownstreamTlsContextR\ntlsContext\x12=\n\x07filters\x18\x03\x20\x03(\
    \x0b2\x1d.envoy.api.v2.listener.FilterR\x07filtersB\x04\xc8\xde\x1f\0\
    \x12B\n\x0fuse_proxy_proto\x18\x04\x20\x01(\x0b2\x1a.google.protobuf.Boo\
    lValueR\ruseProxyProto\x127\n\x08metadata\x18\x05\x20\x01(\x0b2\x1b.envo\
    y.api.v2.core.MetadataR\x08metadata\x12M\n\x10transport_socket\x18\x06\
    \x20\x01(\x0b2\".envoy.api.v2.core.TransportSocketR\x0ftransportSocket\"\
    \xb0\x01\n\x0eListenerFilter\x12\x1d\n\x04name\x18\x01\x20\x01(\tR\x04na\
    meB\t\xba\xe9\xc0\x03\x04r\x02\x20\x01\x125\n\x06config\x18\x02\x20\x01(\
    \x0b2\x17.google.protobuf.StructH\0R\x06configB\x02\x18\x01\x129\n\x0cty\
    ped_config\x18\x03\x20\x01(\x0b2\x14.google.protobuf.AnyH\0R\x0btypedCon\
    figB\r\n\x0bconfig_typeB^\n#io.envoyproxy.envoy.api.v2.listenerB\rListen\
    erProtoP\x01Z\x08listener\xaa\x02\x17Envoy.Api.V2.ListenerNS\xa8\xe2\x1e\
    \x01J\xccH\n\x07\x12\x05\0\0\xd8\x01\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\
    \n\x08\n\x01\x02\x12\x03\x02\x08\x1d\n\x08\n\x01\x08\x12\x03\x04\0.\n\t\
    \n\x02\x08\x08\x12\x03\x04\0.\n\x08\n\x01\x08\x12\x03\x05\0\"\n\t\n\x02\
    \x08\n\x12\x03\x05\0\"\n\x08\n\x01\x08\x12\x03\x06\0<\n\t\n\x02\x08\x01\
    \x12\x03\x06\0<\n\x08\n\x01\x08\x12\x03\x07\0\x1f\n\t\n\x02\x08\x0b\x12\
    \x03\x07\0\x1f\n\x08\n\x01\x08\x12\x03\x08\04\n\t\n\x02\x08%\x12\x03\x08\
    \04\n\t\n\x02\x03\0\x12\x03\n\x07(\n\t\n\x02\x03\x01\x12\x03\x0b\x07%\n\
    \t\n\x02\x03\x02\x12\x03\x0c\x07%\n\t\n\x02\x03\x03\x12\x03\x0e\x07\"\n\
    \t\n\x02\x03\x04\x12\x03\x0f\x07%\n\t\n\x02\x03\x05\x12\x03\x10\x07'\n\t\
    \n\x02\x03\x06\x12\x03\x12\x07\x20\n\t\n\x02\x03\x07\x12\x03\x13\x07\x1d\
    \n\x08\n\x01\x08\x12\x03\x15\0$\n\x0b\n\x04\x08\xa5\xec\x03\x12\x03\x15\
    \0$\no\n\x02\x04\0\x12\x04\x1a\01\x012c\x20[#protodoc-title:\x20Listener\
    \x20components]\n\x20Listener\x20:ref:`configuration\x20overview\x20<con\
    fig_listeners>`\n\n\n\n\x03\x04\0\x01\x12\x03\x1a\x08\x0e\n\xf2\x04\n\
    \x04\x04\0\x02\0\x12\x03&\x02:\x1a\xe4\x04\x20The\x20name\x20of\x20the\
    \x20filter\x20to\x20instantiate.\x20The\x20name\x20must\x20match\x20a\
    \x20supported\n\x20filter.\x20The\x20built-in\x20filters\x20are:\n\n\x20\
    [#comment:TODO(mattklein123):\x20Auto\x20generate\x20the\x20following\
    \x20list]\n\x20*\x20:ref:`envoy.client_ssl_auth<config_network_filters_c\
    lient_ssl_auth>`\n\x20*\x20:ref:`envoy.echo\x20<config_network_filters_e\
    cho>`\n\x20*\x20:ref:`envoy.http_connection_manager\x20<config_http_conn\
    _man>`\n\x20*\x20:ref:`envoy.mongo_proxy\x20<config_network_filters_mong\
    o_proxy>`\n\x20*\x20:ref:`envoy.ratelimit\x20<config_network_filters_rat\
    e_limit>`\n\x20*\x20:ref:`envoy.redis_proxy\x20<config_network_filters_r\
    edis_proxy>`\n\x20*\x20:ref:`envoy.tcp_proxy\x20<config_network_filters_\
    tcp_proxy>`\n\n\r\n\x05\x04\0\x02\0\x04\x12\x04&\x02\x1a\x10\n\x0c\n\x05\
    \x04\0\x02\0\x05\x12\x03&\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03&\t\
    \r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03&\x10\x11\n\x0c\n\x05\x04\0\x02\0\
    \x08\x12\x03&\x129\n\x11\n\n\x04\0\x02\0\x08\x97\x8d8\x0e\x04\x12\x03&\
    \x138\n\x94\x01\n\x04\x04\0\x08\0\x12\x04*\x02.\x03\x1a\x85\x01\x20Filte\
    r\x20specific\x20configuration\x20which\x20depends\x20on\x20the\x20filte\
    r\x20being\n\x20instantiated.\x20See\x20the\x20supported\x20filters\x20f\
    or\x20further\x20documentation.\n\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03*\
    \x08\x13\n\x0b\n\x04\x04\0\x02\x01\x12\x03+\x04:\n\x0c\n\x05\x04\0\x02\
    \x01\x06\x12\x03+\x04\x1a\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03+\x1b!\n\
    \x0c\n\x05\x04\0\x02\x01\x03\x12\x03+$%\n\x0c\n\x05\x04\0\x02\x01\x08\
    \x12\x03+&9\n\r\n\x06\x04\0\x02\x01\x08\x03\x12\x03+'8\n\x0b\n\x04\x04\0\
    \x02\x02\x12\x03-\x04)\n\x0c\n\x05\x04\0\x02\x02\x06\x12\x03-\x04\x17\n\
    \x0c\n\x05\x04\0\x02\x02\x01\x12\x03-\x18$\n\x0c\n\x05\x04\0\x02\x02\x03\
    \x12\x03-'(\n\n\n\x03\x04\0\t\x12\x030\x0b\r\n\x0b\n\x04\x04\0\t\0\x12\
    \x030\x0b\x0c\n\x0c\n\x05\x04\0\t\0\x01\x12\x030\x0b\x0c\n\x0c\n\x05\x04\
    \0\t\0\x02\x12\x030\x0b\x0c\n\x89\t\n\x02\x04\x01\x12\x05M\0\xa8\x01\x01\
    \x1a\xfb\x08\x20Specifies\x20the\x20match\x20criteria\x20for\x20selectin\
    g\x20a\x20specific\x20filter\x20chain\x20for\x20a\n\x20listener.\n\n\x20\
    In\x20order\x20for\x20a\x20filter\x20chain\x20to\x20be\x20selected,\x20*\
    ALL*\x20of\x20its\x20criteria\x20must\x20be\n\x20fulfilled\x20by\x20the\
    \x20incoming\x20connection,\x20properties\x20of\x20which\x20are\x20set\
    \x20by\x20the\n\x20networking\x20stack\x20and/or\x20listener\x20filters.\
    \n\n\x20The\x20following\x20order\x20applies:\n\n\x201.\x20Destination\
    \x20port.\n\x202.\x20Destination\x20IP\x20address.\n\x203.\x20Server\x20\
    name\x20(e.g.\x20SNI\x20for\x20TLS\x20protocol),\n\x204.\x20Transport\
    \x20protocol.\n\x205.\x20Application\x20protocols\x20(e.g.\x20ALPN\x20fo\
    r\x20TLS\x20protocol).\n\x206.\x20Source\x20type\x20(e.g.\x20any,\x20loc\
    al\x20or\x20external\x20network).\n\n\x20For\x20criteria\x20that\x20allo\
    w\x20ranges\x20or\x20wildcards,\x20the\x20most\x20specific\x20value\x20i\
    n\x20any\n\x20of\x20the\x20configured\x20filter\x20chains\x20that\x20mat\
    ches\x20the\x20incoming\x20connection\x20is\x20going\n\x20to\x20be\x20us\
    ed\x20(e.g.\x20for\x20SNI\x20``www.example.com``\x20the\x20most\x20speci\
    fic\x20match\x20would\x20be\n\x20``www.example.com``,\x20then\x20``*.exa\
    mple.com``,\x20then\x20``*.com``,\x20then\x20any\x20filter\n\x20chain\
    \x20without\x20``server_names``\x20requirements).\n\n\x20[#comment:\x20I\
    mplemented\x20rules\x20are\x20kept\x20in\x20the\x20preference\x20order,\
    \x20with\x20deprecated\x20fields\n\x20listed\x20at\x20the\x20end,\x20bec\
    ause\x20that's\x20how\x20we\x20want\x20to\x20list\x20them\x20in\x20the\
    \x20docs.\n\n\x20[#comment:TODO(PiotrSikora):\x20Add\x20support\x20for\
    \x20configurable\x20precedence\x20of\x20the\x20rules]\n\n\n\n\x03\x04\
    \x01\x01\x12\x03M\x08\x18\n\x87\x01\n\x04\x04\x01\x02\0\x12\x03P\x02d\
    \x1az\x20Optional\x20destination\x20port\x20to\x20consider\x20when\x20us\
    e_original_dst\x20is\x20set\x20on\x20the\n\x20listener\x20in\x20determin\
    ing\x20a\x20filter\x20chain\x20match.\n\n\r\n\x05\x04\x01\x02\0\x04\x12\
    \x04P\x02M\x1a\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03P\x02\x1d\n\x0c\n\
    \x05\x04\x01\x02\0\x01\x12\x03P\x1e.\n\x0c\n\x05\x04\x01\x02\0\x03\x12\
    \x03P12\n\x0c\n\x05\x04\x01\x02\0\x08\x12\x03P3c\n\x10\n\t\x04\x01\x02\0\
    \x08\x97\x8d8\x05\x12\x03P4b\n\xa1\x01\n\x04\x04\x01\x02\x01\x12\x03T\
    \x02,\x1a\x93\x01\x20If\x20non-empty,\x20an\x20IP\x20address\x20and\x20p\
    refix\x20length\x20to\x20match\x20addresses\x20when\x20the\n\x20listener\
    \x20is\x20bound\x20to\x200.0.0.0/::\x20or\x20when\x20use_original_dst\
    \x20is\x20specified.\n\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x03T\x02\n\n\
    \x0c\n\x05\x04\x01\x02\x01\x06\x12\x03T\x0b\x19\n\x0c\n\x05\x04\x01\x02\
    \x01\x01\x12\x03T\x1a'\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03T*+\n\xbb\
    \x01\n\x04\x04\x01\x02\x02\x12\x03Y\x02\x1c\x1a\xad\x01\x20If\x20non-emp\
    ty,\x20an\x20IP\x20address\x20and\x20suffix\x20length\x20to\x20match\x20\
    addresses\x20when\x20the\n\x20listener\x20is\x20bound\x20to\x200.0.0.0/:\
    :\x20or\x20when\x20use_original_dst\x20is\x20specified.\n\x20[#not-imple\
    mented-hide:]\n\n\r\n\x05\x04\x01\x02\x02\x04\x12\x04Y\x02T,\n\x0c\n\x05\
    \x04\x01\x02\x02\x05\x12\x03Y\x02\x08\n\x0c\n\x05\x04\x01\x02\x02\x01\
    \x12\x03Y\t\x17\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03Y\x1a\x1b\n'\n\
    \x04\x04\x01\x02\x03\x12\x03\\\x02-\x1a\x1a\x20[#not-implemented-hide:]\
    \n\n\r\n\x05\x04\x01\x02\x03\x04\x12\x04\\\x02Y\x1c\n\x0c\n\x05\x04\x01\
    \x02\x03\x06\x12\x03\\\x02\x1d\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\\\
    \x1e(\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03\\+,\n\x0c\n\x04\x04\x01\
    \x04\0\x12\x04^\x02e\x03\n\x0c\n\x05\x04\x01\x04\0\x01\x12\x03^\x07\x1b\
    \n/\n\x06\x04\x01\x04\0\x02\0\x12\x03`\x04\x0c\x1a\x20\x20Any\x20connect\
    ion\x20source\x20matches.\n\n\x0e\n\x07\x04\x01\x04\0\x02\0\x01\x12\x03`\
    \x04\x07\n\x0e\n\x07\x04\x01\x04\0\x02\0\x02\x12\x03`\n\x0b\nC\n\x06\x04\
    \x01\x04\0\x02\x01\x12\x03b\x04\x0e\x1a4\x20Match\x20a\x20connection\x20\
    originating\x20from\x20the\x20same\x20host.\n\n\x0e\n\x07\x04\x01\x04\0\
    \x02\x01\x01\x12\x03b\x04\t\n\x0e\n\x07\x04\x01\x04\0\x02\x01\x02\x12\
    \x03b\x0c\r\nF\n\x06\x04\x01\x04\0\x02\x02\x12\x03d\x04\x11\x1a7\x20Matc\
    h\x20a\x20connection\x20originating\x20from\x20a\x20different\x20host.\n\
    \n\x0e\n\x07\x04\x01\x04\0\x02\x02\x01\x12\x03d\x04\x0c\n\x0e\n\x07\x04\
    \x01\x04\0\x02\x02\x02\x12\x03d\x0f\x10\nd\n\x04\x04\x01\x02\x04\x12\x03\
    h\x02T\x1aW\x20Specifies\x20the\x20connection\x20source\x20IP\x20match\
    \x20type.\x20Can\x20be\x20any,\x20local\x20or\x20external\x20network.\n\
    \n\r\n\x05\x04\x01\x02\x04\x04\x12\x04h\x02e\x03\n\x0c\n\x05\x04\x01\x02\
    \x04\x06\x12\x03h\x02\x16\n\x0c\n\x05\x04\x01\x02\x04\x01\x12\x03h\x17\"\
    \n\x0c\n\x05\x04\x01\x02\x04\x03\x12\x03h%'\n\x0c\n\x05\x04\x01\x02\x04\
    \x08\x12\x03h(S\n\x11\n\n\x04\x01\x02\x04\x08\x97\x8d8\x10\x02\x12\x03h)\
    R\n\x8d\x02\n\x04\x04\x01\x02\x05\x12\x03o\x023\x1a\xff\x01\x20The\x20cr\
    iteria\x20is\x20satisfied\x20if\x20the\x20source\x20IP\x20address\x20of\
    \x20the\x20downstream\n\x20connection\x20is\x20contained\x20in\x20at\x20\
    least\x20one\x20of\x20the\x20specified\x20subnets.\x20If\x20the\n\x20par\
    ameter\x20is\x20not\x20specified\x20or\x20the\x20list\x20is\x20empty,\
    \x20the\x20source\x20IP\x20address\x20is\n\x20ignored.\n\x20[#not-implem\
    ented-hide:]\n\n\x0c\n\x05\x04\x01\x02\x05\x04\x12\x03o\x02\n\n\x0c\n\
    \x05\x04\x01\x02\x05\x06\x12\x03o\x0b\x19\n\x0c\n\x05\x04\x01\x02\x05\
    \x01\x12\x03o\x1a.\n\x0c\n\x05\x04\x01\x02\x05\x03\x12\x03o12\n\xe9\x01\
    \n\x04\x04\x01\x02\x06\x12\x03u\x028\x1a\xdb\x01\x20The\x20criteria\x20i\
    s\x20satisfied\x20if\x20the\x20source\x20port\x20of\x20the\x20downstream\
    \x20connection\n\x20is\x20contained\x20in\x20at\x20least\x20one\x20of\
    \x20the\x20specified\x20ports.\x20If\x20the\x20parameter\x20is\n\x20not\
    \x20specified,\x20the\x20source\x20port\x20is\x20ignored.\n\x20[#not-imp\
    lemented-hide:]\n\n\x0c\n\x05\x04\x01\x02\x06\x04\x12\x03u\x02\n\n\x0c\n\
    \x05\x04\x01\x02\x06\x06\x12\x03u\x0b&\n\x0c\n\x05\x04\x01\x02\x06\x01\
    \x12\x03u'3\n\x0c\n\x05\x04\x01\x02\x06\x03\x12\x03u67\n\x8c\x05\n\x04\
    \x04\x01\x02\x07\x12\x04\x84\x01\x02$\x1a\xfd\x04\x20If\x20non-empty,\
    \x20a\x20list\x20of\x20server\x20names\x20(e.g.\x20SNI\x20for\x20TLS\x20\
    protocol)\x20to\x20consider\x20when\x20determining\n\x20a\x20filter\x20c\
    hain\x20match.\x20Those\x20values\x20will\x20be\x20compared\x20against\
    \x20the\x20server\x20names\x20of\x20a\x20new\n\x20connection,\x20when\
    \x20detected\x20by\x20one\x20of\x20the\x20listener\x20filters.\n\n\x20Th\
    e\x20server\x20name\x20will\x20be\x20matched\x20against\x20all\x20wildca\
    rd\x20domains,\x20i.e.\x20``www.example.com``\n\x20will\x20be\x20first\
    \x20matched\x20against\x20``www.example.com``,\x20then\x20``*.example.co\
    m``,\x20then\x20``*.com``.\n\n\x20Note\x20that\x20partial\x20wildcards\
    \x20are\x20not\x20supported,\x20and\x20values\x20like\x20``*w.example.co\
    m``\x20are\x20invalid.\n\n\x20..\x20attention::\n\n\x20\x20\x20See\x20th\
    e\x20:ref:`FAQ\x20entry\x20<faq_how_to_setup_sni>`\x20on\x20how\x20to\
    \x20configure\x20SNI\x20for\x20more\n\x20\x20\x20information.\n\n\r\n\
    \x05\x04\x01\x02\x07\x04\x12\x04\x84\x01\x02\n\n\r\n\x05\x04\x01\x02\x07\
    \x05\x12\x04\x84\x01\x0b\x11\n\r\n\x05\x04\x01\x02\x07\x01\x12\x04\x84\
    \x01\x12\x1e\n\r\n\x05\x04\x01\x02\x07\x03\x12\x04\x84\x01!#\n\xd4\x03\n\
    \x04\x04\x01\x02\x08\x12\x04\x8f\x01\x02\x20\x1a\xc5\x03\x20If\x20non-em\
    pty,\x20a\x20transport\x20protocol\x20to\x20consider\x20when\x20determin\
    ing\x20a\x20filter\x20chain\x20match.\n\x20This\x20value\x20will\x20be\
    \x20compared\x20against\x20the\x20transport\x20protocol\x20of\x20a\x20ne\
    w\x20connection,\x20when\n\x20it's\x20detected\x20by\x20one\x20of\x20the\
    \x20listener\x20filters.\n\n\x20Suggested\x20values\x20include:\n\n\x20*\
    \x20``raw_buffer``\x20-\x20default,\x20used\x20when\x20no\x20transport\
    \x20protocol\x20is\x20detected,\n\x20*\x20``tls``\x20-\x20set\x20by\x20:\
    ref:`envoy.listener.tls_inspector\x20<config_listener_filters_tls_inspec\
    tor>`\n\x20\x20\x20when\x20TLS\x20protocol\x20is\x20detected.\n\n\x0f\n\
    \x05\x04\x01\x02\x08\x04\x12\x06\x8f\x01\x02\x84\x01$\n\r\n\x05\x04\x01\
    \x02\x08\x05\x12\x04\x8f\x01\x02\x08\n\r\n\x05\x04\x01\x02\x08\x01\x12\
    \x04\x8f\x01\t\x1b\n\r\n\x05\x04\x01\x02\x08\x03\x12\x04\x8f\x01\x1e\x1f\
    \n\xe3\x07\n\x04\x04\x01\x02\t\x12\x04\xa4\x01\x02-\x1a\xd4\x07\x20If\
    \x20non-empty,\x20a\x20list\x20of\x20application\x20protocols\x20(e.g.\
    \x20ALPN\x20for\x20TLS\x20protocol)\x20to\x20consider\x20when\n\x20deter\
    mining\x20a\x20filter\x20chain\x20match.\x20Those\x20values\x20will\x20b\
    e\x20compared\x20against\x20the\x20application\n\x20protocols\x20of\x20a\
    \x20new\x20connection,\x20when\x20detected\x20by\x20one\x20of\x20the\x20\
    listener\x20filters.\n\n\x20Suggested\x20values\x20include:\n\n\x20*\x20\
    ``http/1.1``\x20-\x20set\x20by\x20:ref:`envoy.listener.tls_inspector\n\
    \x20\x20\x20<config_listener_filters_tls_inspector>`,\n\x20*\x20``h2``\
    \x20-\x20set\x20by\x20:ref:`envoy.listener.tls_inspector\x20<config_list\
    ener_filters_tls_inspector>`\n\n\x20..\x20attention::\n\n\x20\x20\x20Cur\
    rently,\x20only\x20:ref:`TLS\x20Inspector\x20<config_listener_filters_tl\
    s_inspector>`\x20provides\n\x20\x20\x20application\x20protocol\x20detect\
    ion\x20based\x20on\x20the\x20requested\n\x20\x20\x20`ALPN\x20<https://en\
    .wikipedia.org/wiki/Application-Layer_Protocol_Negotiation>`_\x20values.\
    \n\n\x20\x20\x20However,\x20the\x20use\x20of\x20ALPN\x20is\x20pretty\x20\
    much\x20limited\x20to\x20the\x20HTTP/2\x20traffic\x20on\x20the\x20Intern\
    et,\n\x20\x20\x20and\x20matching\x20on\x20values\x20other\x20than\x20``h\
    2``\x20is\x20going\x20to\x20lead\x20to\x20a\x20lot\x20of\x20false\x20neg\
    atives,\n\x20\x20\x20unless\x20all\x20connecting\x20clients\x20are\x20kn\
    own\x20to\x20use\x20ALPN.\n\n\r\n\x05\x04\x01\x02\t\x04\x12\x04\xa4\x01\
    \x02\n\n\r\n\x05\x04\x01\x02\t\x05\x12\x04\xa4\x01\x0b\x11\n\r\n\x05\x04\
    \x01\x02\t\x01\x12\x04\xa4\x01\x12'\n\r\n\x05\x04\x01\x02\t\x03\x12\x04\
    \xa4\x01*,\n\x0b\n\x03\x04\x01\t\x12\x04\xa6\x01\x0b\r\n\x0c\n\x04\x04\
    \x01\t\0\x12\x04\xa6\x01\x0b\x0c\n\r\n\x05\x04\x01\t\0\x01\x12\x04\xa6\
    \x01\x0b\x0c\n\r\n\x05\x04\x01\t\0\x02\x12\x04\xa6\x01\x0b\x0c\n\x0b\n\
    \x03\x04\x01\n\x12\x04\xa7\x01\x0b\x19\n\x0c\n\x04\x04\x01\n\0\x12\x04\
    \xa7\x01\x0b\x18\n\x85\x01\n\x02\x04\x02\x12\x06\xac\x01\0\xc6\x01\x01\
    \x1aw\x20A\x20filter\x20chain\x20wraps\x20a\x20set\x20of\x20match\x20cri\
    teria,\x20an\x20option\x20TLS\x20context,\x20a\x20set\x20of\x20filters,\
    \x20and\n\x20various\x20other\x20parameters.\n\n\x0b\n\x03\x04\x02\x01\
    \x12\x04\xac\x01\x08\x13\nT\n\x04\x04\x02\x02\0\x12\x04\xae\x01\x02*\x1a\
    F\x20The\x20criteria\x20to\x20use\x20when\x20matching\x20a\x20connection\
    \x20to\x20this\x20filter\x20chain.\n\n\x0f\n\x05\x04\x02\x02\0\x04\x12\
    \x06\xae\x01\x02\xac\x01\x15\n\r\n\x05\x04\x02\x02\0\x06\x12\x04\xae\x01\
    \x02\x12\n\r\n\x05\x04\x02\x02\0\x01\x12\x04\xae\x01\x13%\n\r\n\x05\x04\
    \x02\x02\0\x03\x12\x04\xae\x01()\n6\n\x04\x04\x02\x02\x01\x12\x04\xb1\
    \x01\x02,\x1a(\x20The\x20TLS\x20context\x20for\x20this\x20filter\x20chai\
    n.\n\n\x0f\n\x05\x04\x02\x02\x01\x04\x12\x06\xb1\x01\x02\xae\x01*\n\r\n\
    \x05\x04\x02\x02\x01\x06\x12\x04\xb1\x01\x02\x1b\n\r\n\x05\x04\x02\x02\
    \x01\x01\x12\x04\xb1\x01\x1c'\n\r\n\x05\x04\x02\x02\x01\x03\x12\x04\xb1\
    \x01*+\n\xa3\x02\n\x04\x04\x02\x02\x02\x12\x04\xb7\x01\x02=\x1a\x94\x02\
    \x20A\x20list\x20of\x20individual\x20network\x20filters\x20that\x20make\
    \x20up\x20the\x20filter\x20chain\x20for\n\x20connections\x20established\
    \x20with\x20the\x20listener.\x20Order\x20matters\x20as\x20the\x20filters\
    \x20are\n\x20processed\x20sequentially\x20as\x20connection\x20events\x20\
    happen.\x20Note:\x20If\x20the\x20filter\n\x20list\x20is\x20empty,\x20the\
    \x20connection\x20will\x20close\x20by\x20default.\n\n\r\n\x05\x04\x02\
    \x02\x02\x04\x12\x04\xb7\x01\x02\n\n\r\n\x05\x04\x02\x02\x02\x06\x12\x04\
    \xb7\x01\x0b\x11\n\r\n\x05\x04\x02\x02\x02\x01\x12\x04\xb7\x01\x12\x19\n\
    \r\n\x05\x04\x02\x02\x02\x03\x12\x04\xb7\x01\x1c\x1d\n\r\n\x05\x04\x02\
    \x02\x02\x08\x12\x04\xb7\x01\x1e<\n\x10\n\x08\x04\x02\x02\x02\x08\xe9\
    \xfb\x03\x12\x04\xb7\x01\x1f;\n\xa4\x03\n\x04\x04\x02\x02\x03\x12\x04\
    \xbf\x01\x020\x1a\x95\x03\x20Whether\x20the\x20listener\x20should\x20exp\
    ect\x20a\x20PROXY\x20protocol\x20V1\x20header\x20on\x20new\n\x20connecti\
    ons.\x20If\x20this\x20option\x20is\x20enabled,\x20the\x20listener\x20wil\
    l\x20assume\x20that\x20that\n\x20remote\x20address\x20of\x20the\x20conne\
    ction\x20is\x20the\x20one\x20specified\x20in\x20the\x20header.\x20Some\n\
    \x20load\x20balancers\x20including\x20the\x20AWS\x20ELB\x20support\x20th\
    is\x20option.\x20If\x20the\x20option\x20is\n\x20absent\x20or\x20set\x20t\
    o\x20false,\x20Envoy\x20will\x20use\x20the\x20physical\x20peer\x20addres\
    s\x20of\x20the\n\x20connection\x20as\x20the\x20remote\x20address.\n\n\
    \x0f\n\x05\x04\x02\x02\x03\x04\x12\x06\xbf\x01\x02\xb7\x01=\n\r\n\x05\
    \x04\x02\x02\x03\x06\x12\x04\xbf\x01\x02\x1b\n\r\n\x05\x04\x02\x02\x03\
    \x01\x12\x04\xbf\x01\x1c+\n\r\n\x05\x04\x02\x02\x03\x03\x12\x04\xbf\x01.\
    /\n?\n\x04\x04\x02\x02\x04\x12\x04\xc2\x01\x02\x1d\x1a1\x20[#not-impleme\
    nted-hide:]\x20filter\x20chain\x20metadata.\n\n\x0f\n\x05\x04\x02\x02\
    \x04\x04\x12\x06\xc2\x01\x02\xbf\x010\n\r\n\x05\x04\x02\x02\x04\x06\x12\
    \x04\xc2\x01\x02\x0f\n\r\n\x05\x04\x02\x02\x04\x01\x12\x04\xc2\x01\x10\
    \x18\n\r\n\x05\x04\x02\x02\x04\x03\x12\x04\xc2\x01\x1b\x1c\n`\n\x04\x04\
    \x02\x02\x05\x12\x04\xc5\x01\x02,\x1aR\x20See\x20:ref:`base.TransportSoc\
    ket<envoy_api_msg_core.TransportSocket>`\x20description.\n\n\x0f\n\x05\
    \x04\x02\x02\x05\x04\x12\x06\xc5\x01\x02\xc2\x01\x1d\n\r\n\x05\x04\x02\
    \x02\x05\x06\x12\x04\xc5\x01\x02\x16\n\r\n\x05\x04\x02\x02\x05\x01\x12\
    \x04\xc5\x01\x17'\n\r\n\x05\x04\x02\x02\x05\x03\x12\x04\xc5\x01*+\n\x0c\
    \n\x02\x04\x03\x12\x06\xc8\x01\0\xd8\x01\x01\n\x0b\n\x03\x04\x03\x01\x12\
    \x04\xc8\x01\x08\x16\n\xd8\x02\n\x04\x04\x03\x02\0\x12\x04\xcf\x01\x02:\
    \x1a\xc9\x02\x20The\x20name\x20of\x20the\x20filter\x20to\x20instantiate.\
    \x20The\x20name\x20must\x20match\x20a\x20supported\n\x20filter.\x20The\
    \x20built-in\x20filters\x20are:\n\n\x20[#comment:TODO(mattklein123):\x20\
    Auto\x20generate\x20the\x20following\x20list]\n\x20*\x20:ref:`envoy.list\
    ener.original_dst\x20<config_listener_filters_original_dst>`\n\x20*\x20:\
    ref:`envoy.listener.tls_inspector\x20<config_listener_filters_tls_inspec\
    tor>`\n\n\x0f\n\x05\x04\x03\x02\0\x04\x12\x06\xcf\x01\x02\xc8\x01\x18\n\
    \r\n\x05\x04\x03\x02\0\x05\x12\x04\xcf\x01\x02\x08\n\r\n\x05\x04\x03\x02\
    \0\x01\x12\x04\xcf\x01\t\r\n\r\n\x05\x04\x03\x02\0\x03\x12\x04\xcf\x01\
    \x10\x11\n\r\n\x05\x04\x03\x02\0\x08\x12\x04\xcf\x01\x129\n\x12\n\n\x04\
    \x03\x02\0\x08\x97\x8d8\x0e\x04\x12\x04\xcf\x01\x138\n\x96\x01\n\x04\x04\
    \x03\x08\0\x12\x06\xd3\x01\x02\xd7\x01\x03\x1a\x85\x01\x20Filter\x20spec\
    ific\x20configuration\x20which\x20depends\x20on\x20the\x20filter\x20bein\
    g\x20instantiated.\n\x20See\x20the\x20supported\x20filters\x20for\x20fur\
    ther\x20documentation.\n\n\r\n\x05\x04\x03\x08\0\x01\x12\x04\xd3\x01\x08\
    \x13\n\x0c\n\x04\x04\x03\x02\x01\x12\x04\xd4\x01\x04:\n\r\n\x05\x04\x03\
    \x02\x01\x06\x12\x04\xd4\x01\x04\x1a\n\r\n\x05\x04\x03\x02\x01\x01\x12\
    \x04\xd4\x01\x1b!\n\r\n\x05\x04\x03\x02\x01\x03\x12\x04\xd4\x01$%\n\r\n\
    \x05\x04\x03\x02\x01\x08\x12\x04\xd4\x01&9\n\x0e\n\x06\x04\x03\x02\x01\
    \x08\x03\x12\x04\xd4\x01'8\n\x0c\n\x04\x04\x03\x02\x02\x12\x04\xd6\x01\
    \x04)\n\r\n\x05\x04\x03\x02\x02\x06\x12\x04\xd6\x01\x04\x17\n\r\n\x05\
    \x04\x03\x02\x02\x01\x12\x04\xd6\x01\x18$\n\r\n\x05\x04\x03\x02\x02\x03\
    \x12\x04\xd6\x01'(b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
