// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct UpstreamLocalityStats {
    // message fields
    pub locality: ::protobuf::SingularPtrField<super::base::Locality>,
    pub total_successful_requests: u64,
    pub total_requests_in_progress: u64,
    pub total_error_requests: u64,
    pub load_metric_stats: ::protobuf::RepeatedField<EndpointLoadMetricStats>,
    pub upstream_endpoint_stats: ::protobuf::RepeatedField<UpstreamEndpointStats>,
    pub priority: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl UpstreamLocalityStats {
    pub fn new() -> UpstreamLocalityStats {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.core.Locality locality = 1;

    pub fn clear_locality(&mut self) {
        self.locality.clear();
    }

    pub fn has_locality(&self) -> bool {
        self.locality.is_some()
    }

    // Param is passed by value, moved
    pub fn set_locality(&mut self, v: super::base::Locality) {
        self.locality = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_locality(&mut self) -> &mut super::base::Locality {
        if self.locality.is_none() {
            self.locality.set_default();
        }
        self.locality.as_mut().unwrap()
    }

    // Take field
    pub fn take_locality(&mut self) -> super::base::Locality {
        self.locality.take().unwrap_or_else(|| super::base::Locality::new())
    }

    pub fn get_locality(&self) -> &super::base::Locality {
        self.locality.as_ref().unwrap_or_else(|| super::base::Locality::default_instance())
    }

    // uint64 total_successful_requests = 2;

    pub fn clear_total_successful_requests(&mut self) {
        self.total_successful_requests = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_successful_requests(&mut self, v: u64) {
        self.total_successful_requests = v;
    }

    pub fn get_total_successful_requests(&self) -> u64 {
        self.total_successful_requests
    }

    // uint64 total_requests_in_progress = 3;

    pub fn clear_total_requests_in_progress(&mut self) {
        self.total_requests_in_progress = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_requests_in_progress(&mut self, v: u64) {
        self.total_requests_in_progress = v;
    }

    pub fn get_total_requests_in_progress(&self) -> u64 {
        self.total_requests_in_progress
    }

    // uint64 total_error_requests = 4;

    pub fn clear_total_error_requests(&mut self) {
        self.total_error_requests = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_error_requests(&mut self, v: u64) {
        self.total_error_requests = v;
    }

    pub fn get_total_error_requests(&self) -> u64 {
        self.total_error_requests
    }

    // repeated .envoy.api.v2.endpoint.EndpointLoadMetricStats load_metric_stats = 5;

    pub fn clear_load_metric_stats(&mut self) {
        self.load_metric_stats.clear();
    }

    // Param is passed by value, moved
    pub fn set_load_metric_stats(&mut self, v: ::protobuf::RepeatedField<EndpointLoadMetricStats>) {
        self.load_metric_stats = v;
    }

    // Mutable pointer to the field.
    pub fn mut_load_metric_stats(&mut self) -> &mut ::protobuf::RepeatedField<EndpointLoadMetricStats> {
        &mut self.load_metric_stats
    }

    // Take field
    pub fn take_load_metric_stats(&mut self) -> ::protobuf::RepeatedField<EndpointLoadMetricStats> {
        ::std::mem::replace(&mut self.load_metric_stats, ::protobuf::RepeatedField::new())
    }

    pub fn get_load_metric_stats(&self) -> &[EndpointLoadMetricStats] {
        &self.load_metric_stats
    }

    // repeated .envoy.api.v2.endpoint.UpstreamEndpointStats upstream_endpoint_stats = 7;

    pub fn clear_upstream_endpoint_stats(&mut self) {
        self.upstream_endpoint_stats.clear();
    }

    // Param is passed by value, moved
    pub fn set_upstream_endpoint_stats(&mut self, v: ::protobuf::RepeatedField<UpstreamEndpointStats>) {
        self.upstream_endpoint_stats = v;
    }

    // Mutable pointer to the field.
    pub fn mut_upstream_endpoint_stats(&mut self) -> &mut ::protobuf::RepeatedField<UpstreamEndpointStats> {
        &mut self.upstream_endpoint_stats
    }

    // Take field
    pub fn take_upstream_endpoint_stats(&mut self) -> ::protobuf::RepeatedField<UpstreamEndpointStats> {
        ::std::mem::replace(&mut self.upstream_endpoint_stats, ::protobuf::RepeatedField::new())
    }

    pub fn get_upstream_endpoint_stats(&self) -> &[UpstreamEndpointStats] {
        &self.upstream_endpoint_stats
    }

    // uint32 priority = 6;

    pub fn clear_priority(&mut self) {
        self.priority = 0;
    }

    // Param is passed by value, moved
    pub fn set_priority(&mut self, v: u32) {
        self.priority = v;
    }

    pub fn get_priority(&self) -> u32 {
        self.priority
    }
}

impl ::protobuf::Message for UpstreamLocalityStats {
    fn is_initialized(&self) -> bool {
        for v in &self.locality {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.load_metric_stats {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.upstream_endpoint_stats {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.locality)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_successful_requests = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_requests_in_progress = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_error_requests = tmp;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.load_metric_stats)?;
                },
                7 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.upstream_endpoint_stats)?;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.priority = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.locality.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.total_successful_requests != 0 {
            my_size += ::protobuf::rt::value_size(2, self.total_successful_requests, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_requests_in_progress != 0 {
            my_size += ::protobuf::rt::value_size(3, self.total_requests_in_progress, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_error_requests != 0 {
            my_size += ::protobuf::rt::value_size(4, self.total_error_requests, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.load_metric_stats {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.upstream_endpoint_stats {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.priority != 0 {
            my_size += ::protobuf::rt::value_size(6, self.priority, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.locality.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.total_successful_requests != 0 {
            os.write_uint64(2, self.total_successful_requests)?;
        }
        if self.total_requests_in_progress != 0 {
            os.write_uint64(3, self.total_requests_in_progress)?;
        }
        if self.total_error_requests != 0 {
            os.write_uint64(4, self.total_error_requests)?;
        }
        for v in &self.load_metric_stats {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.upstream_endpoint_stats {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.priority != 0 {
            os.write_uint32(6, self.priority)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UpstreamLocalityStats {
        UpstreamLocalityStats::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::Locality>>(
                    "locality",
                    |m: &UpstreamLocalityStats| { &m.locality },
                    |m: &mut UpstreamLocalityStats| { &mut m.locality },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_successful_requests",
                    |m: &UpstreamLocalityStats| { &m.total_successful_requests },
                    |m: &mut UpstreamLocalityStats| { &mut m.total_successful_requests },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_requests_in_progress",
                    |m: &UpstreamLocalityStats| { &m.total_requests_in_progress },
                    |m: &mut UpstreamLocalityStats| { &mut m.total_requests_in_progress },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_error_requests",
                    |m: &UpstreamLocalityStats| { &m.total_error_requests },
                    |m: &mut UpstreamLocalityStats| { &mut m.total_error_requests },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<EndpointLoadMetricStats>>(
                    "load_metric_stats",
                    |m: &UpstreamLocalityStats| { &m.load_metric_stats },
                    |m: &mut UpstreamLocalityStats| { &mut m.load_metric_stats },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<UpstreamEndpointStats>>(
                    "upstream_endpoint_stats",
                    |m: &UpstreamLocalityStats| { &m.upstream_endpoint_stats },
                    |m: &mut UpstreamLocalityStats| { &mut m.upstream_endpoint_stats },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "priority",
                    |m: &UpstreamLocalityStats| { &m.priority },
                    |m: &mut UpstreamLocalityStats| { &mut m.priority },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<UpstreamLocalityStats>(
                    "UpstreamLocalityStats",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static UpstreamLocalityStats {
        static mut instance: ::protobuf::lazy::Lazy<UpstreamLocalityStats> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const UpstreamLocalityStats,
        };
        unsafe {
            instance.get(UpstreamLocalityStats::new)
        }
    }
}

impl ::protobuf::Clear for UpstreamLocalityStats {
    fn clear(&mut self) {
        self.clear_locality();
        self.clear_total_successful_requests();
        self.clear_total_requests_in_progress();
        self.clear_total_error_requests();
        self.clear_load_metric_stats();
        self.clear_upstream_endpoint_stats();
        self.clear_priority();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UpstreamLocalityStats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpstreamLocalityStats {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct UpstreamEndpointStats {
    // message fields
    pub address: ::protobuf::SingularPtrField<super::address::Address>,
    pub metadata: ::protobuf::SingularPtrField<::protobuf::well_known_types::Struct>,
    pub total_successful_requests: u64,
    pub total_requests_in_progress: u64,
    pub total_error_requests: u64,
    pub load_metric_stats: ::protobuf::RepeatedField<EndpointLoadMetricStats>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl UpstreamEndpointStats {
    pub fn new() -> UpstreamEndpointStats {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.core.Address address = 1;

    pub fn clear_address(&mut self) {
        self.address.clear();
    }

    pub fn has_address(&self) -> bool {
        self.address.is_some()
    }

    // Param is passed by value, moved
    pub fn set_address(&mut self, v: super::address::Address) {
        self.address = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address(&mut self) -> &mut super::address::Address {
        if self.address.is_none() {
            self.address.set_default();
        }
        self.address.as_mut().unwrap()
    }

    // Take field
    pub fn take_address(&mut self) -> super::address::Address {
        self.address.take().unwrap_or_else(|| super::address::Address::new())
    }

    pub fn get_address(&self) -> &super::address::Address {
        self.address.as_ref().unwrap_or_else(|| super::address::Address::default_instance())
    }

    // .google.protobuf.Struct metadata = 6;

    pub fn clear_metadata(&mut self) {
        self.metadata.clear();
    }

    pub fn has_metadata(&self) -> bool {
        self.metadata.is_some()
    }

    // Param is passed by value, moved
    pub fn set_metadata(&mut self, v: ::protobuf::well_known_types::Struct) {
        self.metadata = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_metadata(&mut self) -> &mut ::protobuf::well_known_types::Struct {
        if self.metadata.is_none() {
            self.metadata.set_default();
        }
        self.metadata.as_mut().unwrap()
    }

    // Take field
    pub fn take_metadata(&mut self) -> ::protobuf::well_known_types::Struct {
        self.metadata.take().unwrap_or_else(|| ::protobuf::well_known_types::Struct::new())
    }

    pub fn get_metadata(&self) -> &::protobuf::well_known_types::Struct {
        self.metadata.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Struct::default_instance())
    }

    // uint64 total_successful_requests = 2;

    pub fn clear_total_successful_requests(&mut self) {
        self.total_successful_requests = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_successful_requests(&mut self, v: u64) {
        self.total_successful_requests = v;
    }

    pub fn get_total_successful_requests(&self) -> u64 {
        self.total_successful_requests
    }

    // uint64 total_requests_in_progress = 3;

    pub fn clear_total_requests_in_progress(&mut self) {
        self.total_requests_in_progress = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_requests_in_progress(&mut self, v: u64) {
        self.total_requests_in_progress = v;
    }

    pub fn get_total_requests_in_progress(&self) -> u64 {
        self.total_requests_in_progress
    }

    // uint64 total_error_requests = 4;

    pub fn clear_total_error_requests(&mut self) {
        self.total_error_requests = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_error_requests(&mut self, v: u64) {
        self.total_error_requests = v;
    }

    pub fn get_total_error_requests(&self) -> u64 {
        self.total_error_requests
    }

    // repeated .envoy.api.v2.endpoint.EndpointLoadMetricStats load_metric_stats = 5;

    pub fn clear_load_metric_stats(&mut self) {
        self.load_metric_stats.clear();
    }

    // Param is passed by value, moved
    pub fn set_load_metric_stats(&mut self, v: ::protobuf::RepeatedField<EndpointLoadMetricStats>) {
        self.load_metric_stats = v;
    }

    // Mutable pointer to the field.
    pub fn mut_load_metric_stats(&mut self) -> &mut ::protobuf::RepeatedField<EndpointLoadMetricStats> {
        &mut self.load_metric_stats
    }

    // Take field
    pub fn take_load_metric_stats(&mut self) -> ::protobuf::RepeatedField<EndpointLoadMetricStats> {
        ::std::mem::replace(&mut self.load_metric_stats, ::protobuf::RepeatedField::new())
    }

    pub fn get_load_metric_stats(&self) -> &[EndpointLoadMetricStats] {
        &self.load_metric_stats
    }
}

impl ::protobuf::Message for UpstreamEndpointStats {
    fn is_initialized(&self) -> bool {
        for v in &self.address {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.metadata {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.load_metric_stats {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.address)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.metadata)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_successful_requests = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_requests_in_progress = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_error_requests = tmp;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.load_metric_stats)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.address.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.total_successful_requests != 0 {
            my_size += ::protobuf::rt::value_size(2, self.total_successful_requests, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_requests_in_progress != 0 {
            my_size += ::protobuf::rt::value_size(3, self.total_requests_in_progress, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_error_requests != 0 {
            my_size += ::protobuf::rt::value_size(4, self.total_error_requests, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.load_metric_stats {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.address.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.metadata.as_ref() {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.total_successful_requests != 0 {
            os.write_uint64(2, self.total_successful_requests)?;
        }
        if self.total_requests_in_progress != 0 {
            os.write_uint64(3, self.total_requests_in_progress)?;
        }
        if self.total_error_requests != 0 {
            os.write_uint64(4, self.total_error_requests)?;
        }
        for v in &self.load_metric_stats {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UpstreamEndpointStats {
        UpstreamEndpointStats::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::address::Address>>(
                    "address",
                    |m: &UpstreamEndpointStats| { &m.address },
                    |m: &mut UpstreamEndpointStats| { &mut m.address },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Struct>>(
                    "metadata",
                    |m: &UpstreamEndpointStats| { &m.metadata },
                    |m: &mut UpstreamEndpointStats| { &mut m.metadata },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_successful_requests",
                    |m: &UpstreamEndpointStats| { &m.total_successful_requests },
                    |m: &mut UpstreamEndpointStats| { &mut m.total_successful_requests },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_requests_in_progress",
                    |m: &UpstreamEndpointStats| { &m.total_requests_in_progress },
                    |m: &mut UpstreamEndpointStats| { &mut m.total_requests_in_progress },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_error_requests",
                    |m: &UpstreamEndpointStats| { &m.total_error_requests },
                    |m: &mut UpstreamEndpointStats| { &mut m.total_error_requests },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<EndpointLoadMetricStats>>(
                    "load_metric_stats",
                    |m: &UpstreamEndpointStats| { &m.load_metric_stats },
                    |m: &mut UpstreamEndpointStats| { &mut m.load_metric_stats },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<UpstreamEndpointStats>(
                    "UpstreamEndpointStats",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static UpstreamEndpointStats {
        static mut instance: ::protobuf::lazy::Lazy<UpstreamEndpointStats> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const UpstreamEndpointStats,
        };
        unsafe {
            instance.get(UpstreamEndpointStats::new)
        }
    }
}

impl ::protobuf::Clear for UpstreamEndpointStats {
    fn clear(&mut self) {
        self.clear_address();
        self.clear_metadata();
        self.clear_total_successful_requests();
        self.clear_total_requests_in_progress();
        self.clear_total_error_requests();
        self.clear_load_metric_stats();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UpstreamEndpointStats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpstreamEndpointStats {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct EndpointLoadMetricStats {
    // message fields
    pub metric_name: ::std::string::String,
    pub num_requests_finished_with_metric: u64,
    pub total_metric_value: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl EndpointLoadMetricStats {
    pub fn new() -> EndpointLoadMetricStats {
        ::std::default::Default::default()
    }

    // string metric_name = 1;

    pub fn clear_metric_name(&mut self) {
        self.metric_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_metric_name(&mut self, v: ::std::string::String) {
        self.metric_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_metric_name(&mut self) -> &mut ::std::string::String {
        &mut self.metric_name
    }

    // Take field
    pub fn take_metric_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.metric_name, ::std::string::String::new())
    }

    pub fn get_metric_name(&self) -> &str {
        &self.metric_name
    }

    // uint64 num_requests_finished_with_metric = 2;

    pub fn clear_num_requests_finished_with_metric(&mut self) {
        self.num_requests_finished_with_metric = 0;
    }

    // Param is passed by value, moved
    pub fn set_num_requests_finished_with_metric(&mut self, v: u64) {
        self.num_requests_finished_with_metric = v;
    }

    pub fn get_num_requests_finished_with_metric(&self) -> u64 {
        self.num_requests_finished_with_metric
    }

    // double total_metric_value = 3;

    pub fn clear_total_metric_value(&mut self) {
        self.total_metric_value = 0.;
    }

    // Param is passed by value, moved
    pub fn set_total_metric_value(&mut self, v: f64) {
        self.total_metric_value = v;
    }

    pub fn get_total_metric_value(&self) -> f64 {
        self.total_metric_value
    }
}

impl ::protobuf::Message for EndpointLoadMetricStats {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.metric_name)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.num_requests_finished_with_metric = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.total_metric_value = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.metric_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.metric_name);
        }
        if self.num_requests_finished_with_metric != 0 {
            my_size += ::protobuf::rt::value_size(2, self.num_requests_finished_with_metric, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_metric_value != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.metric_name.is_empty() {
            os.write_string(1, &self.metric_name)?;
        }
        if self.num_requests_finished_with_metric != 0 {
            os.write_uint64(2, self.num_requests_finished_with_metric)?;
        }
        if self.total_metric_value != 0. {
            os.write_double(3, self.total_metric_value)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EndpointLoadMetricStats {
        EndpointLoadMetricStats::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "metric_name",
                    |m: &EndpointLoadMetricStats| { &m.metric_name },
                    |m: &mut EndpointLoadMetricStats| { &mut m.metric_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "num_requests_finished_with_metric",
                    |m: &EndpointLoadMetricStats| { &m.num_requests_finished_with_metric },
                    |m: &mut EndpointLoadMetricStats| { &mut m.num_requests_finished_with_metric },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "total_metric_value",
                    |m: &EndpointLoadMetricStats| { &m.total_metric_value },
                    |m: &mut EndpointLoadMetricStats| { &mut m.total_metric_value },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<EndpointLoadMetricStats>(
                    "EndpointLoadMetricStats",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static EndpointLoadMetricStats {
        static mut instance: ::protobuf::lazy::Lazy<EndpointLoadMetricStats> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const EndpointLoadMetricStats,
        };
        unsafe {
            instance.get(EndpointLoadMetricStats::new)
        }
    }
}

impl ::protobuf::Clear for EndpointLoadMetricStats {
    fn clear(&mut self) {
        self.clear_metric_name();
        self.clear_num_requests_finished_with_metric();
        self.clear_total_metric_value();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EndpointLoadMetricStats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EndpointLoadMetricStats {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ClusterStats {
    // message fields
    pub cluster_name: ::std::string::String,
    pub cluster_service_name: ::std::string::String,
    pub upstream_locality_stats: ::protobuf::RepeatedField<UpstreamLocalityStats>,
    pub total_dropped_requests: u64,
    pub dropped_requests: ::protobuf::RepeatedField<ClusterStats_DroppedRequests>,
    pub load_report_interval: ::protobuf::SingularPtrField<::protobuf::well_known_types::Duration>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl ClusterStats {
    pub fn new() -> ClusterStats {
        ::std::default::Default::default()
    }

    // string cluster_name = 1;

    pub fn clear_cluster_name(&mut self) {
        self.cluster_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_cluster_name(&mut self, v: ::std::string::String) {
        self.cluster_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_cluster_name(&mut self) -> &mut ::std::string::String {
        &mut self.cluster_name
    }

    // Take field
    pub fn take_cluster_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.cluster_name, ::std::string::String::new())
    }

    pub fn get_cluster_name(&self) -> &str {
        &self.cluster_name
    }

    // string cluster_service_name = 6;

    pub fn clear_cluster_service_name(&mut self) {
        self.cluster_service_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_cluster_service_name(&mut self, v: ::std::string::String) {
        self.cluster_service_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_cluster_service_name(&mut self) -> &mut ::std::string::String {
        &mut self.cluster_service_name
    }

    // Take field
    pub fn take_cluster_service_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.cluster_service_name, ::std::string::String::new())
    }

    pub fn get_cluster_service_name(&self) -> &str {
        &self.cluster_service_name
    }

    // repeated .envoy.api.v2.endpoint.UpstreamLocalityStats upstream_locality_stats = 2;

    pub fn clear_upstream_locality_stats(&mut self) {
        self.upstream_locality_stats.clear();
    }

    // Param is passed by value, moved
    pub fn set_upstream_locality_stats(&mut self, v: ::protobuf::RepeatedField<UpstreamLocalityStats>) {
        self.upstream_locality_stats = v;
    }

    // Mutable pointer to the field.
    pub fn mut_upstream_locality_stats(&mut self) -> &mut ::protobuf::RepeatedField<UpstreamLocalityStats> {
        &mut self.upstream_locality_stats
    }

    // Take field
    pub fn take_upstream_locality_stats(&mut self) -> ::protobuf::RepeatedField<UpstreamLocalityStats> {
        ::std::mem::replace(&mut self.upstream_locality_stats, ::protobuf::RepeatedField::new())
    }

    pub fn get_upstream_locality_stats(&self) -> &[UpstreamLocalityStats] {
        &self.upstream_locality_stats
    }

    // uint64 total_dropped_requests = 3;

    pub fn clear_total_dropped_requests(&mut self) {
        self.total_dropped_requests = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_dropped_requests(&mut self, v: u64) {
        self.total_dropped_requests = v;
    }

    pub fn get_total_dropped_requests(&self) -> u64 {
        self.total_dropped_requests
    }

    // repeated .envoy.api.v2.endpoint.ClusterStats.DroppedRequests dropped_requests = 5;

    pub fn clear_dropped_requests(&mut self) {
        self.dropped_requests.clear();
    }

    // Param is passed by value, moved
    pub fn set_dropped_requests(&mut self, v: ::protobuf::RepeatedField<ClusterStats_DroppedRequests>) {
        self.dropped_requests = v;
    }

    // Mutable pointer to the field.
    pub fn mut_dropped_requests(&mut self) -> &mut ::protobuf::RepeatedField<ClusterStats_DroppedRequests> {
        &mut self.dropped_requests
    }

    // Take field
    pub fn take_dropped_requests(&mut self) -> ::protobuf::RepeatedField<ClusterStats_DroppedRequests> {
        ::std::mem::replace(&mut self.dropped_requests, ::protobuf::RepeatedField::new())
    }

    pub fn get_dropped_requests(&self) -> &[ClusterStats_DroppedRequests] {
        &self.dropped_requests
    }

    // .google.protobuf.Duration load_report_interval = 4;

    pub fn clear_load_report_interval(&mut self) {
        self.load_report_interval.clear();
    }

    pub fn has_load_report_interval(&self) -> bool {
        self.load_report_interval.is_some()
    }

    // Param is passed by value, moved
    pub fn set_load_report_interval(&mut self, v: ::protobuf::well_known_types::Duration) {
        self.load_report_interval = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_load_report_interval(&mut self) -> &mut ::protobuf::well_known_types::Duration {
        if self.load_report_interval.is_none() {
            self.load_report_interval.set_default();
        }
        self.load_report_interval.as_mut().unwrap()
    }

    // Take field
    pub fn take_load_report_interval(&mut self) -> ::protobuf::well_known_types::Duration {
        self.load_report_interval.take().unwrap_or_else(|| ::protobuf::well_known_types::Duration::new())
    }

    pub fn get_load_report_interval(&self) -> &::protobuf::well_known_types::Duration {
        self.load_report_interval.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Duration::default_instance())
    }
}

impl ::protobuf::Message for ClusterStats {
    fn is_initialized(&self) -> bool {
        for v in &self.upstream_locality_stats {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.dropped_requests {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.load_report_interval {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.cluster_name)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.cluster_service_name)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.upstream_locality_stats)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.total_dropped_requests = tmp;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.dropped_requests)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.load_report_interval)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.cluster_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.cluster_name);
        }
        if !self.cluster_service_name.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.cluster_service_name);
        }
        for value in &self.upstream_locality_stats {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.total_dropped_requests != 0 {
            my_size += ::protobuf::rt::value_size(3, self.total_dropped_requests, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.dropped_requests {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if let Some(ref v) = self.load_report_interval.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.cluster_name.is_empty() {
            os.write_string(1, &self.cluster_name)?;
        }
        if !self.cluster_service_name.is_empty() {
            os.write_string(6, &self.cluster_service_name)?;
        }
        for v in &self.upstream_locality_stats {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.total_dropped_requests != 0 {
            os.write_uint64(3, self.total_dropped_requests)?;
        }
        for v in &self.dropped_requests {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if let Some(ref v) = self.load_report_interval.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClusterStats {
        ClusterStats::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "cluster_name",
                    |m: &ClusterStats| { &m.cluster_name },
                    |m: &mut ClusterStats| { &mut m.cluster_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "cluster_service_name",
                    |m: &ClusterStats| { &m.cluster_service_name },
                    |m: &mut ClusterStats| { &mut m.cluster_service_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<UpstreamLocalityStats>>(
                    "upstream_locality_stats",
                    |m: &ClusterStats| { &m.upstream_locality_stats },
                    |m: &mut ClusterStats| { &mut m.upstream_locality_stats },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "total_dropped_requests",
                    |m: &ClusterStats| { &m.total_dropped_requests },
                    |m: &mut ClusterStats| { &mut m.total_dropped_requests },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ClusterStats_DroppedRequests>>(
                    "dropped_requests",
                    |m: &ClusterStats| { &m.dropped_requests },
                    |m: &mut ClusterStats| { &mut m.dropped_requests },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Duration>>(
                    "load_report_interval",
                    |m: &ClusterStats| { &m.load_report_interval },
                    |m: &mut ClusterStats| { &mut m.load_report_interval },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClusterStats>(
                    "ClusterStats",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClusterStats {
        static mut instance: ::protobuf::lazy::Lazy<ClusterStats> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClusterStats,
        };
        unsafe {
            instance.get(ClusterStats::new)
        }
    }
}

impl ::protobuf::Clear for ClusterStats {
    fn clear(&mut self) {
        self.clear_cluster_name();
        self.clear_cluster_service_name();
        self.clear_upstream_locality_stats();
        self.clear_total_dropped_requests();
        self.clear_dropped_requests();
        self.clear_load_report_interval();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClusterStats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClusterStats {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ClusterStats_DroppedRequests {
    // message fields
    pub category: ::std::string::String,
    pub dropped_count: u64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl ClusterStats_DroppedRequests {
    pub fn new() -> ClusterStats_DroppedRequests {
        ::std::default::Default::default()
    }

    // string category = 1;

    pub fn clear_category(&mut self) {
        self.category.clear();
    }

    // Param is passed by value, moved
    pub fn set_category(&mut self, v: ::std::string::String) {
        self.category = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_category(&mut self) -> &mut ::std::string::String {
        &mut self.category
    }

    // Take field
    pub fn take_category(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.category, ::std::string::String::new())
    }

    pub fn get_category(&self) -> &str {
        &self.category
    }

    // uint64 dropped_count = 2;

    pub fn clear_dropped_count(&mut self) {
        self.dropped_count = 0;
    }

    // Param is passed by value, moved
    pub fn set_dropped_count(&mut self, v: u64) {
        self.dropped_count = v;
    }

    pub fn get_dropped_count(&self) -> u64 {
        self.dropped_count
    }
}

impl ::protobuf::Message for ClusterStats_DroppedRequests {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.category)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.dropped_count = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.category.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.category);
        }
        if self.dropped_count != 0 {
            my_size += ::protobuf::rt::value_size(2, self.dropped_count, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.category.is_empty() {
            os.write_string(1, &self.category)?;
        }
        if self.dropped_count != 0 {
            os.write_uint64(2, self.dropped_count)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClusterStats_DroppedRequests {
        ClusterStats_DroppedRequests::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "category",
                    |m: &ClusterStats_DroppedRequests| { &m.category },
                    |m: &mut ClusterStats_DroppedRequests| { &mut m.category },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "dropped_count",
                    |m: &ClusterStats_DroppedRequests| { &m.dropped_count },
                    |m: &mut ClusterStats_DroppedRequests| { &mut m.dropped_count },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClusterStats_DroppedRequests>(
                    "ClusterStats_DroppedRequests",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClusterStats_DroppedRequests {
        static mut instance: ::protobuf::lazy::Lazy<ClusterStats_DroppedRequests> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClusterStats_DroppedRequests,
        };
        unsafe {
            instance.get(ClusterStats_DroppedRequests::new)
        }
    }
}

impl ::protobuf::Clear for ClusterStats_DroppedRequests {
    fn clear(&mut self) {
        self.clear_category();
        self.clear_dropped_count();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClusterStats_DroppedRequests {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClusterStats_DroppedRequests {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n'envoy/api/v2/endpoint/load_report.proto\x12\x15envoy.api.v2.endpoint\
    \x1a\x1fenvoy/api/v2/core/address.proto\x1a\x1cenvoy/api/v2/core/base.pr\
    oto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.\
    proto\x1a\x17validate/validate.proto\x1a\x14gogoproto/gogo.proto\"\xd9\
    \x03\n\x15UpstreamLocalityStats\x127\n\x08locality\x18\x01\x20\x01(\x0b2\
    \x1b.envoy.api.v2.core.LocalityR\x08locality\x12:\n\x19total_successful_\
    requests\x18\x02\x20\x01(\x04R\x17totalSuccessfulRequests\x12;\n\x1atota\
    l_requests_in_progress\x18\x03\x20\x01(\x04R\x17totalRequestsInProgress\
    \x120\n\x14total_error_requests\x18\x04\x20\x01(\x04R\x12totalErrorReque\
    sts\x12Z\n\x11load_metric_stats\x18\x05\x20\x03(\x0b2..envoy.api.v2.endp\
    oint.EndpointLoadMetricStatsR\x0floadMetricStats\x12d\n\x17upstream_endp\
    oint_stats\x18\x07\x20\x03(\x0b2,.envoy.api.v2.endpoint.UpstreamEndpoint\
    StatsR\x15upstreamEndpointStats\x12\x1a\n\x08priority\x18\x06\x20\x01(\r\
    R\x08priority\"\x89\x03\n\x15UpstreamEndpointStats\x124\n\x07address\x18\
    \x01\x20\x01(\x0b2\x1a.envoy.api.v2.core.AddressR\x07address\x123\n\x08m\
    etadata\x18\x06\x20\x01(\x0b2\x17.google.protobuf.StructR\x08metadata\
    \x12:\n\x19total_successful_requests\x18\x02\x20\x01(\x04R\x17totalSucce\
    ssfulRequests\x12;\n\x1atotal_requests_in_progress\x18\x03\x20\x01(\x04R\
    \x17totalRequestsInProgress\x120\n\x14total_error_requests\x18\x04\x20\
    \x01(\x04R\x12totalErrorRequests\x12Z\n\x11load_metric_stats\x18\x05\x20\
    \x03(\x0b2..envoy.api.v2.endpoint.EndpointLoadMetricStatsR\x0floadMetric\
    Stats\"\xb2\x01\n\x17EndpointLoadMetricStats\x12\x1f\n\x0bmetric_name\
    \x18\x01\x20\x01(\tR\nmetricName\x12H\n!num_requests_finished_with_metri\
    c\x18\x02\x20\x01(\x04R\x1dnumRequestsFinishedWithMetric\x12,\n\x12total\
    _metric_value\x18\x03\x20\x01(\x01R\x10totalMetricValue\"\xa2\x04\n\x0cC\
    lusterStats\x12,\n\x0ccluster_name\x18\x01\x20\x01(\tR\x0bclusterNameB\t\
    \xba\xe9\xc0\x03\x04r\x02\x20\x01\x120\n\x14cluster_service_name\x18\x06\
    \x20\x01(\tR\x12clusterServiceName\x12p\n\x17upstream_locality_stats\x18\
    \x02\x20\x03(\x0b2,.envoy.api.v2.endpoint.UpstreamLocalityStatsR\x15upst\
    reamLocalityStatsB\n\xba\xe9\xc0\x03\x05\x92\x01\x02\x08\x01\x124\n\x16t\
    otal_dropped_requests\x18\x03\x20\x01(\x04R\x14totalDroppedRequests\x12^\
    \n\x10dropped_requests\x18\x05\x20\x03(\x0b23.envoy.api.v2.endpoint.Clus\
    terStats.DroppedRequestsR\x0fdroppedRequests\x12K\n\x14load_report_inter\
    val\x18\x04\x20\x01(\x0b2\x19.google.protobuf.DurationR\x12loadReportInt\
    erval\x1a]\n\x0fDroppedRequests\x12%\n\x08category\x18\x01\x20\x01(\tR\
    \x08categoryB\t\xba\xe9\xc0\x03\x04r\x02\x20\x01\x12#\n\rdropped_count\
    \x18\x02\x20\x01(\x04R\x0cdroppedCountB8\n#io.envoyproxy.envoy.api.v2.en\
    dpointB\x0fLoadReportProtoP\x01J\xb54\n\x07\x12\x05\0\0\xa2\x01\x01\n\
    \x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\x08\x1d\n\x08\
    \n\x01\x08\x12\x03\x04\00\n\t\n\x02\x08\x08\x12\x03\x04\00\n\x08\n\x01\
    \x08\x12\x03\x05\0\"\n\t\n\x02\x08\n\x12\x03\x05\0\"\n\x08\n\x01\x08\x12\
    \x03\x06\0<\n\t\n\x02\x08\x01\x12\x03\x06\0<\n\t\n\x02\x03\0\x12\x03\x08\
    \x07(\n\t\n\x02\x03\x01\x12\x03\t\x07%\n\t\n\x02\x03\x02\x12\x03\x0b\x07\
    '\n\t\n\x02\x03\x03\x12\x03\x0c\x07%\n\t\n\x02\x03\x04\x12\x03\x0e\x07\
    \x20\n\t\n\x02\x03\x05\x12\x03\x0f\x07\x1d\n\xe0\x02\n\x02\x04\0\x12\x04\
    \x16\0:\x01\x1a\xd3\x02\x20These\x20are\x20stats\x20Envoy\x20reports\x20\
    to\x20GLB\x20every\x20so\x20often.\x20Report\x20frequency\x20is\n\x20def\
    ined\x20by\n\x20:ref:`LoadStatsResponse.load_reporting_interval<envoy_ap\
    i_field_load_stats.LoadStatsResponse.load_reporting_interval>`.\n\x20Sta\
    ts\x20per\x20upstream\x20region/zone\x20and\x20optionally\x20per\x20subz\
    one.\n\x20[#not-implemented-hide:]\x20Not\x20configuration.\x20TBD\x20ho\
    w\x20to\x20doc\x20proto\x20APIs.\n\n\n\n\x03\x04\0\x01\x12\x03\x16\x08\
    \x1d\n\x97\x01\n\x04\x04\0\x02\0\x12\x03\x19\x02\x1d\x1a\x89\x01\x20Name\
    \x20of\x20zone,\x20region\x20and\x20optionally\x20endpoint\x20group\x20t\
    hese\x20metrics\x20were\n\x20collected\x20from.\x20Zone\x20and\x20region\
    \x20names\x20could\x20be\x20empty\x20if\x20unknown.\n\n\r\n\x05\x04\0\
    \x02\0\x04\x12\x04\x19\x02\x16\x1f\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\
    \x19\x02\x0f\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x19\x10\x18\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x19\x1b\x1c\n\x95\x03\n\x04\x04\0\x02\x01\x12\
    \x03&\x02'\x1a\x87\x03\x20The\x20total\x20number\x20of\x20requests\x20se\
    nt\x20by\x20this\x20Envoy\x20since\x20the\x20last\x20report.\x20This\n\
    \x20information\x20is\x20aggregated\x20over\x20all\x20the\x20upstream\
    \x20Endpoints.\x20total_requests\n\x20can\x20be\x20inferred\x20from:\n\n\
    \x20..\x20code-block::\x20none\n\n\x20\x20\x20total_requests\x20=\x20tot\
    al_successful_requests\x20+\x20total_requests_in_progress\x20+\n\x20\x20\
    \x20\x20\x20total_error_requests\n\n\x20The\x20total\x20number\x20of\x20\
    requests\x20successfully\x20completed\x20by\x20the\x20endpoints\x20in\
    \x20the\n\x20locality.\n\n\r\n\x05\x04\0\x02\x01\x04\x12\x04&\x02\x19\
    \x1d\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03&\x02\x08\n\x0c\n\x05\x04\0\
    \x02\x01\x01\x12\x03&\t\"\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03&%&\n6\n\
    \x04\x04\0\x02\x02\x12\x03)\x02(\x1a)\x20The\x20total\x20number\x20of\
    \x20unfinished\x20requests\n\n\r\n\x05\x04\0\x02\x02\x04\x12\x04)\x02&'\
    \n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03)\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x02\x01\x12\x03)\t#\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03)&'\n\x86\x01\
    \n\x04\x04\0\x02\x03\x12\x03-\x02\"\x1ay\x20The\x20total\x20number\x20of\
    \x20requests\x20that\x20failed\x20due\x20to\x20errors\x20at\x20the\x20en\
    dpoint,\n\x20aggregated\x20over\x20all\x20endpoints\x20in\x20the\x20loca\
    lity.\n\n\r\n\x05\x04\0\x02\x03\x04\x12\x04-\x02)(\n\x0c\n\x05\x04\0\x02\
    \x03\x05\x12\x03-\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03-\t\x1d\n\
    \x0c\n\x05\x04\0\x02\x03\x03\x12\x03-\x20!\n:\n\x04\x04\0\x02\x04\x12\
    \x030\x029\x1a-\x20Stats\x20for\x20multi-dimensional\x20load\x20balancin\
    g.\n\n\x0c\n\x05\x04\0\x02\x04\x04\x12\x030\x02\n\n\x0c\n\x05\x04\0\x02\
    \x04\x06\x12\x030\x0b\"\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x030#4\n\x0c\n\
    \x05\x04\0\x02\x04\x03\x12\x03078\n\x8e\x02\n\x04\x04\0\x02\x05\x12\x035\
    \x02=\x1a\x80\x02\x20Endpoint\x20granularity\x20stats\x20information\x20\
    for\x20this\x20locality.\x20This\x20information\n\x20is\x20populated\x20\
    if\x20the\x20Server\x20requests\x20it\x20by\x20setting\n\x20:ref:`LoadSt\
    atsResponse.report_endpoint_granularity<envoy_api_field_load_stats.LoadS\
    tatsResponse.report_endpoint_granularity>`.\n\n\x0c\n\x05\x04\0\x02\x05\
    \x04\x12\x035\x02\n\n\x0c\n\x05\x04\0\x02\x05\x06\x12\x035\x0b\x20\n\x0c\
    \n\x05\x04\0\x02\x05\x01\x12\x035!8\n\x0c\n\x05\x04\0\x02\x05\x03\x12\
    \x035;<\nn\n\x04\x04\0\x02\x06\x12\x039\x02\x16\x1aa\x20[#not-implemente\
    d-hide:]\x20The\x20priority\x20of\x20the\x20endpoint\x20group\x20these\
    \x20metrics\n\x20were\x20collected\x20from.\n\n\r\n\x05\x04\0\x02\x06\
    \x04\x12\x049\x025=\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x039\x02\x08\n\x0c\
    \n\x05\x04\0\x02\x06\x01\x12\x039\t\x11\n\x0c\n\x05\x04\0\x02\x06\x03\
    \x12\x039\x14\x15\n\n\n\x02\x04\x01\x12\x04<\0e\x01\n\n\n\x03\x04\x01\
    \x01\x12\x03<\x08\x1d\n%\n\x04\x04\x01\x02\0\x12\x03>\x02\x1b\x1a\x18\
    \x20Upstream\x20host\x20address.\n\n\r\n\x05\x04\x01\x02\0\x04\x12\x04>\
    \x02<\x1f\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03>\x02\x0e\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x03>\x0f\x16\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03>\
    \x19\x1a\n\x85\x01\n\x04\x04\x01\x02\x01\x12\x03B\x02&\x1ax\x20Opaque\
    \x20and\x20implementation\x20dependent\x20metadata\x20of\x20the\n\x20end\
    point.\x20Envoy\x20will\x20pass\x20this\x20directly\x20to\x20the\x20mana\
    gement\x20server.\n\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04B\x02>\x1b\n\
    \x0c\n\x05\x04\x01\x02\x01\x06\x12\x03B\x02\x18\n\x0c\n\x05\x04\x01\x02\
    \x01\x01\x12\x03B\x19!\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03B$%\n\xd1\
    \x05\n\x04\x04\x01\x02\x02\x12\x03R\x02'\x1a\xc3\x05\x20The\x20total\x20\
    number\x20of\x20requests\x20successfully\x20completed\x20by\x20the\x20en\
    dpoint.\x20A\n\x20single\x20HTTP\x20or\x20gRPC\x20request\x20or\x20strea\
    m\x20is\x20counted\x20as\x20one\x20request.\x20A\x20TCP\n\x20connection\
    \x20is\x20also\x20treated\x20as\x20one\x20request.\x20There\x20is\x20no\
    \x20explicit\n\x20total_requests\x20field\x20below\x20for\x20an\x20endpo\
    int,\x20but\x20it\x20may\x20be\x20inferred\x20from:\n\n\x20..\x20code-bl\
    ock::\x20none\n\n\x20\x20\x20total_requests\x20=\x20total_successful_req\
    uests\x20+\x20total_requests_in_progress\x20+\n\x20\x20\x20\x20\x20total\
    _error_requests\n\n\x20The\x20total\x20number\x20of\x20requests\x20succe\
    ssfully\x20completed\x20by\x20the\x20endpoints\x20in\x20the\n\x20localit\
    y.\x20These\x20include\x20non-5xx\x20responses\x20for\x20HTTP,\x20where\
    \x20errors\n\x20originate\x20at\x20the\x20client\x20and\x20the\x20endpoi\
    nt\x20responded\x20successfully.\x20For\x20gRPC,\n\x20the\x20grpc-status\
    \x20values\x20are\x20those\x20not\x20covered\x20by\x20total_error_reques\
    ts\x20below.\n\n\r\n\x05\x04\x01\x02\x02\x04\x12\x04R\x02B&\n\x0c\n\x05\
    \x04\x01\x02\x02\x05\x12\x03R\x02\x08\n\x0c\n\x05\x04\x01\x02\x02\x01\
    \x12\x03R\t\"\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03R%&\nI\n\x04\x04\
    \x01\x02\x03\x12\x03U\x02(\x1a<\x20The\x20total\x20number\x20of\x20unfin\
    ished\x20requests\x20for\x20this\x20endpoint.\n\n\r\n\x05\x04\x01\x02\
    \x03\x04\x12\x04U\x02R'\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03U\x02\x08\
    \n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03U\t#\n\x0c\n\x05\x04\x01\x02\x03\
    \x03\x12\x03U&'\n\x95\x02\n\x04\x04\x01\x02\x04\x12\x03a\x02\"\x1a\x87\
    \x02\x20The\x20total\x20number\x20of\x20requests\x20that\x20failed\x20du\
    e\x20to\x20errors\x20at\x20the\x20endpoint.\n\x20For\x20HTTP\x20these\
    \x20are\x20responses\x20with\x205xx\x20status\x20codes\x20and\x20for\x20\
    gRPC\x20the\n\x20grpc-status\x20values:\n\n\x20\x20\x20-\x20DeadlineExce\
    eded\n\x20\x20\x20-\x20Unimplemented\n\x20\x20\x20-\x20Internal\n\x20\
    \x20\x20-\x20Unavailable\n\x20\x20\x20-\x20Unknown\n\x20\x20\x20-\x20Dat\
    aLoss\n\n\r\n\x05\x04\x01\x02\x04\x04\x12\x04a\x02U(\n\x0c\n\x05\x04\x01\
    \x02\x04\x05\x12\x03a\x02\x08\n\x0c\n\x05\x04\x01\x02\x04\x01\x12\x03a\t\
    \x1d\n\x0c\n\x05\x04\x01\x02\x04\x03\x12\x03a\x20!\n:\n\x04\x04\x01\x02\
    \x05\x12\x03d\x029\x1a-\x20Stats\x20for\x20multi-dimensional\x20load\x20\
    balancing.\n\n\x0c\n\x05\x04\x01\x02\x05\x04\x12\x03d\x02\n\n\x0c\n\x05\
    \x04\x01\x02\x05\x06\x12\x03d\x0b\"\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\
    \x03d#4\n\x0c\n\x05\x04\x01\x02\x05\x03\x12\x03d78\nT\n\x02\x04\x02\x12\
    \x04h\0r\x01\x1aH\x20[#not-implemented-hide:]\x20Not\x20configuration.\
    \x20TBD\x20how\x20to\x20doc\x20proto\x20APIs.\n\n\n\n\x03\x04\x02\x01\
    \x12\x03h\x08\x1f\n0\n\x04\x04\x02\x02\0\x12\x03j\x02\x19\x1a#\x20Name\
    \x20of\x20the\x20metric;\x20may\x20be\x20empty.\n\n\r\n\x05\x04\x02\x02\
    \0\x04\x12\x04j\x02h!\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03j\x02\x08\n\
    \x0c\n\x05\x04\x02\x02\0\x01\x12\x03j\t\x14\n\x0c\n\x05\x04\x02\x02\0\
    \x03\x12\x03j\x17\x18\nF\n\x04\x04\x02\x02\x01\x12\x03m\x02/\x1a9\x20Num\
    ber\x20of\x20calls\x20that\x20finished\x20and\x20included\x20this\x20met\
    ric.\n\n\r\n\x05\x04\x02\x02\x01\x04\x12\x04m\x02j\x19\n\x0c\n\x05\x04\
    \x02\x02\x01\x05\x12\x03m\x02\x08\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\
    \x03m\t*\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03m-.\nq\n\x04\x04\x02\x02\
    \x02\x12\x03q\x02\x20\x1ad\x20Sum\x20of\x20metric\x20values\x20across\
    \x20all\x20calls\x20that\x20finished\x20with\x20this\x20metric\x20for\n\
    \x20load_reporting_interval.\n\n\r\n\x05\x04\x02\x02\x02\x04\x12\x04q\
    \x02m/\n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x03q\x02\x08\n\x0c\n\x05\x04\
    \x02\x02\x02\x01\x12\x03q\t\x1b\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03q\
    \x1e\x1f\n\xf2\x01\n\x02\x04\x03\x12\x05x\0\xa2\x01\x01\x1a\xe4\x01\x20P\
    er\x20cluster\x20load\x20stats.\x20Envoy\x20reports\x20these\x20stats\
    \x20a\x20management\x20server\x20in\x20a\n\x20:ref:`LoadStatsRequest<env\
    oy_api_msg_load_stats.LoadStatsRequest>`\n\x20[#not-implemented-hide:]\
    \x20Not\x20configuration.\x20TBD\x20how\x20to\x20doc\x20proto\x20APIs.\n\
    \x20Next\x20ID:\x207\n\n\n\n\x03\x04\x03\x01\x12\x03x\x08\x14\n'\n\x04\
    \x04\x03\x02\0\x12\x03z\x02B\x1a\x1a\x20The\x20name\x20of\x20the\x20clus\
    ter.\n\n\r\n\x05\x04\x03\x02\0\x04\x12\x04z\x02x\x16\n\x0c\n\x05\x04\x03\
    \x02\0\x05\x12\x03z\x02\x08\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03z\t\x15\
    \n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03z\x18\x19\n\x0c\n\x05\x04\x03\x02\
    \0\x08\x12\x03z\x1aA\n\x11\n\n\x04\x03\x02\0\x08\x97\x8d8\x0e\x04\x12\
    \x03z\x1b@\n\xdf\x01\n\x04\x04\x03\x02\x01\x12\x03\x7f\x02\"\x1a\xd1\x01\
    \x20The\x20eds_cluster_config\x20service_name\x20of\x20the\x20cluster.\n\
    \x20It's\x20possible\x20that\x20two\x20clusters\x20send\x20the\x20same\
    \x20service_name\x20to\x20EDS,\n\x20in\x20that\x20case,\x20the\x20manage\
    ment\x20server\x20is\x20supposed\x20to\x20do\x20aggregation\x20on\x20the\
    \x20load\x20reports.\n\n\r\n\x05\x04\x03\x02\x01\x04\x12\x04\x7f\x02zB\n\
    \x0c\n\x05\x04\x03\x02\x01\x05\x12\x03\x7f\x02\x08\n\x0c\n\x05\x04\x03\
    \x02\x01\x01\x12\x03\x7f\t\x1d\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\x03\
    \x7f\x20!\n$\n\x04\x04\x03\x02\x02\x12\x06\x82\x01\x02\x83\x011\x1a\x14\
    \x20Need\x20at\x20least\x20one.\n\n\r\n\x05\x04\x03\x02\x02\x04\x12\x04\
    \x82\x01\x02\n\n\r\n\x05\x04\x03\x02\x02\x06\x12\x04\x82\x01\x0b\x20\n\r\
    \n\x05\x04\x03\x02\x02\x01\x12\x04\x82\x01!8\n\r\n\x05\x04\x03\x02\x02\
    \x03\x12\x04\x82\x01;<\n\r\n\x05\x04\x03\x02\x02\x08\x12\x04\x83\x01\x06\
    0\n\x12\n\n\x04\x03\x02\x02\x08\x97\x8d8\x12\x01\x12\x04\x83\x01\x07/\n\
    \xb2\x04\n\x04\x04\x03\x02\x03\x12\x04\x91\x01\x02$\x1a\xa3\x04\x20Clust\
    er-level\x20stats\x20such\x20as\x20total_successful_requests\x20may\x20b\
    e\x20computed\x20by\n\x20summing\x20upstream_locality_stats.\x20In\x20ad\
    dition,\x20below\x20there\x20are\x20additional\n\x20cluster-wide\x20stat\
    s.\x20The\x20following\x20total_requests\x20equality\x20holds\x20at\x20t\
    he\n\x20cluster-level:\n\n\x20..\x20code-block::\x20none\n\n\x20\x20\x20\
    sum_locality(total_successful_requests)\x20+\x20sum_locality(total_reque\
    sts_in_progress)\x20+\n\x20\x20\x20\x20\x20sum_locality(total_error_requ\
    ests)\x20+\x20total_dropped_requests`\n\n\x20The\x20total\x20number\x20o\
    f\x20dropped\x20requests.\x20This\x20covers\x20requests\n\x20deliberatel\
    y\x20dropped\x20by\x20the\x20drop_overload\x20policy\x20and\x20circuit\
    \x20breaking.\n\n\x0f\n\x05\x04\x03\x02\x03\x04\x12\x06\x91\x01\x02\x83\
    \x011\n\r\n\x05\x04\x03\x02\x03\x05\x12\x04\x91\x01\x02\x08\n\r\n\x05\
    \x04\x03\x02\x03\x01\x12\x04\x91\x01\t\x1f\n\r\n\x05\x04\x03\x02\x03\x03\
    \x12\x04\x91\x01\"#\n\x0e\n\x04\x04\x03\x03\0\x12\x06\x93\x01\x02\x98\
    \x01\x03\n\r\n\x05\x04\x03\x03\0\x01\x12\x04\x93\x01\n\x19\n@\n\x06\x04\
    \x03\x03\0\x02\0\x12\x04\x95\x01\x04@\x1a0\x20Identifier\x20for\x20the\
    \x20policy\x20specifying\x20the\x20drop.\n\n\x11\n\x07\x04\x03\x03\0\x02\
    \0\x04\x12\x06\x95\x01\x04\x93\x01\x1b\n\x0f\n\x07\x04\x03\x03\0\x02\0\
    \x05\x12\x04\x95\x01\x04\n\n\x0f\n\x07\x04\x03\x03\0\x02\0\x01\x12\x04\
    \x95\x01\x0b\x13\n\x0f\n\x07\x04\x03\x03\0\x02\0\x03\x12\x04\x95\x01\x16\
    \x17\n\x0f\n\x07\x04\x03\x03\0\x02\0\x08\x12\x04\x95\x01\x18?\n\x14\n\
    \x0c\x04\x03\x03\0\x02\0\x08\x97\x8d8\x0e\x04\x12\x04\x95\x01\x19>\nQ\n\
    \x06\x04\x03\x03\0\x02\x01\x12\x04\x97\x01\x04\x1d\x1aA\x20Total\x20numb\
    er\x20of\x20deliberately\x20dropped\x20requests\x20for\x20the\x20categor\
    y.\n\n\x11\n\x07\x04\x03\x03\0\x02\x01\x04\x12\x06\x97\x01\x04\x95\x01@\
    \n\x0f\n\x07\x04\x03\x03\0\x02\x01\x05\x12\x04\x97\x01\x04\n\n\x0f\n\x07\
    \x04\x03\x03\0\x02\x01\x01\x12\x04\x97\x01\x0b\x18\n\x0f\n\x07\x04\x03\
    \x03\0\x02\x01\x03\x12\x04\x97\x01\x1b\x1c\nx\n\x04\x04\x03\x02\x04\x12\
    \x04\x9b\x01\x020\x1aj\x20Information\x20about\x20deliberately\x20droppe\
    d\x20requests\x20for\x20each\x20category\x20specified\n\x20in\x20the\x20\
    DropOverload\x20policy.\n\n\r\n\x05\x04\x03\x02\x04\x04\x12\x04\x9b\x01\
    \x02\n\n\r\n\x05\x04\x03\x02\x04\x06\x12\x04\x9b\x01\x0b\x1a\n\r\n\x05\
    \x04\x03\x02\x04\x01\x12\x04\x9b\x01\x1b+\n\r\n\x05\x04\x03\x02\x04\x03\
    \x12\x04\x9b\x01./\n\xed\x02\n\x04\x04\x03\x02\x05\x12\x04\xa1\x01\x024\
    \x1a\xde\x02\x20Period\x20over\x20which\x20the\x20actual\x20load\x20repo\
    rt\x20occurred.\x20This\x20will\x20be\x20guaranteed\x20to\x20include\x20\
    every\n\x20request\x20reported.\x20Due\x20to\x20system\x20load\x20and\
    \x20delays\x20between\x20the\x20*LoadStatsRequest*\x20sent\x20from\x20En\
    voy\n\x20and\x20the\x20*LoadStatsResponse*\x20message\x20sent\x20from\
    \x20the\x20management\x20server,\x20this\x20may\x20be\x20longer\x20than\
    \n\x20the\x20requested\x20load\x20reporting\x20interval\x20in\x20the\x20\
    *LoadStatsResponse*.\n\n\x0f\n\x05\x04\x03\x02\x05\x04\x12\x06\xa1\x01\
    \x02\x9b\x010\n\r\n\x05\x04\x03\x02\x05\x06\x12\x04\xa1\x01\x02\x1a\n\r\
    \n\x05\x04\x03\x02\x05\x01\x12\x04\xa1\x01\x1b/\n\r\n\x05\x04\x03\x02\
    \x05\x03\x12\x04\xa1\x0123b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
