// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Percent {
    // message fields
    pub value: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl Percent {
    pub fn new() -> Percent {
        ::std::default::Default::default()
    }

    // double value = 1;

    pub fn clear_value(&mut self) {
        self.value = 0.;
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: f64) {
        self.value = v;
    }

    pub fn get_value(&self) -> f64 {
        self.value
    }
}

impl ::protobuf::Message for Percent {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.value = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.value != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.value != 0. {
            os.write_double(1, self.value)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Percent {
        Percent::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "value",
                    |m: &Percent| { &m.value },
                    |m: &mut Percent| { &mut m.value },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Percent>(
                    "Percent",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Percent {
        static mut instance: ::protobuf::lazy::Lazy<Percent> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Percent,
        };
        unsafe {
            instance.get(Percent::new)
        }
    }
}

impl ::protobuf::Clear for Percent {
    fn clear(&mut self) {
        self.clear_value();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Percent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Percent {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct FractionalPercent {
    // message fields
    pub numerator: u32,
    pub denominator: FractionalPercent_DenominatorType,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl FractionalPercent {
    pub fn new() -> FractionalPercent {
        ::std::default::Default::default()
    }

    // uint32 numerator = 1;

    pub fn clear_numerator(&mut self) {
        self.numerator = 0;
    }

    // Param is passed by value, moved
    pub fn set_numerator(&mut self, v: u32) {
        self.numerator = v;
    }

    pub fn get_numerator(&self) -> u32 {
        self.numerator
    }

    // .envoy.type.FractionalPercent.DenominatorType denominator = 2;

    pub fn clear_denominator(&mut self) {
        self.denominator = FractionalPercent_DenominatorType::HUNDRED;
    }

    // Param is passed by value, moved
    pub fn set_denominator(&mut self, v: FractionalPercent_DenominatorType) {
        self.denominator = v;
    }

    pub fn get_denominator(&self) -> FractionalPercent_DenominatorType {
        self.denominator
    }
}

impl ::protobuf::Message for FractionalPercent {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.numerator = tmp;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.denominator, 2, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.numerator != 0 {
            my_size += ::protobuf::rt::value_size(1, self.numerator, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.denominator != FractionalPercent_DenominatorType::HUNDRED {
            my_size += ::protobuf::rt::enum_size(2, self.denominator);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.numerator != 0 {
            os.write_uint32(1, self.numerator)?;
        }
        if self.denominator != FractionalPercent_DenominatorType::HUNDRED {
            os.write_enum(2, self.denominator.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FractionalPercent {
        FractionalPercent::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "numerator",
                    |m: &FractionalPercent| { &m.numerator },
                    |m: &mut FractionalPercent| { &mut m.numerator },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<FractionalPercent_DenominatorType>>(
                    "denominator",
                    |m: &FractionalPercent| { &m.denominator },
                    |m: &mut FractionalPercent| { &mut m.denominator },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<FractionalPercent>(
                    "FractionalPercent",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static FractionalPercent {
        static mut instance: ::protobuf::lazy::Lazy<FractionalPercent> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const FractionalPercent,
        };
        unsafe {
            instance.get(FractionalPercent::new)
        }
    }
}

impl ::protobuf::Clear for FractionalPercent {
    fn clear(&mut self) {
        self.clear_numerator();
        self.clear_denominator();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FractionalPercent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FractionalPercent {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum FractionalPercent_DenominatorType {
    HUNDRED = 0,
    TEN_THOUSAND = 1,
    MILLION = 2,
}

impl ::protobuf::ProtobufEnum for FractionalPercent_DenominatorType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FractionalPercent_DenominatorType> {
        match value {
            0 => ::std::option::Option::Some(FractionalPercent_DenominatorType::HUNDRED),
            1 => ::std::option::Option::Some(FractionalPercent_DenominatorType::TEN_THOUSAND),
            2 => ::std::option::Option::Some(FractionalPercent_DenominatorType::MILLION),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [FractionalPercent_DenominatorType] = &[
            FractionalPercent_DenominatorType::HUNDRED,
            FractionalPercent_DenominatorType::TEN_THOUSAND,
            FractionalPercent_DenominatorType::MILLION,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("FractionalPercent_DenominatorType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for FractionalPercent_DenominatorType {
}

impl ::std::default::Default for FractionalPercent_DenominatorType {
    fn default() -> Self {
        FractionalPercent_DenominatorType::HUNDRED
    }
}

impl ::protobuf::reflect::ProtobufValue for FractionalPercent_DenominatorType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18envoy/type/percent.proto\x12\nenvoy.type\x1a\x17validate/validate.\
    proto\x1a\x14gogoproto/gogo.proto\":\n\x07Percent\x12/\n\x05value\x18\
    \x01\x20\x01(\x01R\x05valueB\x19\xba\xe9\xc0\x03\x14\x12\x12\x19\0\0\0\0\
    \0\0Y@)\0\0\0\0\0\0\0\0\"\xcd\x01\n\x11FractionalPercent\x12\x1c\n\tnume\
    rator\x18\x01\x20\x01(\rR\tnumerator\x12[\n\x0bdenominator\x18\x02\x20\
    \x01(\x0e2-.envoy.type.FractionalPercent.DenominatorTypeR\x0bdenominator\
    B\n\xba\xe9\xc0\x03\x05\x82\x01\x02\x10\x01\"=\n\x0fDenominatorType\x12\
    \x0b\n\x07HUNDRED\x10\0\x12\x10\n\x0cTEN_THOUSAND\x10\x01\x12\x0b\n\x07M\
    ILLION\x10\x02B.\n\x18io.envoyproxy.envoy.typeB\x0cPercentProtoP\x01\xa8\
    \xe2\x1e\x01J\xa0\x0b\n\x06\x12\x04\0\03\x01\n\x08\n\x01\x0c\x12\x03\0\0\
    \x12\n\x08\n\x01\x02\x12\x03\x02\x08\x12\n\x08\n\x01\x08\x12\x03\x04\0-\
    \n\t\n\x02\x08\x08\x12\x03\x04\0-\n\x08\n\x01\x08\x12\x03\x05\0\"\n\t\n\
    \x02\x08\n\x12\x03\x05\0\"\n\x08\n\x01\x08\x12\x03\x06\01\n\t\n\x02\x08\
    \x01\x12\x03\x06\01\n\t\n\x02\x03\0\x12\x03\x08\x07\x20\n\t\n\x02\x03\
    \x01\x12\x03\t\x07\x1d\n\x08\n\x01\x08\x12\x03\x0b\0$\n\x0b\n\x04\x08\
    \xa5\xec\x03\x12\x03\x0b\0$\n_\n\x02\x04\0\x12\x04\x10\0\x12\x01\x1a5\
    \x20Identifies\x20a\x20percentage,\x20in\x20the\x20range\x20[0.0,\x20100\
    .0].\n2\x1c\x20[#protodoc-title:\x20Percent]\n\n\n\n\x03\x04\0\x01\x12\
    \x03\x10\x08\x0f\n\x0b\n\x04\x04\0\x02\0\x12\x03\x11\x02B\n\r\n\x05\x04\
    \0\x02\0\x04\x12\x04\x11\x02\x10\x11\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\
    \x11\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x11\t\x0e\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x11\x11\x12\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03\
    \x11\x13A\n\x10\n\t\x04\0\x02\0\x08\x97\x8d8\x02\x12\x03\x11\x14@\n\xe2\
    \x02\n\x02\x04\x01\x12\x04\x1a\03\x01\x1a\xd5\x02\x20A\x20fractional\x20\
    percentage\x20is\x20used\x20in\x20cases\x20in\x20which\x20for\x20perform\
    ance\x20reasons\x20performing\x20floating\n\x20point\x20to\x20integer\
    \x20conversions\x20during\x20randomness\x20calculations\x20is\x20undesir\
    able.\x20The\x20message\x20includes\n\x20both\x20a\x20numerator\x20and\
    \x20denominator\x20that\x20together\x20determine\x20the\x20final\x20frac\
    tional\x20value.\n\n\x20*\x20**Example**:\x201/100\x20=\x201%.\n\x20*\
    \x20**Example**:\x203/10000\x20=\x200.03%.\n\n\n\n\x03\x04\x01\x01\x12\
    \x03\x1a\x08\x19\n6\n\x04\x04\x01\x02\0\x12\x03\x1c\x02\x17\x1a)\x20Spec\
    ifies\x20the\x20numerator.\x20Defaults\x20to\x200.\n\n\r\n\x05\x04\x01\
    \x02\0\x04\x12\x04\x1c\x02\x1a\x1b\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\
    \x1c\x02\x08\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1c\t\x12\n\x0c\n\x05\
    \x04\x01\x02\0\x03\x12\x03\x1c\x15\x16\nN\n\x04\x04\x01\x04\0\x12\x04\
    \x1f\x02.\x03\x1a@\x20Fraction\x20percentages\x20support\x20several\x20f\
    ixed\x20denominator\x20values.\n\n\x0c\n\x05\x04\x01\x04\0\x01\x12\x03\
    \x1f\x07\x16\n0\n\x06\x04\x01\x04\0\x02\0\x12\x03#\x04\x10\x1a!\x20100.\
    \n\n\x20**Example**:\x201/100\x20=\x201%.\n\n\x0e\n\x07\x04\x01\x04\0\
    \x02\0\x01\x12\x03#\x04\x0b\n\x0e\n\x07\x04\x01\x04\0\x02\0\x02\x12\x03#\
    \x0e\x0f\n8\n\x06\x04\x01\x04\0\x02\x01\x12\x03(\x04\x15\x1a)\x2010,000.\
    \n\n\x20**Example**:\x201/10000\x20=\x200.01%.\n\n\x0e\n\x07\x04\x01\x04\
    \0\x02\x01\x01\x12\x03(\x04\x10\n\x0e\n\x07\x04\x01\x04\0\x02\x01\x02\
    \x12\x03(\x13\x14\n?\n\x06\x04\x01\x04\0\x02\x02\x12\x03-\x04\x10\x1a0\
    \x201,000,000.\n\n\x20**Example**:\x201/1000000\x20=\x200.0001%.\n\n\x0e\
    \n\x07\x04\x01\x04\0\x02\x02\x01\x12\x03-\x04\x0b\n\x0e\n\x07\x04\x01\
    \x04\0\x02\x02\x02\x12\x03-\x0e\x0f\n\x9b\x01\n\x04\x04\x01\x02\x01\x12\
    \x032\x02N\x1a\x8d\x01\x20Specifies\x20the\x20denominator.\x20If\x20the\
    \x20denominator\x20specified\x20is\x20less\x20than\x20the\x20numerator,\
    \x20the\x20final\n\x20fractional\x20percentage\x20is\x20capped\x20at\x20\
    1\x20(100%).\n\n\r\n\x05\x04\x01\x02\x01\x04\x12\x042\x02.\x03\n\x0c\n\
    \x05\x04\x01\x02\x01\x06\x12\x032\x02\x11\n\x0c\n\x05\x04\x01\x02\x01\
    \x01\x12\x032\x12\x1d\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x032\x20!\n\
    \x0c\n\x05\x04\x01\x02\x01\x08\x12\x032\"M\n\x11\n\n\x04\x01\x02\x01\x08\
    \x97\x8d8\x10\x02\x12\x032#Lb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
