// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct TcpProtocolOptions {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl TcpProtocolOptions {
    pub fn new() -> TcpProtocolOptions {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for TcpProtocolOptions {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TcpProtocolOptions {
        TcpProtocolOptions::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let fields = ::std::vec::Vec::new();
                ::protobuf::reflect::MessageDescriptor::new::<TcpProtocolOptions>(
                    "TcpProtocolOptions",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static TcpProtocolOptions {
        static mut instance: ::protobuf::lazy::Lazy<TcpProtocolOptions> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const TcpProtocolOptions,
        };
        unsafe {
            instance.get(TcpProtocolOptions::new)
        }
    }
}

impl ::protobuf::Clear for TcpProtocolOptions {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TcpProtocolOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TcpProtocolOptions {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct HttpProtocolOptions {
    // message fields
    pub idle_timeout: ::protobuf::SingularPtrField<::protobuf::well_known_types::Duration>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl HttpProtocolOptions {
    pub fn new() -> HttpProtocolOptions {
        ::std::default::Default::default()
    }

    // .google.protobuf.Duration idle_timeout = 1;

    pub fn clear_idle_timeout(&mut self) {
        self.idle_timeout.clear();
    }

    pub fn has_idle_timeout(&self) -> bool {
        self.idle_timeout.is_some()
    }

    // Param is passed by value, moved
    pub fn set_idle_timeout(&mut self, v: ::protobuf::well_known_types::Duration) {
        self.idle_timeout = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_idle_timeout(&mut self) -> &mut ::protobuf::well_known_types::Duration {
        if self.idle_timeout.is_none() {
            self.idle_timeout.set_default();
        }
        self.idle_timeout.as_mut().unwrap()
    }

    // Take field
    pub fn take_idle_timeout(&mut self) -> ::protobuf::well_known_types::Duration {
        self.idle_timeout.take().unwrap_or_else(|| ::protobuf::well_known_types::Duration::new())
    }

    pub fn get_idle_timeout(&self) -> &::protobuf::well_known_types::Duration {
        self.idle_timeout.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::Duration::default_instance())
    }
}

impl ::protobuf::Message for HttpProtocolOptions {
    fn is_initialized(&self) -> bool {
        for v in &self.idle_timeout {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.idle_timeout)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.idle_timeout.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.idle_timeout.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HttpProtocolOptions {
        HttpProtocolOptions::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Duration>>(
                    "idle_timeout",
                    |m: &HttpProtocolOptions| { &m.idle_timeout },
                    |m: &mut HttpProtocolOptions| { &mut m.idle_timeout },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<HttpProtocolOptions>(
                    "HttpProtocolOptions",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static HttpProtocolOptions {
        static mut instance: ::protobuf::lazy::Lazy<HttpProtocolOptions> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const HttpProtocolOptions,
        };
        unsafe {
            instance.get(HttpProtocolOptions::new)
        }
    }
}

impl ::protobuf::Clear for HttpProtocolOptions {
    fn clear(&mut self) {
        self.clear_idle_timeout();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HttpProtocolOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HttpProtocolOptions {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Http1ProtocolOptions {
    // message fields
    pub allow_absolute_url: ::protobuf::SingularPtrField<::protobuf::well_known_types::BoolValue>,
    pub accept_http_10: bool,
    pub default_host_for_http_10: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl Http1ProtocolOptions {
    pub fn new() -> Http1ProtocolOptions {
        ::std::default::Default::default()
    }

    // .google.protobuf.BoolValue allow_absolute_url = 1;

    pub fn clear_allow_absolute_url(&mut self) {
        self.allow_absolute_url.clear();
    }

    pub fn has_allow_absolute_url(&self) -> bool {
        self.allow_absolute_url.is_some()
    }

    // Param is passed by value, moved
    pub fn set_allow_absolute_url(&mut self, v: ::protobuf::well_known_types::BoolValue) {
        self.allow_absolute_url = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_allow_absolute_url(&mut self) -> &mut ::protobuf::well_known_types::BoolValue {
        if self.allow_absolute_url.is_none() {
            self.allow_absolute_url.set_default();
        }
        self.allow_absolute_url.as_mut().unwrap()
    }

    // Take field
    pub fn take_allow_absolute_url(&mut self) -> ::protobuf::well_known_types::BoolValue {
        self.allow_absolute_url.take().unwrap_or_else(|| ::protobuf::well_known_types::BoolValue::new())
    }

    pub fn get_allow_absolute_url(&self) -> &::protobuf::well_known_types::BoolValue {
        self.allow_absolute_url.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::BoolValue::default_instance())
    }

    // bool accept_http_10 = 2;

    pub fn clear_accept_http_10(&mut self) {
        self.accept_http_10 = false;
    }

    // Param is passed by value, moved
    pub fn set_accept_http_10(&mut self, v: bool) {
        self.accept_http_10 = v;
    }

    pub fn get_accept_http_10(&self) -> bool {
        self.accept_http_10
    }

    // string default_host_for_http_10 = 3;

    pub fn clear_default_host_for_http_10(&mut self) {
        self.default_host_for_http_10.clear();
    }

    // Param is passed by value, moved
    pub fn set_default_host_for_http_10(&mut self, v: ::std::string::String) {
        self.default_host_for_http_10 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_default_host_for_http_10(&mut self) -> &mut ::std::string::String {
        &mut self.default_host_for_http_10
    }

    // Take field
    pub fn take_default_host_for_http_10(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.default_host_for_http_10, ::std::string::String::new())
    }

    pub fn get_default_host_for_http_10(&self) -> &str {
        &self.default_host_for_http_10
    }
}

impl ::protobuf::Message for Http1ProtocolOptions {
    fn is_initialized(&self) -> bool {
        for v in &self.allow_absolute_url {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.allow_absolute_url)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.accept_http_10 = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.default_host_for_http_10)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.allow_absolute_url.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.accept_http_10 != false {
            my_size += 2;
        }
        if !self.default_host_for_http_10.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.default_host_for_http_10);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.allow_absolute_url.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.accept_http_10 != false {
            os.write_bool(2, self.accept_http_10)?;
        }
        if !self.default_host_for_http_10.is_empty() {
            os.write_string(3, &self.default_host_for_http_10)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Http1ProtocolOptions {
        Http1ProtocolOptions::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::BoolValue>>(
                    "allow_absolute_url",
                    |m: &Http1ProtocolOptions| { &m.allow_absolute_url },
                    |m: &mut Http1ProtocolOptions| { &mut m.allow_absolute_url },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "accept_http_10",
                    |m: &Http1ProtocolOptions| { &m.accept_http_10 },
                    |m: &mut Http1ProtocolOptions| { &mut m.accept_http_10 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "default_host_for_http_10",
                    |m: &Http1ProtocolOptions| { &m.default_host_for_http_10 },
                    |m: &mut Http1ProtocolOptions| { &mut m.default_host_for_http_10 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Http1ProtocolOptions>(
                    "Http1ProtocolOptions",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Http1ProtocolOptions {
        static mut instance: ::protobuf::lazy::Lazy<Http1ProtocolOptions> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Http1ProtocolOptions,
        };
        unsafe {
            instance.get(Http1ProtocolOptions::new)
        }
    }
}

impl ::protobuf::Clear for Http1ProtocolOptions {
    fn clear(&mut self) {
        self.clear_allow_absolute_url();
        self.clear_accept_http_10();
        self.clear_default_host_for_http_10();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Http1ProtocolOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Http1ProtocolOptions {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Http2ProtocolOptions {
    // message fields
    pub hpack_table_size: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub max_concurrent_streams: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub initial_stream_window_size: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub initial_connection_window_size: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    pub allow_connect: bool,
    pub allow_metadata: bool,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl Http2ProtocolOptions {
    pub fn new() -> Http2ProtocolOptions {
        ::std::default::Default::default()
    }

    // .google.protobuf.UInt32Value hpack_table_size = 1;

    pub fn clear_hpack_table_size(&mut self) {
        self.hpack_table_size.clear();
    }

    pub fn has_hpack_table_size(&self) -> bool {
        self.hpack_table_size.is_some()
    }

    // Param is passed by value, moved
    pub fn set_hpack_table_size(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.hpack_table_size = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_hpack_table_size(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.hpack_table_size.is_none() {
            self.hpack_table_size.set_default();
        }
        self.hpack_table_size.as_mut().unwrap()
    }

    // Take field
    pub fn take_hpack_table_size(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.hpack_table_size.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_hpack_table_size(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.hpack_table_size.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // .google.protobuf.UInt32Value max_concurrent_streams = 2;

    pub fn clear_max_concurrent_streams(&mut self) {
        self.max_concurrent_streams.clear();
    }

    pub fn has_max_concurrent_streams(&self) -> bool {
        self.max_concurrent_streams.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_concurrent_streams(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.max_concurrent_streams = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_max_concurrent_streams(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.max_concurrent_streams.is_none() {
            self.max_concurrent_streams.set_default();
        }
        self.max_concurrent_streams.as_mut().unwrap()
    }

    // Take field
    pub fn take_max_concurrent_streams(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.max_concurrent_streams.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_max_concurrent_streams(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.max_concurrent_streams.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // .google.protobuf.UInt32Value initial_stream_window_size = 3;

    pub fn clear_initial_stream_window_size(&mut self) {
        self.initial_stream_window_size.clear();
    }

    pub fn has_initial_stream_window_size(&self) -> bool {
        self.initial_stream_window_size.is_some()
    }

    // Param is passed by value, moved
    pub fn set_initial_stream_window_size(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.initial_stream_window_size = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_initial_stream_window_size(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.initial_stream_window_size.is_none() {
            self.initial_stream_window_size.set_default();
        }
        self.initial_stream_window_size.as_mut().unwrap()
    }

    // Take field
    pub fn take_initial_stream_window_size(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.initial_stream_window_size.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_initial_stream_window_size(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.initial_stream_window_size.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // .google.protobuf.UInt32Value initial_connection_window_size = 4;

    pub fn clear_initial_connection_window_size(&mut self) {
        self.initial_connection_window_size.clear();
    }

    pub fn has_initial_connection_window_size(&self) -> bool {
        self.initial_connection_window_size.is_some()
    }

    // Param is passed by value, moved
    pub fn set_initial_connection_window_size(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.initial_connection_window_size = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_initial_connection_window_size(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.initial_connection_window_size.is_none() {
            self.initial_connection_window_size.set_default();
        }
        self.initial_connection_window_size.as_mut().unwrap()
    }

    // Take field
    pub fn take_initial_connection_window_size(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.initial_connection_window_size.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }

    pub fn get_initial_connection_window_size(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.initial_connection_window_size.as_ref().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::default_instance())
    }

    // bool allow_connect = 5;

    pub fn clear_allow_connect(&mut self) {
        self.allow_connect = false;
    }

    // Param is passed by value, moved
    pub fn set_allow_connect(&mut self, v: bool) {
        self.allow_connect = v;
    }

    pub fn get_allow_connect(&self) -> bool {
        self.allow_connect
    }

    // bool allow_metadata = 6;

    pub fn clear_allow_metadata(&mut self) {
        self.allow_metadata = false;
    }

    // Param is passed by value, moved
    pub fn set_allow_metadata(&mut self, v: bool) {
        self.allow_metadata = v;
    }

    pub fn get_allow_metadata(&self) -> bool {
        self.allow_metadata
    }
}

impl ::protobuf::Message for Http2ProtocolOptions {
    fn is_initialized(&self) -> bool {
        for v in &self.hpack_table_size {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.max_concurrent_streams {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.initial_stream_window_size {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.initial_connection_window_size {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.hpack_table_size)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.max_concurrent_streams)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.initial_stream_window_size)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.initial_connection_window_size)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.allow_connect = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.allow_metadata = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.hpack_table_size.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.max_concurrent_streams.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.initial_stream_window_size.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.initial_connection_window_size.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.allow_connect != false {
            my_size += 2;
        }
        if self.allow_metadata != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.hpack_table_size.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.max_concurrent_streams.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.initial_stream_window_size.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.initial_connection_window_size.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.allow_connect != false {
            os.write_bool(5, self.allow_connect)?;
        }
        if self.allow_metadata != false {
            os.write_bool(6, self.allow_metadata)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Http2ProtocolOptions {
        Http2ProtocolOptions::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "hpack_table_size",
                    |m: &Http2ProtocolOptions| { &m.hpack_table_size },
                    |m: &mut Http2ProtocolOptions| { &mut m.hpack_table_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "max_concurrent_streams",
                    |m: &Http2ProtocolOptions| { &m.max_concurrent_streams },
                    |m: &mut Http2ProtocolOptions| { &mut m.max_concurrent_streams },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "initial_stream_window_size",
                    |m: &Http2ProtocolOptions| { &m.initial_stream_window_size },
                    |m: &mut Http2ProtocolOptions| { &mut m.initial_stream_window_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                    "initial_connection_window_size",
                    |m: &Http2ProtocolOptions| { &m.initial_connection_window_size },
                    |m: &mut Http2ProtocolOptions| { &mut m.initial_connection_window_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "allow_connect",
                    |m: &Http2ProtocolOptions| { &m.allow_connect },
                    |m: &mut Http2ProtocolOptions| { &mut m.allow_connect },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "allow_metadata",
                    |m: &Http2ProtocolOptions| { &m.allow_metadata },
                    |m: &mut Http2ProtocolOptions| { &mut m.allow_metadata },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Http2ProtocolOptions>(
                    "Http2ProtocolOptions",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Http2ProtocolOptions {
        static mut instance: ::protobuf::lazy::Lazy<Http2ProtocolOptions> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Http2ProtocolOptions,
        };
        unsafe {
            instance.get(Http2ProtocolOptions::new)
        }
    }
}

impl ::protobuf::Clear for Http2ProtocolOptions {
    fn clear(&mut self) {
        self.clear_hpack_table_size();
        self.clear_max_concurrent_streams();
        self.clear_initial_stream_window_size();
        self.clear_initial_connection_window_size();
        self.clear_allow_connect();
        self.clear_allow_metadata();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Http2ProtocolOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Http2ProtocolOptions {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct GrpcProtocolOptions {
    // message fields
    pub http2_protocol_options: ::protobuf::SingularPtrField<Http2ProtocolOptions>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl GrpcProtocolOptions {
    pub fn new() -> GrpcProtocolOptions {
        ::std::default::Default::default()
    }

    // .envoy.api.v2.core.Http2ProtocolOptions http2_protocol_options = 1;

    pub fn clear_http2_protocol_options(&mut self) {
        self.http2_protocol_options.clear();
    }

    pub fn has_http2_protocol_options(&self) -> bool {
        self.http2_protocol_options.is_some()
    }

    // Param is passed by value, moved
    pub fn set_http2_protocol_options(&mut self, v: Http2ProtocolOptions) {
        self.http2_protocol_options = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_http2_protocol_options(&mut self) -> &mut Http2ProtocolOptions {
        if self.http2_protocol_options.is_none() {
            self.http2_protocol_options.set_default();
        }
        self.http2_protocol_options.as_mut().unwrap()
    }

    // Take field
    pub fn take_http2_protocol_options(&mut self) -> Http2ProtocolOptions {
        self.http2_protocol_options.take().unwrap_or_else(|| Http2ProtocolOptions::new())
    }

    pub fn get_http2_protocol_options(&self) -> &Http2ProtocolOptions {
        self.http2_protocol_options.as_ref().unwrap_or_else(|| Http2ProtocolOptions::default_instance())
    }
}

impl ::protobuf::Message for GrpcProtocolOptions {
    fn is_initialized(&self) -> bool {
        for v in &self.http2_protocol_options {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.http2_protocol_options)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.http2_protocol_options.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.http2_protocol_options.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GrpcProtocolOptions {
        GrpcProtocolOptions::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Http2ProtocolOptions>>(
                    "http2_protocol_options",
                    |m: &GrpcProtocolOptions| { &m.http2_protocol_options },
                    |m: &mut GrpcProtocolOptions| { &mut m.http2_protocol_options },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<GrpcProtocolOptions>(
                    "GrpcProtocolOptions",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static GrpcProtocolOptions {
        static mut instance: ::protobuf::lazy::Lazy<GrpcProtocolOptions> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const GrpcProtocolOptions,
        };
        unsafe {
            instance.get(GrpcProtocolOptions::new)
        }
    }
}

impl ::protobuf::Clear for GrpcProtocolOptions {
    fn clear(&mut self) {
        self.clear_http2_protocol_options();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for GrpcProtocolOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GrpcProtocolOptions {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20envoy/api/v2/core/protocol.proto\x12\x11envoy.api.v2.core\x1a\x1eg\
    oogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\
    \x17validate/validate.proto\x1a\x14gogoproto/gogo.proto\"\x14\n\x12TcpPr\
    otocolOptions\"Y\n\x13HttpProtocolOptions\x12B\n\x0cidle_timeout\x18\x01\
    \x20\x01(\x0b2\x19.google.protobuf.DurationR\x0bidleTimeoutB\x04\x98\xdf\
    \x1f\x01\"\xbe\x01\n\x14Http1ProtocolOptions\x12H\n\x12allow_absolute_ur\
    l\x18\x01\x20\x01(\x0b2\x1a.google.protobuf.BoolValueR\x10allowAbsoluteU\
    rl\x12$\n\x0eaccept_http_10\x18\x02\x20\x01(\x08R\x0cacceptHttp10\x126\n\
    \x18default_host_for_http_10\x18\x03\x20\x01(\tR\x14defaultHostForHttp10\
    \"\xf3\x03\n\x14Http2ProtocolOptions\x12F\n\x10hpack_table_size\x18\x01\
    \x20\x01(\x0b2\x1c.google.protobuf.UInt32ValueR\x0ehpackTableSize\x12c\n\
    \x16max_concurrent_streams\x18\x02\x20\x01(\x0b2\x1c.google.protobuf.UIn\
    t32ValueR\x14maxConcurrentStreamsB\x0f\xba\xe9\xc0\x03\n*\x08\x18\xff\
    \xff\xff\xff\x07(\x01\x12l\n\x1ainitial_stream_window_size\x18\x03\x20\
    \x01(\x0b2\x1c.google.protobuf.UInt32ValueR\x17initialStreamWindowSizeB\
    \x11\xba\xe9\xc0\x03\x0c*\n\x18\xff\xff\xff\xff\x07(\xff\xff\x03\x12t\n\
    \x1einitial_connection_window_size\x18\x04\x20\x01(\x0b2\x1c.google.prot\
    obuf.UInt32ValueR\x1binitialConnectionWindowSizeB\x11\xba\xe9\xc0\x03\
    \x0c*\n\x18\xff\xff\xff\xff\x07(\xff\xff\x03\x12#\n\rallow_connect\x18\
    \x05\x20\x01(\x08R\x0callowConnect\x12%\n\x0eallow_metadata\x18\x06\x20\
    \x01(\x08R\rallowMetadata\"t\n\x13GrpcProtocolOptions\x12]\n\x16http2_pr\
    otocol_options\x18\x01\x20\x01(\x0b2'.envoy.api.v2.core.Http2ProtocolOpt\
    ionsR\x14http2ProtocolOptionsB6\n\x1fio.envoyproxy.envoy.api.v2.coreB\rP\
    rotocolProtoP\x01\xa8\xe2\x1e\x01J\xdf\x1f\n\x06\x12\x04\x02\0b\x01\n/\n\
    \x01\x0c\x12\x03\x02\0\x122%\x20[#protodoc-title:\x20Protocol\x20options\
    ]\n\n\x08\n\x01\x02\x12\x03\x04\x08\x19\n\x08\n\x01\x08\x12\x03\x06\0.\n\
    \t\n\x02\x08\x08\x12\x03\x06\0.\n\x08\n\x01\x08\x12\x03\x07\0\"\n\t\n\
    \x02\x08\n\x12\x03\x07\0\"\n\x08\n\x01\x08\x12\x03\x08\08\n\t\n\x02\x08\
    \x01\x12\x03\x08\08\n\t\n\x02\x03\0\x12\x03\n\x07'\n\t\n\x02\x03\x01\x12\
    \x03\x0b\x07'\n\t\n\x02\x03\x02\x12\x03\r\x07\x20\n\t\n\x02\x03\x03\x12\
    \x03\x0e\x07\x1d\n\x08\n\x01\x08\x12\x03\x10\0$\n\x0b\n\x04\x08\xa5\xec\
    \x03\x12\x03\x10\0$\nM\n\x02\x04\0\x12\x04\x15\0\x16\x01\x1a\x1a\x20[#no\
    t-implemented-hide:]\n2%\x20[#protodoc-title:\x20Protocol\x20options]\n\
    \n\n\n\x03\x04\0\x01\x12\x03\x15\x08\x1a\n\n\n\x02\x04\x01\x12\x04\x18\0\
    \x1e\x01\n\n\n\x03\x04\x01\x01\x12\x03\x18\x08\x1b\n\xe0\x02\n\x04\x04\
    \x01\x02\0\x12\x03\x1d\x02M\x1a\xd2\x02\x20The\x20idle\x20timeout\x20for\
    \x20upstream\x20connection\x20pool\x20connections.\x20The\x20idle\x20tim\
    eout\x20is\x20defined\x20as\x20the\n\x20period\x20in\x20which\x20there\
    \x20are\x20no\x20active\x20requests.\x20If\x20not\x20set,\x20there\x20is\
    \x20no\x20idle\x20timeout.\x20When\x20the\n\x20idle\x20timeout\x20is\x20\
    reached\x20the\x20connection\x20will\x20be\x20closed.\x20Note\x20that\
    \x20request\x20based\x20timeouts\x20mean\n\x20that\x20HTTP/2\x20PINGs\
    \x20will\x20not\x20keep\x20the\x20connection\x20alive.\n\n\r\n\x05\x04\
    \x01\x02\0\x04\x12\x04\x1d\x02\x18\x1d\n\x0c\n\x05\x04\x01\x02\0\x06\x12\
    \x03\x1d\x02\x1a\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1d\x1b'\n\x0c\n\
    \x05\x04\x01\x02\0\x03\x12\x03\x1d*+\n\x0c\n\x05\x04\x01\x02\0\x08\x12\
    \x03\x1d,L\n\x0f\n\x08\x04\x01\x02\0\x08\xf3\xfb\x03\x12\x03\x1d-K\n\n\n\
    \x02\x04\x02\x12\x04\x20\01\x01\n\n\n\x03\x04\x02\x01\x12\x03\x20\x08\
    \x1c\n\xb0\x02\n\x04\x04\x02\x02\0\x12\x03%\x023\x1a\xa2\x02\x20Handle\
    \x20HTTP\x20requests\x20with\x20absolute\x20URLs\x20in\x20the\x20request\
    s.\x20These\x20requests\n\x20are\x20generally\x20sent\x20by\x20clients\
    \x20to\x20forward/explicit\x20proxies.\x20This\x20allows\x20clients\x20t\
    o\x20configure\n\x20envoy\x20as\x20their\x20HTTP\x20proxy.\x20In\x20Unix\
    ,\x20for\x20example,\x20this\x20is\x20typically\x20done\x20by\x20setting\
    \x20the\n\x20*http_proxy*\x20environment\x20variable.\n\n\r\n\x05\x04\
    \x02\x02\0\x04\x12\x04%\x02\x20\x1e\n\x0c\n\x05\x04\x02\x02\0\x06\x12\
    \x03%\x02\x1b\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03%\x1c.\n\x0c\n\x05\
    \x04\x02\x02\0\x03\x12\x03%12\n\x8f\x02\n\x04\x04\x02\x02\x01\x12\x03+\
    \x02\x1a\x1a\x81\x02\x20Handle\x20incoming\x20HTTP/1.0\x20and\x20HTTP\
    \x200.9\x20requests.\n\x20This\x20is\x20off\x20by\x20default,\x20and\x20\
    not\x20fully\x20standards\x20compliant.\x20There\x20is\x20support\x20for\
    \x20pre-HTTP/1.1\n\x20style\x20connect\x20logic,\x20dechunking,\x20and\
    \x20handling\x20lack\x20of\x20client\x20host\x20iff\n\x20*default_host_f\
    or_http_10*\x20is\x20configured.\n\n\r\n\x05\x04\x02\x02\x01\x04\x12\x04\
    +\x02%3\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03+\x02\x06\n\x0c\n\x05\x04\
    \x02\x02\x01\x01\x12\x03+\x07\x15\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\
    \x03+\x18\x19\n\xe1\x01\n\x04\x04\x02\x02\x02\x12\x030\x02&\x1a\xd3\x01\
    \x20A\x20default\x20host\x20for\x20HTTP/1.0\x20requests.\x20This\x20is\
    \x20highly\x20suggested\x20if\x20*accept_http_10*\x20is\x20true\x20as\n\
    \x20Envoy\x20does\x20not\x20otherwise\x20support\x20HTTP/1.0\x20without\
    \x20a\x20Host\x20header.\n\x20This\x20is\x20a\x20no-op\x20if\x20*accept_\
    http_10*\x20is\x20not\x20true.\n\n\r\n\x05\x04\x02\x02\x02\x04\x12\x040\
    \x02+\x1a\n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x030\x02\x08\n\x0c\n\x05\
    \x04\x02\x02\x02\x01\x12\x030\t!\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\
    0$%\n\n\n\x02\x04\x03\x12\x043\0]\x01\n\n\n\x03\x04\x03\x01\x12\x033\x08\
    \x1c\n\xa2\x02\n\x04\x04\x03\x02\0\x12\x038\x023\x1a\x94\x02\x20`Maximum\
    \x20table\x20size\x20<https://httpwg.org/specs/rfc7541.html#rfc.section.\
    4.2>`_\n\x20(in\x20octets)\x20that\x20the\x20encoder\x20is\x20permitted\
    \x20to\x20use\x20for\x20the\x20dynamic\x20HPACK\x20table.\x20Valid\x20va\
    lues\n\x20range\x20from\x200\x20to\x204294967295\x20(2^32\x20-\x201)\x20\
    and\x20defaults\x20to\x204096.\x200\x20effectively\x20disables\x20header\
    \n\x20compression.\n\n\r\n\x05\x04\x03\x02\0\x04\x12\x048\x023\x1e\n\x0c\
    \n\x05\x04\x03\x02\0\x06\x12\x038\x02\x1d\n\x0c\n\x05\x04\x03\x02\0\x01\
    \x12\x038\x1e.\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03812\n\xe4\x01\n\x04\
    \x04\x03\x02\x01\x12\x04=\x02><\x1a\xd5\x01\x20`Maximum\x20concurrent\
    \x20streams\x20<https://httpwg.org/specs/rfc7540.html#rfc.section.5.1.2>\
    `_\n\x20allowed\x20for\x20peer\x20on\x20one\x20HTTP/2\x20connection.\x20\
    Valid\x20values\x20range\x20from\x201\x20to\x202147483647\x20(2^31\x20-\
    \x201)\n\x20and\x20defaults\x20to\x202147483647.\n\n\r\n\x05\x04\x03\x02\
    \x01\x04\x12\x04=\x0283\n\x0c\n\x05\x04\x03\x02\x01\x06\x12\x03=\x02\x1d\
    \n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03=\x1e4\n\x0c\n\x05\x04\x03\x02\
    \x01\x03\x12\x03=78\n\x0c\n\x05\x04\x03\x02\x01\x08\x12\x03>\x06;\n\x10\
    \n\t\x04\x03\x02\x01\x08\x97\x8d8\x05\x12\x03>\x07:\n\x8d\x05\n\x04\x04\
    \x03\x02\x02\x12\x04K\x02L@\x1a\xec\x01\x20This\x20field\x20also\x20acts\
    \x20as\x20a\x20soft\x20limit\x20on\x20the\x20number\x20of\x20bytes\x20En\
    voy\x20will\x20buffer\x20per-stream\x20in\x20the\n\x20HTTP/2\x20codec\
    \x20buffers.\x20Once\x20the\x20buffer\x20reaches\x20this\x20pointer,\x20\
    watermark\x20callbacks\x20will\x20fire\x20to\n\x20stop\x20the\x20flow\
    \x20of\x20data\x20to\x20the\x20codec\x20buffers.\n2\x8f\x03\x20`Initial\
    \x20stream-level\x20flow-control\x20window\n\x20<https://httpwg.org/spec\
    s/rfc7540.html#rfc.section.6.9.2>`_\x20size.\x20Valid\x20values\x20range\
    \x20from\x2065535\n\x20(2^16\x20-\x201,\x20HTTP/2\x20default)\x20to\x202\
    147483647\x20(2^31\x20-\x201,\x20HTTP/2\x20maximum)\x20and\x20defaults\
    \x20to\x20268435456\n\x20(256\x20*\x201024\x20*\x201024).\n\n\x20NOTE:\
    \x2065535\x20is\x20the\x20initial\x20window\x20size\x20from\x20HTTP/2\
    \x20spec.\x20We\x20only\x20support\x20increasing\x20the\x20default\n\x20\
    window\x20size\x20now,\x20so\x20it's\x20also\x20the\x20minimum.\n\n\r\n\
    \x05\x04\x03\x02\x02\x04\x12\x04K\x02><\n\x0c\n\x05\x04\x03\x02\x02\x06\
    \x12\x03K\x02\x1d\n\x0c\n\x05\x04\x03\x02\x02\x01\x12\x03K\x1e8\n\x0c\n\
    \x05\x04\x03\x02\x02\x03\x12\x03K;<\n\x0c\n\x05\x04\x03\x02\x02\x08\x12\
    \x03L\x06?\n\x10\n\t\x04\x03\x02\x02\x08\x97\x8d8\x05\x12\x03L\x07>\n\
    \xbe\x01\n\x04\x04\x03\x02\x03\x12\x04P\x02Q@\x1a\xaf\x01\x20Similar\x20\
    to\x20*initial_stream_window_size*,\x20but\x20for\x20connection-level\
    \x20flow-control\n\x20window.\x20Currently,\x20this\x20has\x20the\x20sam\
    e\x20minimum/maximum/default\x20as\x20*initial_stream_window_size*.\n\n\
    \r\n\x05\x04\x03\x02\x03\x04\x12\x04P\x02L@\n\x0c\n\x05\x04\x03\x02\x03\
    \x06\x12\x03P\x02\x1d\n\x0c\n\x05\x04\x03\x02\x03\x01\x12\x03P\x1e<\n\
    \x0c\n\x05\x04\x03\x02\x03\x03\x12\x03P?@\n\x0c\n\x05\x04\x03\x02\x03\
    \x08\x12\x03Q\x06?\n\x10\n\t\x04\x03\x02\x03\x08\x97\x8d8\x05\x12\x03Q\
    \x07>\nL\n\x04\x04\x03\x02\x04\x12\x03T\x02\x19\x1a?\x20Allows\x20proxyi\
    ng\x20Websocket\x20and\x20other\x20upgrades\x20over\x20H2\x20connect.\n\
    \n\r\n\x05\x04\x03\x02\x04\x04\x12\x04T\x02Q@\n\x0c\n\x05\x04\x03\x02\
    \x04\x05\x12\x03T\x02\x06\n\x0c\n\x05\x04\x03\x02\x04\x01\x12\x03T\x07\
    \x14\n\x0c\n\x05\x04\x03\x02\x04\x03\x12\x03T\x17\x18\n\x8a\x02\n\x04\
    \x04\x03\x02\x05\x12\x03\\\x02\x1a\x1a\xfc\x01\x20[#not-implemented-hide\
    :]\x20Hiding\x20until\x20envoy\x20has\x20full\x20metadata\x20support.\n\
    \x20Still\x20under\x20implementation.\x20DO\x20NOT\x20USE.\n\n\x20Allows\
    \x20metadata.\x20See\x20[metadata\n\x20docs](https://github.com/envoypro\
    xy/envoy/blob/master/source/docs/h2_metadata.md)\x20for\x20more\n\x20inf\
    ormation.\n\n\r\n\x05\x04\x03\x02\x05\x04\x12\x04\\\x02T\x19\n\x0c\n\x05\
    \x04\x03\x02\x05\x05\x12\x03\\\x02\x06\n\x0c\n\x05\x04\x03\x02\x05\x01\
    \x12\x03\\\x07\x15\n\x0c\n\x05\x04\x03\x02\x05\x03\x12\x03\\\x18\x19\n&\
    \n\x02\x04\x04\x12\x04`\0b\x01\x1a\x1a\x20[#not-implemented-hide:]\n\n\n\
    \n\x03\x04\x04\x01\x12\x03`\x08\x1b\n\x0b\n\x04\x04\x04\x02\0\x12\x03a\
    \x022\n\r\n\x05\x04\x04\x02\0\x04\x12\x04a\x02`\x1d\n\x0c\n\x05\x04\x04\
    \x02\0\x06\x12\x03a\x02\x16\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03a\x17-\
    \n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03a01b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
